sifiveinc/wake

bin/digraph, share/wake/lib/system/job.wake, src/database.cpp
Also, have the fuse runner save output jobs in sorted order.
This makes most output of 'wake -o ...' sorted, yet preserves
unusual order if the runner decides to do that.
Fixes #105
=> database: return outputs in the same order they are saved

fuse/fuse.cpp
With permission (via private email) of the authors, Miklos Szeredi and
Sebastian Pipping, we've agreed to relicense this file from GPL to Apache 2.
=> fuse.cpp: relicense under Apache 2

doc/tutorial.md, share/wake/lib/core/list.wake
The code examples all worked, but the accompanying text was woefully out-of-date.
=> tutorial: update to match current syntax

shim/shim.c
so that we don't need to absolute paths to executables in our cmdlines.
=> use execvp instead of execv

share/wake/lib/system/environment.wake
These methods should make it easy to do things like:
```
makePlan ("verilator", ...) ...
| editPlanEnvironment (getenv "VERILATOR_ROOT" | addEnvironmentPathOpt)
| setPlanResources ("verilator", Nil)
| runJob
```
=> environment: add some helper methods for manipulating keys

share/wake/lib/system/job.wake
If the resources needed aren't in the environment, they will fail.
However, they might also succeed.
This is important when making open source builds without a corporate
environment package that defines where packages are installed.
=> job: fuse and manual runners should always try to run

.circleci/config.yml, .circleci/dockerfiles/Dockerfile.centos_7_0, .circleci/dockerfiles/Dockerfile.centos_7_6, .circleci/dockerfiles/Dockerfile.debian_10, .circleci/dockerfiles/Dockerfile.ubuntu_16_04, .circleci/dockerfiles/Dockerfile.ubuntu_18_04, .dockerignore
I set up some CircleCI build rules so that every PR causes a build of wake on several OSes. This is my first time using CircleCI, but I have to say, this is a relatively nice experience compared to Travis CI because of the first-class Docker support.
I have builds running and passing on:
- CentOS 7.6 (I tried building on CentOS 6.x, but gave up after having to work around several oddities/bugs and finally after learning that CentOS 6.8's g++ does not have support for C++ 11)
- Debian 8 (Jessie)
- Debian 9 (Stretch)
- Ubuntu 16.04 (Xenial)
- Ubuntu 18.04 (Bionic)
I did check that this would have caught the bug fixed by https://github.com/sifive/wake/pull/128.
=> Add CircleCI build rules for several OSes.

build.wake, share/wake/lib/core/list.wake, share/wake/lib/core/option.wake, share/wake/lib/core/regexp.wake, share/wake/lib/core/result.wake, share/wake/lib/system/job.wake
h/t @terpstra for most of the work.
The motivating example was to turn `List (Result a b)` -> `Result (List a) b`.
This can be done with `findFail` which finds the first `Fail` in a `List` or returns `Pass (List a)`. There are related functions `findFailFn`, `findPass`, and `findPassFn`.
We already had `findSome` which is similar but for `List (Option a)`, so we also generalized that into `findSome`, `findSomeFn`, `findNone`, and `findNoneFn`.
=> Add functions for turning List of Option|Result to Option|Result of List

re2c/re2c.wake
CircleCI showed 'execve: re2c' in red.
=> re2c: it is acceptable to fail; don't log it

share/wake/lib/system/gcc.wake, share/wake/lib/system/job.wake, share/wake/lib/system/sources.wake, src/parser.cpp, src/wake.wake
```
global def jack =
makePlan ("ls", Nil) Nil
| setPlanLocalOnly True
| setPlanFnOutputs (\_ "file.txt", Nil)
| runJob
| getJobOutputs
```
When you ran this, you used to get:
```
$ wake jack                                                                                                     
script
hash_open: file.txt: No such file or directory
PANIC: Failed to hash file file.txt
Requirement !panic_called failed at src/exception.cpp:64
```
Now you get:
```
BadPath (Error "Could not hash file.txt" Nil), Nil
```
=> Fix hash panic

common/execpath.cpp
Turns out that PATH=... does not equal PATH=
=> execpath: actually find the PATH

share/wake/lib/system/job.wake
Previously, the fuse runner ignored these and the preload runner died.
I can only imagine how horribly wrong things would go with a slurm runner.
=> job: forbid absolute paths in visible list

src/status.cpp
This will help keep more useful compile history on the screen.
=> status: don't render jobs that last less than 0.2s

src/job.cpp
This is a stop-gap measure until we find a way to get 'ppoll' or equivalent.
=> job: don't use more file descriptors than select can support

debian/changelog.in
Bump the changelog to start accumulating changes for 0.16.
=> debian: start release cycle for 0.16-alpha

preload/open.c
This makes it possible to use 'cp -r' of visible files under the preload runner.
=> preload: also intercept and filter readdir

preload/wrap.cpp
The preload runner was incorrectly trying to create '.'
Fixes #183.
=> preload: fix jobs with output in workspace root

share/wake/lib/system/job.wake, src/database.cpp
This regression was introduced when '-c' was added!
The intended behaviour is:
- if we would like to 'reuse' a job and MODIFIED outputs exist,
abort and let the user know to remove (or stash) their hand
edits of a built file.
- if you have a completed build and run wake with '-c', all build
steps are rerun and the hash is cross-checked against prior run
=> database: unless run with '-c', output hashes are allowed to change

src/job.cpp
Due to rounding error, these expressions could break the invaraint:
status_state.total -= status_state.remain - crit.pathtime
status_state.remain = crit.pathtime;
By contrast, these expressions cannot:
status_state.total = crit.pathtime + (status_state.total - status_state.remain);
status_state.remain = crit.pathtime;
If total >= remain, then E = (total - remain) >= 0.
Thus, status_state.total = crit.pathtime + E >= crit.pathtime = remain.
By contrast, the expression
status_state.total = status_state.total - (status_state.remain - crit.pathtime)
could violate the invariant if (remain - pathtime) rounds up.
=> job: maintain the invariant status_state.total >= status_state.remain

src/regexp.cpp, src/sfinae.h, src/value.cpp, src/value.h
This situation causes wake to crash.
=> Detect when an old re2 library is combined with a large string input

src/bind.cpp
This bug oddly did not appear until other changes were made to bind.cpp
=> bind: fix initial values for Tarjan's algorithm

preload/wrap.cpp
Fixes #207.
Obviously, if a build does this (output the same file from two different
Jobs), it is buggy.  However, we should fail later and with a better error
message.
=> preload: don't fail in runner when conflicting outputs races

src/gc.cpp, src/gc.h
By enforcing alignment, we can eliminate heap-size pessimism.
=> GC: half the consumed heap memory

src/database.cpp, src/job.cpp, src/string.cpp
Conversion to-from void* should be a static_cast.
=> wake: remove non-conforming use of reinterpret_cast

.circleci/config.yml
The _static and _source directories are blocked by jekyll.
=> circleci: disable jekyll on gh-pages and release only tar/deb/rpms

fuse/daemon.cpp, fuse/fuse.cpp
daemon quits after: 2+4+8+16 = 30 seconds of retry
client aborts after: 10ms*(1+2+...+2048) = 40 seconds of retry.
=> fuse: adjust timeouts for better restart

share/wake/lib/system/job.wake
To do this correctly would require really parsing shell code.
A simple regexp will fail due to comments and strings.
=> shellJob: don't try to escape scripts to one line

share/wake/lib/system/job.wake, src/job.cpp, src/job.h, src/main.cpp
This is now possible:
```
editPlanUsage (setUsageMemBytes XXX _)
```
wake -p50 will limit wake to using only 50% of memory+cpu+etc, guided by:
1. the database-statistics-based predicted usage
2. the user supplied predict usage
3. the default guess (1 thread, 2MiB)
=> User-controlled Plan Usage

src/expr.cpp
Top has DefMap children with no body.
=> stop-after-parse: fix nullptr dereference

share/doc/wake/from-scala.adoc
I took a stab at writing a document aimed at describing Wake from the perspective of a Scala programmer. I am neither a Wake nor a Scala expert, so feel free to make any changes that you want to this.
This is not comprehensive, but I thought it at least covered some of the most common data types used in Wake. I wish this talked a bit more about other, non-data-type similarities and differences between Scala and Wake, but I haven't figured out how to organize that kind of information yet.
Note that I tried out writing this in AsciiDoc, since I thought it'd be a richer markup language for writing documentation. However, if you prefer a different language like Markdown, I could port this over (although the codes blocks within the table may be tricky to do in Markdown without relying on …
=> Add documentation describing Wake from a Scala perspective.

share/wake/lib/system/job.wake
Makes `makeJSONRunner` accept a tuple for better backwards-compatibility. Also adds `extraArgs` to allow passing of extra arguments to `rawScript`.
=> makeJSONRunner: make input a tuple, add extraArgs

Makefile, wake.spec.in
Installing into the working directory leads to problems with duplicated
symbols which can surprise new users.
Now, 'make DESTDIR=/wherever install' acts as people expect.
Fixes #256.
=> make: install now installs to /usr/local by default

src/deadcode.cpp, src/expr.cpp, src/expr.h, src/gc.h, src/parser.cpp, src/runtime.cpp, src/value.cpp, src/value.h
This also makes inlining constants free.
=> wake: move Literals to a shared constant pool

src/gc.cpp, src/gc.h, src/prim.cpp
Profiling on linux using 'perf' indicated large pause times when accessing memory in trivial functions. This led me to conclude that we were seeing a lot of page faults. Further investigation revealed the problem was that our GC heap allocations were the problem.
On a large (private) repository, this led to the following performance change:
```
old             new
user    sys     user    sys
11.1    12.6    9.5     1.9
10.4    14.9    9.4     2.0
10.5    14.9    9.8     1.9
```
The big difference is in the "system time" which goes from being the dominant cost (15s) to minor (2s).
=> Reuse space

src/cse.cpp, src/main.cpp, src/prim.cpp, src/scope.cpp, src/ssa.cpp, src/ssa.h
The function '\_ x' is the same, no matter where 'x' is on the stack.
Of course, a closure must also hash the contents of 'x'.
=> hash: differently scoped identical functions are identical

share/wake/lib/core/tuple.wake, src/parser.cpp
This adds support for variable-length tuples using heterogenously typed lists.
=> Variable length tuples

share/wake/lib/system/job.wake, src/database.cpp, src/database.h, src/gc.h, src/job.cpp, src/scope.cpp, src/ssa.cpp, src/value.cpp, src/value.h
This is finally possible to fix!
We can now hash functions in a way that is stable enough to only change if a used value or expression differs. ie: the false positive rate is now low enough not to cause builds to waste time.
NOTE: The runner is not included into this test. Otherwise, switching between local/remote build environments would force a rebuild.
=> Job: changing FnInputs, FnOutputs, Resources, or Keep -> rerun

fuse/daemon.cpp
Fixes #311.
It turns out 1MiB was not enough for some tools.
=> fuse: allow up 128MiB JSON Job descriptions

common/unlink.cpp, common/unlink.h, fuse/daemon.cpp, preload/wrap.cpp
Both FUSE and preload runners now use a shared 'rm -rf' helper method, which tries very hard to clean out files. In particular:
- preload runner: clean up even read-only .build/xxx directories
- fuse runner: erase invisible outputs to uphold fiction that nothing was there
=> Deep cleaning

fuse/daemon.cpp
This PR protects visible files from being the target of rename()
=> FUSE: prevent overwrite of visible files

share/wake/lib/system/incremental.wake, share/wake/lib/system/job.wake, src/string.cpp
This works!:
```
global def make Unit =
makePlan (which "make", "foo", Nil) (sources "x" `.*`)
| setPlanDirectory "x"
| runIncrementalJob "foo" (\_ True)
| getJobOutputs
```
Fixes #65. As State files no longer exist!
Fixes #319. Visible files are now strictly read-only, but that's ok, because we now have a better way to run incremental jobs.
=> Replace state files with runIncrementalJob

fuse/daemon.cpp
Increase the size of the JSON string. The old value, 1Mib, results in I/O error messages from wake. The increase in MAX_JSON is already part of master - this PR back ports it to v0.17.
Note we will also need to create and distribute a 0.17.1 release of wake.
Update: Will need the same change in the 0.15 release.
=> Bump MAX_JSON to 128 MiB.

debian/changelog.in
Since @terpstra is out for a couple weeks, I'm going to take charge of getting the max JSON file size change backported and included in a new release.
Since the change was already backported onto the `v0.15` branch, I believe all I need to do is update the Debian changelog file with the latest release info. After this is merged in and the release tag is created, I'll create another entry in the changelog.in file for the "next" release.
My understanding of the process for cutting a release is the following:
1. Update the `@VERSION@` release information in `debian/changelog.in` to match the actual release info and release date, since the previous information is just a placeholder. (e.g. https://github.com/sifive/wake/commit/bea16cdeda1fea61e36b476f1b29994e87b205ba)
2. Merge that into the …
=> Set release date and committer for v0.15.3 release.

debian/changelog.in
Also add 0.17.0 entry to changelog
* Increase maximum size of JSON files to 128 MiB.
=> 0.17.1: set release date

src/bind.cpp, src/inline.cpp
global def f Unit = 42
This should not be type: a => Integer
It should be: Unit => Integer
This happened because an inling optimization was applied in the front-end.
Moving it to the backend resolves the type-checker freedom.
=> wake: Fix a type checker bug in single arg destructors

.circleci/config.yml
It's not obvious to people that some of these methods are not part of the public API.
=> circleci: don't include wake's own build rules in reference html

share/wake/lib/core/json.wake
Currently the return type of `parseJSONBody` is `Result JValue String`. This PR makes the return value `Result JValue Error` to be consistent with the other functions that return `Result`.
=> Make parseJSONBody fail with Error instead of String

share/doc/wake/syntax/vim/syntax/wake.vim
This adds a few things to the Vim syntax highlighting rules that have been bugging me for a little while.
https://github.com/sifive/wake/commit/ef9893b335ce6b22c1821afb7e624efb7a75e434 - Adding the `tuple` and `target` keywords
https://github.com/sifive/wake/commit/ddbbc981fcfae51ca9d3f436fdb64a9b2428c456 - Adding numeric literals, based on my attempt at translating the [regexes from the Wake parser](https://github.com/sifive/wake/blob/5f67a1e4b9e26b83a31f9c1dbdb22348c141b54e/src/symbol.re#L501-L521) to Vim's regex syntax.
=> Improve Vim syntax highlighting

share/wake/lib/system/path.wake
make `writeImp` a target so that calling `write` with the same arguments does not result in an error.
```
$ wake 'write "foo" "bar", write "foo" "bar", Nil'
File output by multiple Jobs: foo
```
=> write: use target to avoid multiple output errors

share/wake/lib/system/cp.wake
running the command `wake 'installIn "asdf" "asdf".makeError.makeBadPath, installIn "asdf" "lkj".makeError.makeBadPath, Nil'` gives the following error
```
ERROR: Target subkey mismatch for share/wake/lib/system/job.wake:247:[8-78]
To debug, rerun your wake command with these additional options:
--debug-target=15313308315147462255 to see the unique target arguments (before the '\')
--debug-target=179846794147169920 to see the first invocation's extra arguments
--debug-target=3543282263022983498 to see the second invocation's extra arguments
```
running with `--debug-target=15313308315147462255` shows
```
Debug-target hash input was: ("/bin/cp", "BADPATH", "asdf/BADPATH", Nil), Nil, ".", "", Nil
```
This makes change makes it so that `installAs` and `installIn` will propagate the bad paths …
=> installAs: check for BAD PATH before running

src/database.cpp
If you try to run a job with identical command-line/etc, but reduced visible files, it does not rerun. That is a problem is one of the visible files you removed was an input to that job, since presumably the job will have been affected.
=> database: don't allow job reuse when inputs go missing

share/doc/wake/tutorial.md, src/main.cpp, src/sources.cpp, src/sources.h, tests/test_all.sh, tests/test_util.sh, tests/wake-ignore.t
Files called `.wakeignore` can contain globs to
exclude wake source files from usage.
The exclusions are globs and are relative
to the root of the workspace.
```
workspace
├── wake.db
├── repo1
│   └── foo.wake
└── repo2
└── repo1
└── foo.wake
```
If `repo1` is checkout out twice, like above, then if a `.wakeignore` file at path`workspace/repo2` contained `repo2/repo1` then `foo.wake` would not be read twice.
Issue #355
=> Search for .wakeignore files

share/wake/lib/system/path.wake, src/main.cpp, src/prim.h, src/string.cpp
This is necessary to be able to process file names passed to wake functions from the command line.
=> wake: expose cwd where wake was invoked

src/cse.cpp, src/inline.cpp, src/ssa.cpp, src/ssa.h
A very important inlining optimization is the singleton-exemption.
This allows inlining of a function to proceed (no matter how large the
function is) if there is only one use of that function.
A prominant example would be 'map (someFnHere) list'.
We want to always transform that code into a loop with someFnHere inside it.
The wake parser also implements pattern matching using large functions that
are invoked only once.  It is very important to inline these in order to
expose further inlining opportunities in the inner clauses.
However, wake had a bug (fixed by this PR) whereby some functions were
erroneously retaining their singleton status even after transformations (in
this case inlinling itself) added additional references.
Futhermore, when we inlined a singleton function, we left …
=> wake: fix an inlining bug that consumed exponential memory

src/bind.cpp, src/parser.cpp
Segfaults, even on bad input, leave a bad taste in people's mouths.
Example: `global def`
=> Fix parser segfault

.circleci/config.yml, Makefile, build.wake, debian/rules, share/doc/wake/tour/packages.adoc, share/wake/lib/system/path.wake, src/bind.cpp, src/main.cpp, src/prim.h, src/string.cpp
Invoking wake now lists subcommands exported by a package.
For example:
```
terpstra@peach:~/wake$ ./bin/wake
Available wake subcommands:
build
install
```
Subcommands are functions that accept List String and return Result.
Running 'wake build default' from the command-line will result in evaluation of 'build ("default", Nil)'.
This PR also adds two new functions to make coping with files provided by the command-line:
'in dir path' - combines dir and path
'cwd' - the directory where wake was invoked
=> Wake command-line subcommands now controlled by package exports

src/inline.cpp
Normally, wake does not inline recursive functions.
However, using a Y combinator can hide this from wake.
For example:
````
data Foo = Foo (Foo => Integer => Integer)
def foo (Foo self) x = if x == 0 then 1 else x * self (Foo self) (x-1)
def bar x = foo (Foo foo) x
````
In this definition, 'foo' does not look like a recursive function to wake's
front-end.  However, 'bar' closes foo over itself.  This now creates a
situation where the inliner can inline foo over and over again forever.
The fix?: mark an inlined function recursive for the duration of inlining.
=> inline: fix a case of infinite recursion

src/parser.cpp, src/regexp.cpp
God knows why you would want to do this, but it is syntactically legal and
thus should work.
=> parser: support regexp as pattern literals

gopt/gopt.c, share/wake/lib/system/path.wake, src/main.cpp, src/prim.h, src/sources.cpp, src/sources.h, src/string.cpp
This PR:
- makes it possible to invoke wake as a shell script
- passes options after a target to the target
- removed package name from --exports
- auto-initializes a wake.db where it find a wit-lock.json
- expands the legal list of targets to include non-Results
=> Improved command line

src/parser.cpp
The parser was desugaring the table creation on top of the target token.
Fixes #392.
=> html: hide internal 'Target' type on mouse-over of 'target'

src/parser.cpp
All of these forms are now legal:
```
require PATTERN = BODY else OTHERWISE
require PATTERN = BODY
else OTHERWISE
require PATTERN = BODY else
def ...
OTHERWISE
require PATTERN = BODY
else
def ...
OTHERWISE
require PATTERN =
def ...
BODY
else OTHERWISE
require PATTERN =
def ...
BODY
else
def ...
OTHERWISE
```
These are illegal:
```
require PATTERN =
def ...
BODY else OTHERWISE
require PATTERN =
def ...
BODY else
def ...
OTHERWISE
```
=> require: enable 'else' combined with a block expression

share/doc/wake/syntax/vim/syntax/wake.vim
Highlight topic names as Identifiers.
Highlight package/import/export keywords and Includes.
Highlight panic as Exception.
Correctly highlight unary/binary as keywords and not identifiers.
I don't really know what I'm doing with vim syntax highlighting, but I think this makes it look better and closer to what I'm used to, at least for my vim color scheme. Yes, I know that any identifier that follows a `def` or `topic` in the import/export list gets incorrectly colored, and, yes, I know that operators are kind of broken, but I don't think I can fix that without spending a lot more time learning how vim syntax highlighting works.
=> vim: Update syntax highlighting for new keywords.

src/main.cpp
There was a memory leak in this case (the unparsed first argument).
=> main: don't assert fail on 'wake x.y'

src/integer.cpp, src/vector.cpp
If a person asks for a multi-megabyte Integer, let them have it.
Likewise, there should be no limit on Vector sizes.
If you run out of memory, fine.
=> runtime: remove upper-limits on vector and integer sizes

share/wake/lib/core/double.wake, src/double.cpp, src/parser.cpp, src/prim.h
<. <=. >=. >. ==. all return False if either side is a NaN
!=. returns True if either side is a NaN
<=>. returns None if either side is a Nan (else Some Order)
Previously, these comparisons caused the runtime to panic.
=> Double: use IEEE754 comparison rules

src/integer.cpp
Don't fail with "floating point exception" and unclean exit.
Fail with "Requirement !division_by_zero failed" and cleanly exit.
=> Integer: powm _ _ 0 is also division by zero

src/inline.cpp
If we allowed this, the function which received the movement would be changed
by adding an unrelated function sharing use of the now-not-singleton function.
We want function hashes to remain stable across source-code changes, to
improve reuse of stored values in the cache.
=> inline: do not move top-level singleton functions

.circleci/config.yml, .circleci/dockerfiles/alpine, .circleci/dockerfiles/centos-6.6, .circleci/dockerfiles/centos-7.6, .circleci/dockerfiles/debian-testing, .circleci/dockerfiles/debian-wheezy, .circleci/dockerfiles/ubuntu-14.04, .circleci/dockerfiles/ubuntu-16.04, .circleci/dockerfiles/ubuntu-18.04, build.wake, debian/rules, wake.spec.in
This PR switches Circle CI to using VMs for builds. Those VMs can then run docker with the appropriate flags to enable FUSE.
This is helpful, because we're about to start making a bunch of improvements to FUSE.
=> CircleCI: Enable fuse

fuse/daemon.cpp
On linux you previously got this error:
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
=> fuse: allow the .fuse directory to already exist

share/wake/lib/system/job.wake
This is useful to add to plans when we want to make the fuse-wake input json (as a string) more deterministic on repeat job invocations.
=> Add sortPaths function

src/exception.cpp, src/main.cpp, src/prim.h
On sufficiently large projects, `wake -g` runs out of stack space.
This was caused by a now unnecessary code path which nested all symbols.
That code has been removed.
=> Fix globals stack overflow

Makefile, build.wake, debian/rules, fuse/fuse.cpp, share/wake/lib/system/job.wake, wake.spec.in
These isolation levels are supported by requesting resources:
- isolate/workspace; makes the workspace appear to be /var/cache/wake
- isolate/user; makes the build user appear to be root
- isolate/host; makes the hostname appear to be build.local
- isolate/net; disables network access
=> fuse: support unshare isolation for user, host, net, and workspace

share/wake/lib/core/list.wake, share/wake/lib/core/tree.wake, share/wake/lib/system/incremental.wake, share/wake/lib/system/job.wake, src/bind.cpp, src/bind.h, src/expr.h, src/main.cpp, src/parser.cpp
This PR detects and warns on any unused definitions, topics, or arguments.
This PR adds a `--fatal-warnings` option, which prevents execution if there are any warnings.
Fixes #432.
=> Detect and report any unused definitions, topics, or arguments

scripts/fetch
circleCI now uses redirects, which must be enabled
Added the static tarball as well
=> fetch: update with new circleCI

fuse/fuse.cpp
These calls should never fail, but if they do, report an error and continue.
=> fuse: fix warnings from hostname system call

share/wake/lib/core/option.wake
Alternatively could do:
```
export def orElse alt x = match x
Some _ = x
None   = alt
```
That saves an object allocation but this optimization could also be performed by the compiler.
I opted for what I PRed to keep it consistent with the other option functions (eg. `getOrElse`)
=> Simplify orElse

src/job.cpp
I recently reran wake/master on freeBSD and found a regression when there were more cores on the virtual machine.
These three commits fix the issue.
The symptom was that child processes of wake had a limit of 64 file descriptors, which can cause even reasonable software to break.
=> FreeBSD limits

src/inline.cpp, src/main.cpp, src/ssa.cpp
When trying to debug what code was compiled to, the pre-scoped form of SSA is a lot easier to read.
You can see this output when you use the secret developer --stop-after-ssa option. This shows what the wake files got compiled into after applying optimization.
=> Better SSA output

src/main.cpp
Previously, `wake foo.kk` would output:
```
Specified target 'foo.kk' is not a legal identifier
Segmentation fault
```
Now it outputs:
```
Specified target 'foo.kk' is not a legal identifier
>>> Aborting without execution <<<
```
=> main: fix segfault on illegal input

.circleci/config.yml, scripts/fetch
Servers no longer supply packages for this distribution...
=> CI: remove end-of-life CentOS 6.6 support

share/wake/lib/system/incremental.wake
Some build tools (zinc) record timestamps in their own database.
We need to restore the timestamp with nanosecond precision to coax them into
reusing output saved in a tar.gz.
=> runIncrementalJob: record timestamps precise to the nanosecond

share/wake/lib/system/incremental.wake
There is now claimFileAsPathIn to put a file in a directory not created
using wake's mkdir. Otherwise, claimFileAsPath will auto-create the directory.
Fixes #493.
=> claimFileAsPath: now create output directory

src/main.cpp
This makes it possible to do stuff like:
```
wake defaultScalaContext.getScalaCompiler a b c d
```
... and have the expression work as expected.
As discussed on slack.
=> main: allow any expression as the first argument to wake

share/wake/lib/system/job.wake, src/database.cpp, src/database.h, src/describe.cpp, src/describe.h, src/job.cpp, src/main.cpp
Jobs can now have key-value annotations added to them in the database.
This is useful for tools which will introspect the database post-build.
For example, CI or a build server protocol implementation.
The new functionality works like this:
- setJobTag job "key" "value"
- wake -v --job &lt;job-id&gt; # Dump all tags for the specified job
- wake --tag-dag &lt;regexp&gt; # Dump a dependency DAG including only the tagged jobs
- wake --get-tag &lt;job-id&gt; &lt;tag-name&gt;
=> Database tagging API

src/sources.cpp
Otherwise branch names can get interpreted as wake files.
Fixes #491.
=> files: ignore anything inside a .git folder

src/exception.cpp
Printing out a failing REQUIRE line number for the c++ code on calls to `panic` was confusing.
This does not yet change panic to unreachable and then add back a "real" panic. That may be a follow-up PR down the road.
=> exception: don't report C++ line numbers on panic

.gitignore, bsp/bsp.cpp, bsp/bsp.wake, build.wake, src/main.cpp
This PR adds support for the build server protocol, as used by scala metals.
To use this functionality, you need wake scripts that pass the necessary information via tags and a bsp output stream.
=> Build Server Protocol

src/sources.cpp
Auto-create a wake.db in projects with a .wakeroot file in them.
=> sources: use .wakeroot instead of wit-lock.json

bsp/bsp.cpp
Depending on where the bsp is invoked, you could totally end up with a pipe
descriptor in the range of 1-5 before dup2.
=> bsp: harden pipe descriptor setup

bsp/bsp.cpp
The BSP server might be the first program to touch a fresh workspace.
In that case, do not abort due to the absense of wake.db
=> bsp: be willing to initialize a wake workspace

fuse/daemon.cpp, fuse/fuse.cpp
If a client tried to connect to the FUSE daemon between the time when the FUSE daemon started to exit and when it succeeded in exiting, there was a race condition, whereby the open of '.f.fuse-waked' succeeds, but the daemon exits anyway, leaving the client unable to make forward progress.
The solution taken is to recognize that once an exit attempt had been made, it cannot be stopped.  Instead, any future attempts to open '.f.fuse-waked' must fail.  Careful synchonization is needed, because canceling the SIGALRM does not guarantee the absence of invocations of handle_exit.
Revert #521 since that debug code was/is not actually helpful... and should now be unreachable, anyway.
=> Fix FUSE exit race

common/membytes.h, fuse/fuse.cpp, preload/wrap.cpp, src/job.cpp
Fixes #530.
It turns out that the units of ru_maxrss is platform dependent.
Put all the platforms I could easily find documentation for into a new
shared header file.  Use this header macro instead of ru_maxrss.
=> getrusage: add platform-dependent maxrss accessor

bsp/bsp.cpp
The BSP previously only transformed workspace:/// URIs in tags. Now it does it for messages too.
=> BSP expand message paths

fuse/fuse.cpp, share/wake/lib/system/job.wake
The workspace location is no longer hardcoded in fuse-wake, but instead hardcoded via wakelang (where it could become flexible later)
* Add `type` field to fuse-wake mount fields, define `bind` and `workspace` as fields.
* Remove the automatic 'hide fuse' mount of `workspace/.fuse/$PID -> workspace`.
* In wakelang's `makeJSONRunner`, add `workspace` mount type to replace the above 'hide fuse'.
* Consolidate logic for choosing the directory to run the job in (on the fuse-wake side).
The `workspace` mount type is just a `bind` mount type, except that the `source` is not provided by the json, instead it is the `.fuse/$PID` directory.
=> Add 'workspace' mount type

.github/workflows/build.yaml, fuse/fuse.cpp
This builds `wake` for MacOS.
I suspect that it's using the preload runner to do the build of wake, as `osxfuse` claims that it needs a reboot when it is being installed, but it should at least build-check the fuse codepath
```
osxfuse requires a kernel extension to work.
If the installation fails, retry after you enable it in:
System Preferences → Security & Privacy → General
For more information, refer to vendor documentation or this Apple Technical Note:
https://developer.apple.com/library/content/technotes/tn2459/_index.html
You must reboot for the installation of osxfuse to take effect.
```
=> Move 'ifdef linux' to remove warning on MacOS, add MacOS CI test

fuse/fuse.cpp
Inside a user namespace, you are not allowed to separate mounts that you inherited from another mount namespace from their child mounts.
(though you're allowed to remount over the children in your own namespace)
So whenever a mount has subdirectories with mounts in them, we _must_ be recursive when we bind mount.
Since there is no downside to requesting recursive when the mount has no children, we apply `MS_REC` to all bind mounts. We could make this configurable in the future if we found a need to.
I ran into this when being denied trying to bind mount `/proc` which has the child `/proc/sys/fs/binfmt_misc`
=> Always use 'recursive' for bind mounts

fuse/fuse.cpp
Add a `tmpfs` mount type to fuse-wake.
Tested with:
```
$ cat tmpfs.in.json
{
"command": [
"bash", "-c", "findmnt | grep mnt; ls -l /mnt; touch /mnt/foo; ls -l /mnt"
],
"environment": [
"PATH=/usr/bin:/bin"
],
"visible": [],
"directory": ".",
"mounts": [
{
"type": "tmpfs",
"destination":"/mnt"
},
{
"type": "workspace",
"destination": "."
}
],
"stdin": "",
"resources": [],
"version": "v0.21.0-alpha-4-gde85a32-dirty",
"usage": {
"status": 1,
"runtime": 5.40870000000000031e-02,
"cputime": 4.00000000000000008e-03,
"membytes": 3289088,
"inbytes": 0,
"outbytes": 0
}
}
$ ../fuse-wake tmpfs.in.json out.json
`-/mnt   tmpfs   tmpfs   rw,nodev,relatime,uid=1375,gid=1375
total 0
total 0
-rw-rw-r-- 1 matthew matthew 0 Feb 18 13:40 foo
```
=> Add 'tmpfs' mount type to fuse-wake

src/main.cpp, src/sources.cpp
This is a critical work-around for a bug in our builds.
If something renders a portion of the workspace unreadable while wake starts, wake cannot abort.
The potential causes of this are: permission denied and/or directory/file deleted concurrently.
While it is certainly the case that both of these situations are bad and should be avoided, wake needs to bee as robust as possible. It's quite possible the affected files were not relevant to the build.
=> Ignore enumeration failures

Makefile, common/jparser.cpp, common/json5.h, fuse/client.cpp, fuse/fuse.cpp, fuse/fuse.h, fuse/fuse.wake
This further breaks up the fuse-wake fuse.cpp `main()` function
* main() function created in new file: client.cpp
* main() handles `argv` and reads/writes the input/output json files
* run_fuse() handles the bulk of the work that main() used to do
* some queries of global state are moved out of run_fuse() into main()
The commits in the series are mostly meaningful
=> fuse-wake: accept string inputs

fuse/namespace.cpp, share/wake/lib/system/job.wake
It can be useful to be able to create directories inside tmpfs mounts to act as further mount points.
Additionally, if you want to bind a file in you may want to create a file as a destination mount point.
Example use-case: run an X11 application using the .Xauthority file to authenticate with the X server
```
{
"command": [
"xeyes"
],
"environment": [
"PATH=/usr/bin:/bin",
"HOME=/home/user",
"DISPLAY=":0"
],
"mount-ops": [
{ "type": "bind", "source":"/tmp/rootfs", "destination": "/mnt"},       
{ "type": "tmpfs", "destination": "/mnt/home"},
{ "type": "create-dir", "destination": "/mnt/home/user" },
{ "type": "create-file", "destination": "/mnt/home/user/.Xauthority" },
{ "type": "bind", source: "/home/myusername/.Xauthority", "destination": "/mnt/home/user/.Xauthority" },
...
```
=> fuse-wake: add create-file and create-dir mount operations

fuse/namespace.cpp
This makes the user and group id mapping configurable from the json
You could set it to 0/0, or 1000/1000 or leave out those json keys and get your real id
```
{
"command": ["bash"],
"environment": [
"PATH=/usr/bin:/bin",
],
"visible": [],
"directory": ".",
"user-id": 0,
"group-id": 0,
"mount-ops": [
...
```
=> fuse-wake: configurable user/group id

.circleci/config.yml, .circleci/dockerfiles/centos-6.6, .circleci/dockerfiles/centos-7.6, .circleci/dockerfiles/debian-testing, .circleci/dockerfiles/ubuntu-16.04, .circleci/dockerfiles/ubuntu-18.04, .gitignore, Makefile, build.wake, debian/control, fuse/client.cpp, fuse/fuse.cpp, fuse/fuse.wake, gopt/gopt-arg.c, gopt/gopt-arg.h, src/main.cpp, wake.spec.in, wakebox/build.wake, wakebox/main.cpp
This creates a separate executable for wakebox, so that it can evolve its CLI independently of fuse wake.
Longer term, we may move all the linux-only code to be wakebox only, and leave fuse-wake for non-linux platforms.
The actual arguments for the CLI are not final and will likely change in the near future.
Some refactoring happened too
* `arg` for gopt has moved into a shared location
* an argument to ignore the `stdin` json value is passed through to fuse.cpp
* Added squashfuse dependency to deb/rpm packages
I suspect that debian wheezy, ubuntu 14.04 and centos 6.6 are simply too old to use _any_ of the user namespace functionality, and they also don't have squashfuse packages. So they're likely broken as we haven't been feature testing the kernel to check if we should mount .fuse/$PID …
=> wakebox: a CLI separate from fuse-wake

wakebox/build.wake, wakebox/main.cpp
In wakebox it's useful to directly enter a shell environment, disregarding the `command` value from the params file.
This adds an option `-s/--force-shell` which changes the run command to `/bin/sh` and adds the originally intended command to an environment variable called `WAKEBOX_CMD` which can be eval'd
```
matthew@computer:/home/matthew/work$ wakebox -s -p example.wb
user@wakebox:/workspace$ env | grep WAKE
WAKEBOX_CMD="bash" "-c" "echo \"hello world\""
user@wakebox:/workspace$ eval $WAKEBOX_CMD
hello world
```
~There's also some refactoring, moving the JAST parse() into main()~
=> wakebox: add --force-shell arg

common/json5.h, fuse/fuse.cpp
As discussed in https://github.com/sifive/wake/pull/582, this replaces the custom json that reports status to wake
=> fuse: refactor to use JAST for result output

common/execpath.cpp, common/execpath.h, fuse/fuse.cpp, fuse/namespace.cpp, fuse/namespace.h, wakebox/main.cpp
This allows the squashfs to self-describe its expected mountpoint, environment modifications, and any required helper mounts.
A rootfs must specify it's destination in the params json, but a toolchain squashfs can place the expected mountpoint with itself at `.wakebox/mountpoint`
To modify environment variables, a sh-compatible file `.wakebox/environment` will be sourced.
If a rootfs requires additional helper mounts, `.wakebox/mounts` will contain json-formatted mount-ops (tmpfs & bind only for now).
Example wakebox input params json:
```
{
"command": ["bash"],
"user-id": 0,
"group-id": 0,
"mount-ops": [
{ "type": "squashfs", "source": "centos8.squashfs", "destination": "/"},
{ "type": "squashfs", "source": "gcc.squashfs"},
{ "type": "workspace", "destination": "/workspace"}
]
}
```
The …
=> wakebox: Metadata from within squashfs

.github/workflows/build.yaml, fuse/fuse.cpp, fuse/fuse.h
This starts the separating-out of the fuse daemon logic. 
This PR shouldn't result in a behavior change
-------------------------------------
Longer term:
In pseudocode, our current flow looks like
```
contact_fuse_daemon()
for mount_ops:
if op == workspace
bind_workspace_mount()
else
do_other_mount_op()
collect_results()
```
I'd like to make the 'contact the fuse daemon' logic become part of the 'workspace' mount op
```
for mount_ops:
if op == workspace:
contact_fuse_daemon()
bind_workspace_mount()
else
do_other_mount_op()
if want_results:
collect_results()
```
In json our current flow the input json looks like:
```
{
"command": ["bash", "-c", "findmnt"],
"visible": ["a-file", "b-file"],
"mount-ops": [
{ "type": "workspace", "destination": "."}
]
}
```
but it could instead be:
```
{ …
```
=> fuse-wake: refactor daemon communication

gopt/gopt-errors.c, gopt/gopt.c, gopt/gopt.h
Our gopt implementation allows you to repeat an option, but it will only store the value associated with the option _once_.
This PR changes that to store the repeated option's values in an array.
The array is allocated outside of gopt and passed in to the option struct.
Code example:
```
int main(int argc, char *argv[])
{
unsigned int max_vals = argc / 2;
char* vals[max_vals];
struct option options[] {
{'v', "value", GOPT_ARGUMENT_REQUIRED | GOPT_REPEATABLE_VALUE, vals, max_vals},
{0,   0,       GOPT_LAST }
};
argc = gopt(argv, options);
gopt_errors("test-cli", options);
for (unsigned int i = 0; i < arg(options, "value")->count; i++)
std::cout << "repeated value: " << vals[i] << std::endl;
```
It handles short, short without space, and long version of the argument
```
./cli-tester -v …
```
=> gopt: allow repeated options that have a value

fuse/fuse.cpp
A recent change caused the full path to the executable to be not found when these are true:
* the job asks to be run within a subdir of the workspace
* the PATH contains relative locations
* the executable is contained in one of the relative PATH locations
This PR restores the previous behaviour where we would `chdir` into the subdirectory and only then search the PATH for the executable.
=> fuse.cpp: change dir before finding executable in PATH

fuse/daemon.cpp
libfuse will sometimes create files prefixed with `.fuse_hidden` (for example: `somedir/.fuse_hidden000002d500000001`)
```
/**
* The default behavior is that if an open file is deleted,
* the file is renamed to a hidden file (.fuse_hiddenXXX), and
* only removed when the file is finally released.  This
* relieves the filesystem implementation of having to deal
* with this problem. This option disables the hiding
* behavior, and files are removed immediately in an unlink
* operation (or in a rename operation which overwrites an
* existing file).
*
* It is recommended that you not use the hard_remove
* option. When hard_remove is set, the following libc
* functions fail on unlinked files (returning errno of
* ENOENT): read(2), write(2), fsync(2), close(2), f*xattr(2),
* ftruncate(2), …
```
=> fuse daemon: don't report .fuse_hidden prefixed files as outputs

build.wake, fuse/client.cpp, fuse/fuse.cpp, fuse/fuse.h, fuse/namespace.cpp, fuse/namespace.h, wakebox/main.cpp
This replaces most of `wakebox.cpp` to provide a second mode of option from the CLI.
There is scope for more CLI work, but this is likely sufficient for use in the medium term
There is now
* batch mode, for use with json params files
* interactive mode, for adhoc cli usage
There are also some refactors
* wakebox only builds on linux
* the working directory of the eventual command to execute is now set in main.cpp/client.cpp, not in namespace.cpp
* the #ifdef linux section in fuse.cpp is much smaller
=> wakebox: cli interactive mode options

share/wake/lib/system/job.wake
Allows a user to implement a base runner in their own codebase outside of the `wake` package
=> Export tuples: RunnerInput, RunnerOutput, Usage

fuse/namespace.cpp
Provides a little more freedom creating directory structure
=> wakebox: Allow create-dir in helper mounts

fuse/fuse.h, wakebox/main.cpp
Value wasn't initialized, matches non-interactive default for now until we provide explicit knobs
=> wakebox: enable network by default on interactive mode

share/wake/lib/system/incremental.wake
This makes claimFileAsPathIn work when:
- invoked multiple times
- used to claim a file from another file system
=> claimFileInPath: improve for use as an 'input file' processing API

share/wake/lib/system/job.wake, src/describe.cpp
Helps with identifying Jobs when looking at params files, or in `wake --failed -v`
=> fuse-wake: add label to json params file and in wake --failed

src/string.cpp
Found this bug while writing documentation.
=> integerToByte: should return "\x00" when run on 0

src/integer.cpp
wake -x 'strbase 0 15'
zsh: floating point exception  ./bin/wake -x 'strbase 0 15'
The primitive now returns "".
A follow-up PR will change the type of strbase.
=> strbase: don't explode wake on bases < 0

src/parser.cpp
Previously, `def f x = x+42` would have type `(x: Integer) => Integer`.
With the new type patterns `def f (x: Integer): Integer = x+42`, it was becoming `Integer => Integer`.
This happens because the type ascription caused the code to be rewritten as:
```
def f '_ x' =
def x = '_ x': Integer
(x+42): Integer
```
... and the name `_x` is rejected as a nametag since it starts with `_`.
Instead, just discard the result of the type ascription construct:
```
def f x =
def '_type x' = x: Integer
(x+42): Integer
```
=> parser: don't lose tags on typed function arguments

src/bind.cpp, src/parser.cpp, tests/type-system/lambda-fail/stderr, tests/type-system/lambda-fail/test.wake, tests/type-system/lambda-pass/test.wake, tests/type-system/multi-match-fail/fail.sh, tests/type-system/multi-match-fail/stderr, tests/type-system/multi-match-fail/test.wake, tests/type-system/multi-match-pass/pass.sh, tests/type-system/multi-match-pass/test.wake
This fixes two bugs:
- output type signatures on functions with a pattern argument were ignored
- multi-argument patterns (or functions with multiple pattern arguments) ignored their first-level types
=> types: fix multi-arg pattern types and functions with pattern extractors

share/wake/lib/system/job.wake
This is useful for debugging, as `wake --failed -v` doesn't show the full environment
=> Allow fuse-wake input/output json files to be kept

fuse/daemon.cpp, fuse/daemon_client.cpp, share/wake/lib/system/job.wake
Often we need to diagnose a released version of wake.
This let's us easily inject some trace information.
DEBUG_FUSE_WAKE=1 wake ...
Fixes #594
=> fuse: allow an environment variable to enable debug/trace

.gitignore, build.wake, common/unlink.cpp, fuse/daemon.cpp, share/wake/lib/system/job.wake, shim/shim.c, src/string.cpp, tests/runtime/symlinks/pass.sh, tests/runtime/symlinks/test.wake, tests/tests.wake
It turns out there were three distinct bugs with symlinks:
- wake's unlink wrapper could not remove them (this led to problems where jobs meant to overwrite a symlink, but instead created the link destination instead)
- the wake shim would hash the contents of the destination instead of the link (Fixes #560)
- the wake 'write' command would not follow a symlink to create the target instead
This PR fixes all of the above issues. It also:
- adds a unit test which fails if any of these three bugs are present
- adds a `getPathHash` method for introspecting hash codes
- fixes a recursive-fuse-bug in the unit testing framework on os/x
=> Fix handling of symbolic links

share/wake/lib/core/print.wake, src/gc.cpp, src/job.cpp, src/job.h, src/main.cpp, src/status.cpp, src/status.h
The report stream (magenta) is now used for println and profile-heap.
These should be output even without verbose mode.
The logInfo stream is now dim.  This makes echoed commands stick out when
compared to the intermingled standard output.
Fixes #592.
=> streams: add report stream and intensity control

share/doc/wake/tutorial.md, share/wake/lib/system/sources.wake
Pretty self-explanatory. Many a user has had a hell of a time after moving a source file without doing a `git mv`.
I also grepped for the error message and updated it in the tutorial which uses a different error message now.
=> Add suggestion to error message when source file doesn't exist

.circleci/config.yml, .circleci/dockerfiles/wasm, build.wake, common/rusage.cpp, common/whereami.cpp, fuse/fuse.cpp, lsp/emscripten.wake, preload/wrap.cpp, share/wake/lib/gcc_wake/gcc.wake, src/gc.h, src/regexp.cpp
Adds support for compiling wake as a web assembly target.
This will be useful to produce a platform-agnostic image suitable for use in the vscode extension.
=> Emscripten

fuse/daemon.cpp, fuse/daemon_client.cpp
This PR makes it far harder for the client to miss a connection to the daemon and also enables a debug facility which can be enabled to diagnose the cause.
=> FUSE daemon resilience

fuse/daemon.cpp
We want to wait a while before the daemon tries to quit the first time.
Once we start trying to exit, though, we need to get the job done!
=> fuse: daemon exit policy should differentiate between linger + retry

fuse/daemon.cpp
A build was seen to fail with this in the .fuse.log:
```
Too many umount attempts; unable to exit cleanly. Leaving a broken mount point behind.
Unable to umount on attempt 1
Unable to umount on attempt 2
Unable to umount on attempt 3
Unable to umount on attempt 4
Unable to umount on attempt 5
Unable to umount on attempt 6
Unable to umount on attempt 1
Unable to umount on attempt 2
Unable to umount on attempt 3
Unable to umount on attempt 4
Unable to umount on attempt 5
Unable to umount on attempt 6
Unable to umount on attempt 7
Unable to umount on attempt 8
Too many umount attempts; unable to exit cleanly. Leaving a broken mount point behind.
```
Presumably, the daemon tried to exit with something still live in the filesystem. Eventually, that process quit before the timeout fired the …
=> FUSE: do not exit daemon while files/dirs are open

src/cli/status.cpp
This PR removes the huge number of `[#         ] '<hash>' foo/baa/abc` messages when building interactively, 
simply filtering them all out <ins>unconditionally</ins>, but only at the display layer.
This applies to all messages that start with `'<`, such as `'<hash>'` and `'<mkdir>'`
Files that fail to hash still produce an error message as before:
```
$ cat do.wake
global def do _ =
"echo hello"
| makePlan "" Nil
| setPlanFnOutputs (\_ "/foo", Nil)
| runJob
```
```
$ wake do
shim hash open(/foo): No such file or directory
Job 150067
```
```
$ wake --failed -v
Job 150068:
Command-line: '<hash>' /foo
Environment:
Directory: .
Built:     2021-07-22 00:44:25
Runtime:   0.001472
CPUtime:   9.9e-05
Mem bytes: 0
In  bytes: 0
Out bytes: 0
Status:    1
Stdin:     /dev/null
Visible:
Inputs: …
```
=> silence '<hash>' messages

.circleci/config.yml, lsp/lsp.wake, src/src.wake, src/wake.wake
Create src.wake.
Rewrite lsp.wake and wake.wake to use this library.
Disable the vscode build in circleci as it stopped building successfully.
=> src: separate into a library

extensions/vscode/lsp-client/src/extension.ts, lsp/lsp.cpp
Restructure lsp.cpp. Rewrite it to define the reporter object and use it for sending diagnostics to the client.
Revert extension.ts back to using the default build of the server.
=> lsp: enable squiggly lines

bsp/bsp.wake, common/common.wake, fuse/fuse.wake, gopt/gopt.wake, lsp/lsp.wake, preload/preload.wake, shim/shim.wake, src/runtime.wake, src/wake.wake, utf8proc/utf8proc.wake, wakebox/build.wake
It's just too messy to have these differ by target.
=> build: have variant ALWAYS mean both C and C++

lsp/lsp.cpp, src/cli/main.cpp, src/frontend/parser.cpp, src/types/bind.cpp, src/types/bind.h
On mouse hover the name and type of a symbol is provided.
By pressing Ctrl+Shift+P you can go to the command palette and from there:
- By starting with @ search for symbol definitions in the open document.
- By starting with # search for symbol definitions in the project folder.
By pressing F2 you can rename a symbol.
Additionally, features are being provided even if there are type errors.
=> lsp: add hover, search definitions by name, rename

tools/lsp-wake/lsp.cpp
This file gets enormous.
We're also past the point it's useful.
@elena-pudovkina Or are you still using it?
=> LSP: remove the log file for every request

Makefile
Cuts compilation time by 33%.
This will likely make 'make' even less reliable, but whatever.
It's just there to bootstrap the build.
=> make: don't rebuild when wake touches parser.h

src/util/location.h, tools/lsp-wake/lsp.cpp
Now on hover not only the name and type of the symbol are provided, but also its documentation if it exists.
=> lsp: add documentation on hover

src/parser/syntax.cpp, src/parser/wakefiles.cpp, src/util/file.cpp, src/util/file.h, tools/lsp-wake/lsp.cpp, vendor/emscripten.wake, vendor/whereami/whereami.c
Using asyncify makes it possible to read from stdin with a 1s timeout using native nodejs.
This PR also switches us from noderawfs to nodefs, which has less issues with readdir/etc.
=> Switch emscripten LSP to using asyncify

extensions/vscode/package.json, src/dst/todst.cpp, src/parser/wakefiles.cpp, tools/lsp-wake/lsp.cpp
Whenever a file is potentially changed, we record we're out-of-date.
Whenever a query arrives, if we are out-of-date, we update.
If no new requests arrive for 1 second, we update.
This should improve the perceived performance.
=> LSP: defer reparsing of the project until 1s of no typing

share/wake/lib/core/boolean.wake
Most programming languages realize that a True value left of an OR can satisfy the equation and False for AND, but the docs had them switched.  I also fixed a typo on the same line.
=> core: update the docs to use the proper often-short-circuit values

share/wake/lib/core/tuple.wake
By re-exporting Pair as → rather than defining it, we can use → also in patterns.
=> tuple: improve arrow operator

src/dst/bind.cpp
If the body had an error, don't deference it.
Fixes #705.
=> bind: don't dereference a null ascription pointer

share/wake/lib/core/vector.wake
The calls to 'vnew' in several places did NOT bind to the correct
pre-existing type variable.  This left more type freedom than is sound.
=> vector: vunfoldl creates any type!

tools/lsp-wake/astree.cpp, tools/lsp-wake/astree.h
When a file has no diagnostics, report an empty diagnostics array to indicate that there are no errors.
=> lsp: don't discard empty diagnostics

tools/lsp-wake/astree.cpp
Now all comment content after the two last subsequent newline characters is discarded.
=> lsp: fix sanitize comment

build.wake, extensions/vscode/vscode.wake, share/wake/lib/core/boolean.wake, share/wake/lib/core/double.wake, share/wake/lib/core/integer.wake, share/wake/lib/core/json.wake, share/wake/lib/core/list.wake, share/wake/lib/core/tree.wake, share/wake/lib/core/vector.wake, share/wake/lib/system/job.wake, share/wake/lib/versions/v0_19.wake, tests/tests.wake
I've been reading through the Wake code and making sure I stay attentive by adding type annotations.  This is unfortunately a rather large PR, but it should hopefully be relatively straight-forward to review (I extracted the harder-to-glance-at patches to be sent later).  Let me know if you'd prefer smaller chunks, in which case I'll probably just break this up by file.
=> core: add basic type annotations to exported symbols

extensions/vscode/README.md, src/compat/aligned_alloc.c, src/compat/readable.c, src/compat/readable.h, src/compat/windows.c, src/compat/windows.h, src/parser/wakefiles.cpp, src/parser/wakefiles.h, src/runtime/gc.h, src/runtime/sources.cpp, src/util/file.cpp, tools/lsp-wake/astree.cpp, tools/lsp-wake/astree.h, tools/lsp-wake/json_converter.cpp, tools/lsp-wake/json_converter.h, tools/lsp-wake/lsp.cpp, tools/wake/main.cpp, vendor/emscripten.wake, vendor/whereami/whereami.c
This PR revamps how the LSP tracks files. It now tracks them using absolute paths. The URI is also now %-decoded/encoded properly. This makes it possible to reference to/from files in the standard library, which do not lie under the workspace. As the LSP also no longer uses relative paths, it's working directory is irrelevant to its operation, which should alleviate the neovim headaches. Finally, using absolute paths makes it relatively easy to support windows, where the standard library and the workspace might be on different volumes.
In other words, this PR:
- Fixes 'neovim must be invoked from workspace root'
- Fixes 'find references' from the standard library
- Fixes handling of filenames with non-alphanumeric characters
- Adds support for Windows
=> LSP: support windows and following references from standard libraries

tools/lsp-wake/lsp.cpp
If a user hits 'undo' on a symbol rename, you can get hundreds of sequential didClose invocations.
Calling refresh for each would cause the extension to 'hang' for a very long time.
=> LSP: don't require immediate refresh for modified-file-closed

extensions/vscode/vscode.wake
This makes it less likely someone will accidentally modify the standard
library included with the extension in ~/.vscode/extensions/
=> extensions/vscode: make the standard library install read-only

tools/lsp-wake/astree.cpp
If a wakefile has no package, the package name is taken as the file name.
The package name is appended after an '@' to top-level symbol names.
Therefore, when rejecting symbol names with spaces, allow spaces AFTER an @.
=> LSP: fix wakefiles with names including a ' '

tools/wake/main.cpp
This is useful, because wake is in the PATH while lsp-wake is not.
=> wake: add an '--lsp' option to start the LSP service

tools/lsp-wake/astree.cpp
Bug was found by the native LSP with neovim.
=> LSP: do not crash on an incomplete AST

src/parser/wakefiles.cpp
Neovim can find the standard library both as rooted at 'lib/' and relative to lsp-wake. This causes it to consider these symbols duplicated.
Solution: just eliminate the duplicates in the file list.
=> Fix duplicated stdlib in neovim

src/dst/todst.cpp
Consider this buggy code:
```
def x: Integer = y
def y: Integer = x
```
Now wake reports:
```
build.wake:159:[18-19]: definition of 'y@build_wake' references 'x@build_wake' forming an illegal cyclic value
build.wake:158:18: definition of 'x@build_wake' references 'y@build_wake' forming an illegal cyclic value
```
Instead of:
```
src/dst/todst.cpp:822:1: definition of 'y@build_wake' references 'x@build_wake' forming an illegal cyclic value
src/dst/todst.cpp:822:1: definition of 'x@build_wake' references 'y@build_wake' forming an illegal cyclic value
```
Fixes #721.
=> todst: fix the location for typed cyclic values

src/dst/bind.cpp
Now `def _foo: Foo = 21 + "asd"` will still tell you about bad addition
after it tells you that 'Foo' is undefined.
=> bind: check the body of an expression with a bad type signature

src/dst/bind.cpp, tools/lsp-wake/astree.cpp
Previously, if wake encountered `def x = x`,  it would give an error and stop further analysis.
In light of #721, it would be helpful to continue analysis of other definitions.
To that end, this PR clears out only the offending cyclic expressions and attempts to continue.
This is introduces nullptr in places it was previously impossible, potentially leading to new segfaults.
Nevertheless, it should be possible to shake-out those issues and end up with a more robust experience.
=> Type check past cycles

share/wake/lib/core/list.wake, share/wake/lib/core/syntax.wake
Notice in the PR how I also added a name for the inner function argument and it then made it into the type signature shown in the tool-tip, matching the documentation.
=> map: include an example of how to format comments

share/wake/lib/system/job.wake
Adding this as I don't think we have a one liner to do `Job => Result (List Path) Error`
Regardless of future api changes to Plan/Job, we should have something like this for now so we're not asking people to do something like this on each job:
```
job
| getJobOutputs
| map getPathResult
| findFail
```
=> getJobResult

src/runtime/database.cpp, src/runtime/database.h, src/runtime/status.cpp, src/runtime/status.h, tools/wake/main.cpp, vendor/lemon/lemon.wake
When wake is run interactively, show the message
```
Database wake.db is busy; waiting ...
```
Otherwise, just wait quietly until the lock is obtained.
This PR also incidentally fixes a bug whereby is_tty detection was not impacting job output batching.
=> Show DB retry attempts only on a terminal

tools/fuse-waked/fuse-waked.cpp
The fuse_loop calls blocking read.
If the arrival of SIGALRM never interrupts this read, the daemon never exits cleanly.
=> Don't restart IO operations after exit is scheduled

src/dst/bind.cpp
Fixes #739.
This program:
```
def _ =
match a.b a.c
(Pass _) (Pass _) = ""
_                 = Unit
```
Now produces:
```
demo.wake:4:13: multi-argument match requires a multi-argument pattern
demo.wake:2:[11-13]: non-exhaustive match; missing:  (Pass _) (Fail _)
>>> Aborting without execution <<<
```
Instead of just:
```
>>> Aborting without execution <<<
```
=> match: report an error for multiarg match with singleton pattern

tools/fuse-waked/fuse-waked.cpp
For whatever reason, fuse_unmount after a fork doesn't work anymore.
However, on OSX we can just call good old unmount().
=> fuse-waked: fix unmounting on macfuse-4

src/dst/bind.cpp, src/dst/expr.h, src/dst/todst.cpp
Fixes #752.
When reporting an error for
```
from nonexistent import _
```
now report the location of the import instead of the whole file.
=> wake: report location of bad import all

vendor/lemon/lemon.wake, vendor/re2c.wake
For systems without re2c and for the pre-wake bootstrap, we need
copies of the generated parser/lexer files.  When the actual
origin of these files change, the generated code is committed to git.
However, gzip on different systems produces different output.
Therefore, to prevent dirty trees and ping-pong'ing the contents,
only recreate the generated files if UPGRADE_GENERATED=1.
=> wake: don't replace bootstrap gz files by default

src/runtime/job.cpp
This should not actually matter.
=> job: fix a warning on newer linux

src/wakefs/fuse.cpp
If wakebox happens to be invoked on a different host from the local machine, for debugging it could be useful to know which host that was
=> Add hostname to fuse output json

extensions/vscode/vscode.wake
This is necessary because node in the emsdk image is too old.
=> vscode: peg vsce at older version

src/runtime/job.cpp, src/runtime/poll.cpp, src/runtime/poll.h, src/runtime/status.cpp, tools/bsp-wake/bsp.cpp, tools/lsp-wake/lsp.cpp, tools/shim-wake/shim.c
This PR reworks how wake manages file descriptor monitoring:
- We can use > 1024 file descriptors (up to the hard ulimit)
- This means we can have a lot more child processes
- On linux, we now use epoll() to avoid scaling issues with many children
- We regularize / sanitize the soft descriptor limit for our children
Fixes #776.
=> wake: switch from select() to poll() wherever possible

src/runtime/database.cpp, src/runtime/database.h, tools/wake/describe.cpp
Even if a previous job's inputs have changed (and thus the outputs
are stale), users may still wish to inspect which job produced the
file.
This PR helps wake remember jobs for all output files, by not erasing
a stale job the moment it is out-of-date.
Now, you will see something like this:
```
Job 1086 (compile c++ src/runtime/job.native-cpp11-release.o):
Command-line: /usr/bin/c++ -std=c++11 -Wall -O2 -Isrc -Ivendor -std=c++11 -pthread -c src/runtime/job.cpp -frandom-seed=src/runtime/job.native-cpp11-release.o -o src/runtime/job.native-cpp11-release.o
Environment:
PATH=/usr/bin:/bin
Directory: .
Built:     2021-11-09 01:06:50
Runtime:   1.91766
CPUtime:   1.89431
Mem bytes: 169934848
In  bytes: 246256
Out bytes: 184790
Status:    0
Stdin:     /dev/null
Inputs:
<out-of-date> …
```
=> wake.db: keep a record for jobs with stale inputs

src/runtime/database.cpp, src/runtime/database.h, src/runtime/job.cpp, src/runtime/status.cpp, src/runtime/status.h, tools/wake/describe.cpp
This required upgrading a lot of types to use timespec (with ns).
Fixes #794
=> wake: record start+stop times for jobs in ns

src/dst/todst.cpp
This code is fine:
```
def ok _ =
def Unit = println "Hello"
4
```
This code is not fine:
```
def bad _ =
def Unit = 44
4
```
This code is also not fine:
```
def bad _ =
def None = Some 10
4
```
Previously, both of the bad examples were accepted by wake.
=> todst: check unused pattern expansions

src/runtime/sources.cpp, src/runtime/sources.h, tools/lsp-wake/lsp.cpp, tools/wake/main.cpp
If you run an older wake on a newer repository, you often get spurious errors from the wake files.
This is confusing to users.
In order to report a more useful error message, allow the `.wakeroot` file to include a version number on the first line of the file. This is then compared against the wake version, potentially resulting in an error message like:
```
.wakeroot: minor version is not a number (0.a23.9)
.wakeroot: excess text after the patch version number (0.23.9.k)
.wakeroot: minor version not followed by a '.' (0.23-9)
.wakeroot: repository requires wake v1.x.y, but this is wake v0.24.0-alpha-75-gdd46370-dirty
.wakeroot: repository requires wake >= v0.200.3, but this is wake v0.24.0-alpha-75-gdd46370-dirty
```
A repository version `x.y.z` is compatible with a wake version `a.b.c` …
=> Check version in .wakeroot before parsing a repository

share/wake/lib/system/environment.wake
If the value of an environment variable includes an `=` it gets cut.
ie: `getEnvironment "a" ("a=b=c", Nil) == "c"` (should be: "b=c")
=> {get,edit}Environment: fix value extraction

tools/wake/main.cpp
This is a developer facing option. If it segfaults, no big deal.
Being able to inspect the partially typed IR is useful in debug.
=> wake: Serve --stop-after-type-check also on typing failure

src/dst/todst.cpp, src/optimizer/purity.cpp, src/runtime/prim.cpp, src/runtime/runtime.cpp, src/runtime/runtime.h, src/runtime/target.cpp, src/types/internal.cpp, tools/wake/main.cpp
Rework how target subkeys are treated in wake. By definition, these keys are not supposed to matter. So, if they are used inconsistently, this should not trigger an error, just a warning. Furthermore, the old error messages were exceedingly unhelpful.
Consider this bad program:
```
export def broken _ =
require Pass job1 =
"ls"
| makePlan "job1" Nil
| setPlanStdout logError
| runJob
| getJobStdout
require Pass job2 =
"ls"
| makePlan "job2" Nil
| setPlanStdout logWarning
| runJob
| getJobStdout
Pass "{job1}{job2}"
```
The old ERROR message:
```
ERROR: Target subkey mismatch for share/wake/lib/system/job.wake:273:[8-32]
To debug, rerun your wake command with these additional options:
--debug-target=945013996097089732 to see the unique target arguments (before the '\') …
```
=> Subhash as useful warning

src/runtime/target.cpp
This warning was printed on recent ubuntu:
```
src/runtime/target.cpp: In instantiation of 'T Target::recurse(T) [with T = PadObject*; T (HeapPointerBase::* memberfn)(T) = &HeapPointerBase::moveto]':
src/runtime/gc.h:356:10:   required from 'Placement GCObject<T, B>::descend(PadObject*) [with T = Target; B = DestroyableObject]'
src/runtime/gc.h:355:11:   required from here
src/runtime/target.cpp:79:24: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
arg = (x.*memberfn)(arg);
~~~~~~~~~~~~~^~~~~
```
I'm baffled why it couldn't lower from HeapPointer<String>& to
HeapPointerBase& on it's own, since it will do it for values.
=> target: fix a pointer cast warning on newer g++

src/dst/bind.cpp
Without the '&', auto causes us to copy the map on every lookup!
This leads to a high-constant quadratic time algorithm. Oops.
=> bind: fix a bug wasting nearly 1s on wake start-up

src/dst/bind.cpp, src/dst/expr.h, tools/lsp-wake/astree.cpp
Adds support for goto-definition and hover for destructors in patterns.
=> dst: include the uses of destructors in patterns

share/wake/lib/core/types.wake, src/dst/bind.cpp, src/dst/expr.h
This is helpful for nice popup text.
=> types: add documentation for the builtin wake types

src/dst/todst.cpp
These constructions incorrectly conflated token and region.
Fixes #823.
=> bind: fix extractor destructor token

src/dst/bind.cpp, src/dst/expr.h, src/dst/todst.cpp, tools/lsp-wake/astree.cpp
Fix some type hover bugs discovered by @elena-pudovkina 
```
data Foo = Bar
```
Mouse-over of `Foo` should still show the comment, even before
`Foo` is used in a type signature.
```
from wake import type Hax=List
def foo (x: Hax Integer) = sum2 (x: List Integer)
```
In the LSP, Hax and List should be the same.
```
data Foo = Bar
from my_pkg export type Foo
```
The definition of `Foo` should be bound to the `data`, not the export.
=> LSP: fix type hover corner cases

src/util/location.h, tools/lsp-wake/astree.cpp, tools/lsp-wake/astree.h, tools/lsp-wake/json_converter.cpp, tools/lsp-wake/symbol_definition.h
Outer comments are now also bound to symbols introduced in a `tuple` or `data` definition. They appear after the inner comment:
Definitions which have the same location are now merged into a single definition with the documentation containing:
- Name and type of the symbol
- Inner documentation of the symbol
- List of definitions introduced at this location
- Outer documentation
Fixes #820.
=> LSP: fix documentation hover for `tuple` and `data`

.circleci/config.yml, .circleci/dockerfiles/debian-bullseye, scripts/fetch
Bullseye was recently released and debian/testing currently has major breaking changes in how apt works. Let's avoid that for now.
=> CI: switch from debian testing to bullseye

.circleci/config.yml, .circleci/dockerfiles/rocky-8, .github/workflows/build.yaml
Both centos8 and rocky8 are RHEL8 clones.
Centos8 discontinued support and broke their mirror urls..
Use rocky8 instead, as that will be supported for some time (and using actual RHEL8 requires licences which isnt helpful).
Fixes https://github.com/sifive/wake/issues/852
=> CI: use rocky linux 8 instead of centos 8

scripts/fetch
The fetch script for releases also needs to know about the `s/centos_8_3/rocky_8/`
=> release fetch: use rocky8

share/wake/lib/system/sources.wake, src/runtime/database.cpp
This change adds add_claim to the standard library where we have access to things like raw_sources. If we're happy with this I'll also use this as an excuse to do a minor release so I can learn that process.
The specific semantics I chose are to restrict `claim` to operating within wakeroot to limit its effectiveness. I couldn't think of a way to prevent people from using it instead of `source` but added that `source` is preferred in the documentation.
=> Added claim function for using edited files

tools/fuse-waked/fuse-waked.cpp
When using the fuse daemon, running `ls -laR` in the root of the workspace we would see
```
.:
total 8
-rw-rw-r--. 1 root root   19 Feb 14 18:57 bar.sv
drwxrwxr-x. 2 root root 4096 Feb 14 19:00 foo
./foo:
total 4
-rw-rw-r--. 1 root root 26 Feb 14 18:27 beef.sv
```
instead of the expected
```
.:
total 16
drwxrwxrwx.  1 root   root   4096 Feb 15 00:04 .
dr-xr-xr-x. 27 nobody nobody 4096 Feb  3 20:47 ..
-rw-rw-r--.  1 root   root     19 Feb 14 18:57 bar.sv
drwxrwxr-x.  2 root   root   4096 Feb 14 19:00 foo
./foo:
total 12
drwxrwxr-x. 2 root root 4096 Feb 14 19:00 .
drwxrwxrwx. 1 root root 4096 Feb 15 00:04 ..
-rw-rw-r--. 1 root root   26 Feb 14 18:27 beef.sv
```
If `dir1` is visible `dir1/.` should be visible.
If `dir1/dir2` is visible, `dir1/dir2/..` should be visible, and so should `dir1`. …
=> Allow visibility of . and .. in directory listings

.circleci/config.yml
Context: https://circleci.com/blog/ubuntu-14-16-image-deprecation/
Ubuntu 16.04 image types to disappear
```
The first brownouts of the affected images will take place on March 29, 2022, followed by another 
round of brownouts on April 26, 2022. Any pipeline runs that depend on these images will fail during
the specified brownout periods. The 14.04 and 16.04 images will be permanently removed on 
May 31, 2022, and pipelines using the affected images will fail permanently until a newer image is specified.
```
All of our circle ci configs used a VM with a Ubuntu 16.04 filesystem.
We would then start a docker container with whatever OS filesystem we actually wanted to test.
Since 16.04 is going to be removed, this PR bumps us to 20.04.
With any luck, this shouldn't change how our tests run
=> circle-ci: newer base OS

.circleci/config.yml, .circleci/dockerfiles/debian-jessie, .circleci/dockerfiles/ubuntu-14.04, .circleci/dockerfiles/ubuntu-16.04
We've carried some older linux distributions in CI for a while, it may be time to remove them.
Debian Jessie ends extended LTS support in few months, and has already ended regular LTS.
Ubuntu 14.04 & 16.04 are also outside LTS, though it's possible to pay for extended support.
If desired, we could add some newer distros to CI in a separate PR
=> CI: remove older linux distros

.circleci/config.yml, .circleci/dockerfiles/ubuntu-22.04
Adds Ubuntu 22.04 as a supported build target in CI
Follows on from the removals of older distros in https://github.com/sifive/wake/pull/869
Ubuntu 22.04 isn't actually officially released yet, but this is pointing at the docker image _tag_ that will become the official image in a few weeks (April 23). It's unlikely that much would change between now and then that would impact us
=> CI: Ubuntu 22.04 LTS

src/dst/bind.cpp
This change alters the type checking error message revived for so called "guard" statements in wake's pattern matching. This would be anything after an `if` in a pattern. We also use guards to implement literal pattern matching so if you have something like 0 or "foo" in a pattern we wind up use a guard for that.
Currently we do not type check code before transforming it this way which means that the type checker can wind up type checking generated code. Wes had previously used the C++ source location for the source location of the generated code. Most of the time when this technique is used the code is known to be correct in form ahead of time. When it is not known to be correct in form ahead of time we should (and often already do) prefer to use the fragment from the code that we're …
=> Improve user error messages of guard statements

share/wake/lib/system/job.wake
The fuse-wake executable would default to not returning the exit code of the process as its own.
Wakebox does by default, but has a cli flag to use the other behavior.
When we removed the fuse-wake executable, it was missed to add the `-I` to isolate the return code so that wakelang runners would only observe the jobs return code via the output json
=> use isolate-retcode when running Jobs

.circleci/dockerfiles/alpine, .gitignore, build.wake, tools/job-cache/bloom.h, tools/job-cache/job-cache.cpp, tools/job-cache/job-cache.wake, tools/job-cache/logging.h, tools/job-cache/xoshiro256.h, wake.spec.in
This is the start of a tool that will be able to create, retrive, and manage
a cache of jobs. It's missing *many* features that will need to be added to
reach parity with the existing database. This PR only allows you to *add*
things to the database (but the files are copied in). Additionally some important
features like atomicity and allowing multiple job caches to interact at once
are missing but that can be fixed by adding WAL which we will need anyway. Still
this represents a good base that appears like its going to work going forward.
=> [job-cache] Add tool for creating a job cache

tools/bsp-wake/bsp.wake, tools/fuse-waked/fuse-waked.wake, tools/job-cache/job-cache.cpp, tools/job-cache/job-cache.wake, tools/job-cache/logging.h, tools/job-cache/schema.sql, tools/job-cache/unique_fd.h, tools/job-cache/xoshiro256.h, tools/lsp-wake/lsp.wake, tools/shim-wake/shim.wake, tools/tools.wake, tools/wake-unit/wake-unit.wake, tools/wake/wake.wake, tools/wakebox/wakebox.wake
This change is really just a big refactor of the job-cache. It aims to make all "clean up" use RAII and it aims to strike a middle ground between full ORM and the kind of raw sqlite we were doing before. Additionally the base schema is now located in its own file modulo some hackery but sql syntax highlighting works so I'll call it good. I don't want job-cache to have to depend on some external file so we have to find a way to embed the string and this does that with only a few lines of hacks.
=> [NFC][job-cache] Job cache clean up

vendor/re2c.wake
`re2c.wake` wasn't reading the env path so it was always returning the system `re2c`. This PR fixes that issue.
Also supersedes https://github.com/sifive/wake/pull/915 with a more detailed error message.
Ex:
```
[WARN] Requested re2c which is unsatisfiable. Using fake
why: re2c version 0.14 is not 1.3 or higher
```
=> Update re2c to use environment PATH

src/wcl/optional.h, tests/tests.wake, tests/wake-unit/stdout, tools/wake-unit/optional.cpp, tools/wake-unit/unit.cpp, tools/wake-unit/unit.h
This change just adds an optional type that functions the same way as std::optional more or less.
It doesn't respect assignment quite the same way right now which means that wcl::optional<std::vector<T>>
isn't as efficen't as it could be since if you assign one vector to another that already has capacity,
the current implementation deallocates the first one and reallocates this one despite that not being
needed.
=> [wcl] Introduce the Wake Core Library

.gitignore
`wake.db-shm` and `wake.db-wal` shouldn't be tracked by git
=> .gitignore: wake.db-shm and wake.db-wal

src/wcl/xoshiro256.h, src/wcl/xoshiro_256.h, tools/job-cache/job-cache.cpp
Moves `Xoshiro256` to wcl. `Xoshiro256` is currently used to generate unique file names for `job-cache`. We also need to generate unique filenames for `wake-format` so it is being moved to wcl to make it generally available
=> Move Xoshiro256 to wcl

scripts/which_clang_files
This change will make the following pre-commit hook check for formatting before you commit. It accounts for some generated files and excludes them from formatting.
=> [clang-format] Prepare for optional formatting pre-commit hook

Makefile
1) `wake --version` prepended `v` for the bootstrap build while the main build didn't. This brings them in alignment with no `v`
2) Adds `-bootstrap` to the bootstrap build so that it explicitly calls out that its the bootstrap build and not the main one
=> Remove v and add '-bootstrap' to bootstrap build

tests/command-line/qv/fail.sh, tests/dst/colon/fail.sh, tests/dst/packages/fail.sh, tests/dst/typedef/fail.sh, tests/parser/unicode/pass.sh, tests/runtime/symlinks/pass.sh, tests/standard-library/groupBy/pass.sh, tests/standard-library/json-normalize-merge/compat-identity/pass.sh, tests/standard-library/json-normalize-merge/compat-valid/pass.sh, tests/standard-library/json-normalize-merge/compat/pass.sh, tests/standard-library/json-normalize-merge/deduplicate/pass.sh, tests/standard-library/json-normalize-merge/mergeJSON/pass.sh, tests/standard-library/json-normalize-merge/overrideJSON/pass.sh, tests/tests.wake, tests/type-system/extract-fail/fail.sh, tests/type-system/extract-pass/pass.sh, tests/type-system/lambda-fail/fail.sh, tests/type-system/lambda-pass/pass.sh, tests/type-system/match-fail/fail.sh, tests/type-system/match-pass/pass.sh, tests/type-system/multi-match-fail/fail.sh, tests/type-system/multi-match-pass/pass.sh, tests/type-system/require-fail/fail.sh, tests/type-system/require-pass/pass.sh, tests/type-system/value-restriction/pass.sh
Instead of setting `$1` to `<something>/bin/wake` set it to `<something>/bin`.
This allows tests to execute any of the tools installed by wake.
Also updates all wake tests to point to bin/wake.
It is mainly needed to support wake-format tests but may be used for
other tools in the future.
=> test: Provide dir to bin/ instead of wake as $1

src/wcl/trie.h, tests/wake-unit/stdout, tools/wake-unit/trie.cpp
Trie's aren't just good at mapping sequences to values, they can also find the maximal prefix of a given sequence that's still mapped to a key. You can implement dictionary finding this way too. This change adds that functionality.
=> [wcl] Generalize wcl::trie to allow finding the maximal prefix

src/runtime/job.cpp
This gets wake working again on macOS Monterey / M1:
```
terpstra@watermelon wake % uname -a
Darwin watermelon.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
terpstra@watermelon wake % ./bin/wake build default
Pass "BUILD"
```
=> job: fix pointer lifetime bug

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h
Adds all the boilerplate code required to walk the CST. These changes are pulled out of of much larger set of changes for ease of review.
Formatting output is currently messed up but will be fixed in the follow up PR
=> wake-format: Add tree walk boilerplate code

share/wake/lib/core/map.wake, share/wake/lib/core/tree.wake
A homebrew `List (Pair k v)` may work for most cases, so long as the set of values remains small, but for general use the time complexity becomes undesirable; a `Tree (Pair k v)` would seem to solve some issues, but since the type's not specialized for comparison functions which only reference the left-hand key, lookup and some other manipulations wind up no better than the `List`. Instead, providing a `Map k v` wrapper with access to the `Tree` internals where necessary allows a full and optimal implementation of the data structure.  I would appreciate people double-checking my evaluation of the `Tree` interface via map.wake, to both be sure I've not re-implemented something which was already optimal time, and to be sure I'm not missing anywhere that can be improved by only caring about …
=> [core] add `Map` data structure

tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h
This add support for `ctx.width` and implements `def` and `block` using it. Seems like this may actually be the final API. _knocks on wood_
I still need to go back and delete `flat` and make the walk functions not return `optional` but I wanted to get this up first before another major refactor.
=> Implement ctx width, basic def & block

tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h
Now that `flat()` and `wcl::optional` are no longer part of the wake-format internal API, remove them
=> Refactor: remove flat() and wcl::optional from format API

tools/wake-format/emitter.cpp, tools/wake-format/emitter.h, tools/wake-format/formatter.h
This PR does two primary (dependent) things
- It deletes the functions `space` and `newline` and unused MACROs from emitter.cpp since they are now redundant
- replaces previous calls to `space` and `newline` with calls into the format DSL which required adding `walk_children`
- bonus: it slightly rewrites `walk_rhs` to make less calls when possible
- bonus 2: it slightly moves around where newlines are added so that `undo` is no longer used
=> Add walk children, remove extra functions

share/wake/lib/system/path.wake
Unix/C/Python/... basename implementations return the final directory when given a path ending in a slash; ours returned the empty string (`basename "foo/bar/"` -> `""`).  This seems like something we'd want to align with the common understanding of the command.
I've not added a backwards-compatibility wrapper since to me this feels more like a bug rather than like something people would have been relying on, but if y'all think it would be better to keep the empty-string behaviour for previous versioned packages, I can certainly add it back.
I also tried to come up with some single-call version based on `extract`, but the regex greedy-matching behaviour made that rather difficult.
=> path: ignore trailing slashes in basename

src/parser/cst.cpp, src/parser/cst.h, src/wcl/doc.h, src/wcl/hash.h, src/wcl/hash_combine.h, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h, tools/wake-format/formatter.h
Memoize subtrees during the formatting walk to minimize repeated work. This significantly improves the running time for the format walk.
Also does the following in support of the above.
- implements a `hash_combine` function in wcl to merge two hashable objects
- implements `hash` and `op==` for `CSTElement` and `ctx_t`, and `std::pair<CSTElement, ctx_t>` 
Two types of memo tables are maintained
- `context_free_memo` which is higher priority and stores `docs` for `nodes` that are independent from context. Such as TOKEN nodes and subtrees where formatting is disabled
- `__memo_map__` which is unique to each memoizeable function where `ctx_t` is considered and part of the key. It it maintained by the MEMO macros.
As a general policy/thing to look out for in code review: within a given …
=> Memoize formatting for sub trees

src/wcl/doc.h, tests/wake-unit/stdout, tools/wake-unit/doc.cpp
`wcl::doc` was incorrectly reporting width values when passed in unicode strings. As unicode is common place in wake code, we need to also support it here. This change does the thing.
=> Support unicode with in wcl::doc

src/dst/todst.cpp, src/parser/cst.cpp, src/parser/cst.h, tools/wake-format/emitter.cpp, tools/wake-format/formatter.h
Creates an explicit type for CSTElement Ids. This makes the documentation in `wake-format` more clear and serves as a safety net if we ever expand past 256 CST ids
I know I missed some. `lexer.h` and `lexer.re` has a lot of suspicious `uint8_t`s, but this is a start down the correct path.
=> Create explicit type for CSTElement ids

tools/wake-format/emitter.cpp, tools/wake-format/formatter.h
Adds `match` to the formatting API. Used as shown below
```
fmt().match(match()
.pred(TOKEN_ID, fmt())
.pred({TOKEN_ID, TOKEN_ID}, fmt())
.pred(some_predicate, fmt())
.fits(fmt())
.otherwise(fmt())
.format(..., ...)
```
- `pred` -> the `case` statement. if predicate returns true then fmt is used, if false the the next entry is considered
- `fits` -> fmt is used if it fits the size limit, otherwise the next entry is considered
- `otherwise` -> the `default` statement. fmt is always used and no other case is considered. Should be the last item in a match
if no statement is accepted then an assertion is thrown; therefore a `match` should always end in an `otherwise` unless it is known that a `pred` will always pass 
Cases are evaluated top down, the first to be accepted is the one that is …
=> Add `match` syntax to the formatter API

share/wake/lib/gcc_wake/pkgconfig.wake, share/wake/lib/system/path.wake, vendor/emscripten.wake, vendor/re2c.wake
The repeated code here has been bothering me for a bit, had a minute so I decided to knock it out.
There are a few places inside the wake build where we depend on a cli program present in the users path. Each of them thus far implemented the same helper function to get it. This change makes a function for them all to share
=> which: Add whichInEnvPath

tests/wake-format/basic/basic.wake, tests/wake-format/basic/pass.sh, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h, tools/wake-format/formatter.h, tools/wake-format/wake-format.cpp
Implements `# wake-format off` with the following semantics.
1) For a `# wake-format off` comment at top level, the next sibling node and all its children will be re-emitted exactly as they are. Including whitespace, indents, and newlines
2) For all other `# wake-format off` comments, the next sibling node and all its children will be emitted exactly as they are except that indentation will be overwritten to match the indentation for the rest of the containing block. Since wake is whitespace sensitive, this is required to maintain a semantically valid program.
=> Implement `# wake-format off`

src/util/shell.cpp, tests/wake-unit/stdout, tools/wake-unit/shell.cpp
Bug Fix: When calling `shell_escape()` over the components of a shell command and collecting it into a string [as done here](https://github.com/sifive/wake/blob/master/tools/wakebox/wakebox.cpp#L179-L186) an empty string gets re-emitted as an empty string effectively erasing it as an argument.
Ex: 
```
0: bash
1: -c
2: echo $#
3: test0
4: 
5: test1
6: test2
```
becomes `bash -c 'echo $#' test0 test1 test2` instead of the expected `bash -c 'echo $#' test0 '' test1 test2`
Fix this by always escaping empty string.
=> shell: always escape empty strings

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/formatter.h
Adds ctx.sub() inside of all calls to compose. Before this width wasn't being correctly tracked so the formatted wouldn't newline when the width was too high.
=> Fix width tracking in formatter

src/wcl/doc.h, src/wcl/doc_state.h, tools/wake-format/emitter.cpp, tools/wake-format/formatter.h, tools/wake-unit/doc.cpp
Splits doc_state into several monoids, enabling easier composition of other bits of data.
I started down the template path but it turned out to be quite combursome and prone so I'm hoping to put that off for now until it becomes more important.
max_width also isn't implemented, happy to throw it in but since we weren't using it I didn't put in the effort to pin it down
=> Extract doc_state into several monoids

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tests/wake-format/disallowed-input/disallowed-input.wake, tests/wake-format/disallowed-input/stdout, tools/wake-format/emitter.cpp, tools/wake-format/formatter.h
This pins down and solves the last major ws errors/issues we've been seeing. The following changes are made
1) newline() now  only emits a single NL
2) freshline() emits a single NL if the last line doesn't have one and brings the total whitespace up to the value required by the nest level
3) 'before bound' comments emit a freshline()
4) 'after bound' comments emit a newline()
=> impl freshline() and fix formatting

extensions/vscode/package.json.in
The previous 0.28.1 was missing an icon for the extension; due to the Marketplace's policy, we need a version bump to fix that.
=> Release 0.28.2

tools/lsp-wake/lsp.wake
Otherwise functions that wasm exports are not recognized as such
=> vscode: include cwrap function

tools/lsp-wake/lsp.wake
This should *hopefully* be the final fix for this version; emscripten updated out from under us on CircleCI and broke the extension.
=> Release 0.28.3

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h, tools/wake-format/formatter.h
Implements 'full choice' for binary op formatting. Explores six different formatting options and then chooses the one that best optimizes for formatting, character width, and height.
=> Wake format binop full choice

share/doc/wake/quickref.md
Hello! I was reading the Wake quick reference and saw just a couple of typos and thought I'd make a quick fix commit for them and added some other formatting things, hopefully improvements. :)
I'm not sure about the contribution process, so currently, this PR targets the `master` branch as the base branch. Not sure if it should target a particular version or other branch.
=> Small, primarily formatting, changes to the quick reference

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h, tools/wake-format/formatter.h
Binop separation was moved to a single function/source of truth. This enabled things like moving the `,` to be a suffix instead of a prefix and had the bonus benefit of cleaning up the combine_* functions significantly
=> Improve binop separation

tools/wake-format/emitter.cpp, tools/wake-format/formatter.h
walk_children doesn't compose well with `format()` since fully consuming the parent node only moves the pointer to the parent's sibling. Instead this changes the aspect to that of the children thus "walking all" from a starting (child) node. In this aspect, fully consuming the children results in the expected `node.empty() == true` and has the bonus effect of making the function more generic.
=> Replace walk_children with walk_all

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Formats the `data` subtree
Ex:
```
export data JValue =
JString  String
JInteger Integer
JDouble  Double
JBoolean Boolean
JNull
JObject  (List (Pair String JValue))
JArray   (List JValue)
```
=> Format data subtree

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Formats the `if` subtree. Short expressions are on a single line
```
def x = if true then 5 else 3
```
while expressions with NLs or expressions that don't fit are split across several 
```
def linkKind =
if verrrrrrrry loooooooooooog naaaaaaaaaaaame then
verrrrrrrrrrrrrrrrrrrrrrry
else
looooooooooooooooong
```
=> Format if subtree

share/doc/wake/quickref.md
I didn't want to do a total overhaul, since a lot of this is out of date, but I wanted to update a few examples that need the `-x` to work today and I wanted to add a few more notes on getting info about jobs.
=> quickref: Add some more useful tips about getting job info.

tools/wake-format/actions.h, tools/wake-format/common.h, tools/wake-format/emitter.cpp, tools/wake-format/formatter.h
It's useful to know exactly where and which CSTElement fails an assert. This add a macro that adds that debug info as part of the assert. If it proves to be too expensive in real usage then it can be `ifdef`d away for release builds
=> Add fmt_assert macro for detailed debugging

tools/wake-format/actions.h, tools/wake-format/formatter.h, tools/wake-format/predicates.h
In the formatting API there is this use case to say "use this formatter if it fits" otherwise use this other formatter. Since fitting can only be checked after actually running the formatter we previously ran the formatter on a copy, checked if it fit, then threw out the copy. 
This idea of asking a question about an already formatted bit of code before continuing to format actually comes up in other formatting cases and is a precursor to any kind of "full choice" formatting. 
This change makes the idea of "try to format something and make a decision on how to proceed based on the format" generic so that it can be used in any formatter. This genercism also simplifies our previous implementations of `fits_first` and `fits_all`
A common case is to format condidtionally on if something …
=> Make fmt_fits generic via try_else

tests/wake-format/basic/basic.wake, tests/wake-format/basic/small.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h
Formats a subtree that has multiple variables in the match pattern
Ex
```
def f0 = match _ _
(x: Integer) (True:  Boolean) = x+1
(x: Integer) (False: Boolean) = x+0
```
=> Format multi-match subtree

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Format the tuple subtree
Ex:
```
global export tuple Map k v =
Comparison: k => k => Order
Data: Tree (Pair k v)
```
=> Wake format tuple

tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
CST_DATA was emitting `<nl><space><space><space><space>` at the end of the node incorrectly. This PR fixes that
=> Remove extra whitespace after a data node

.circleci/dockerfiles/alpine, scripts/fetch, src/runtime/database.cpp, tests/runtime/symlinks/pass.sh, tools/fuse-waked/fuse-waked.cpp
When a symlink was included as part of a job's input or output files, wake had previously been hashing the *target* rather than the link itself; when the symlink was broken on-disc (e.g. referring to an absolute `/workspace` sandboxed path), this could cause the job to rerun unnecessarily as it saw the symlink as having been "deleted".  By using the flag-aware `faccessat` rather than the simpler `access`, we can instruct wake to just look at but not follow the link for the proper behaviour.  This is a similar but distinct bug to that solved by #1008.
This does break compatibility with some older versions of MacOS; current/recent versions do implement the required features.
=> wake: check the hash of a symlink itself, not of the target

src/wcl/trie.h
WSL unittest builds fail due to a missing header import. This doesn't seem to effect other targets, likily due to slightly different imports and definition locations for `size_t`
=> Fix missing include on WSL build

README.md
I forgot to update the README based on what we discovered in solving #1019; this properly lists the minimum version for bug-free execution.
=> readme: signpost the musl requirement for AT_SYMLINK_NOFOLLOW

tools/wake-format/wake-format.cpp
Check if we are able to open and read the file before attempting to parse it. This gives more informative errors when the input is bad
=> Check if file exists before parsing it

share/doc/wake/quickref.md, share/doc/wake/tutorial.md
The Wake quick reference had a couple of typos for the example given in the "Sources and `Path` objects" section. I updated the section with a little bit of elaboration and updated the example.
I tried being accurate for the details of `source` and `sources`, but please review for accuracy.
=> Update "Sources and `Path` objects" section in the quick reference

share/wake/lib/core/map.wake, share/wake/lib/core/tree.wake
It looks like `minsertWith` was updated at some point to include the key in the update `fn` function, but the examples were out of date. So I updated the examples. I went with `\_key \old \new old + new` as I couldn't figure out how to make it more concise with Wake's syntax. I did try `(\_key _+_)` but this didn't work as expected. For example:
```bash
$ wakex '(\_key _+_)'
(\_key _+_): Integer => Integer => (_key: a) => Integer
```
But as you can see, this is the wrong type signature. I do find this a bit non-intuitive, as I might have expected (or maybe I should say hoped for to make the examples cleaner) `(_key: a) => Integer => Integer => Integer`.
Also, when using this function, it wasn't clear to me which value in the update function `(fn: k => v => v => v)` was the old or existing …
=> Update `minsertWith` examples and label arguments in type signature

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Comments were forcing paren nodes to be multi-lined. This was changing the semantics of the `data` subtree and was also just wrong formatting. This PR fixes it so they are only multi-lined when appropriate.
=> emit flat paren node when NL from a comment

share/wake/lib/system/job.wake, vendor/lemon/lemon.wake
Debugging what went wrong with a Job sometimes/often requires looking it up in the database, and if another `wake` invocation has been run since the failed job, or if we're looking into a reported issue rather than one we've triggered ourselves, `wake --last`/`wake --failed` can sometimes be less than helpful.  Printing the job ID directly in the error message doesn't introduce much extra noise but makes any `wake --job` calls to zero in on the info much simpler to construct.
=> job: include lookup id in job error messages

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
non-comment "top level" newlines inside of a CST_BLOCK or CST_REQUIRE should be re-emitted as they represent spacing requested by the author. This implements that change.
=> re-emit author provided newlines inside of BLOCKs

tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Re-emits author provided newlines for everything except defs which should be followed by 2 newlines. When a comment is encountered it and all wsnl is skipped as that is managed by the comment subsystem.
=> Re-emit top level newlines to maintain author separation

tools/lsp-wake/lsp.cpp
The recent refactor to support the LSP in web based vscode transitioned to a 1:1 request-response model for LSP requests. This means that for some requests where there isn't a response `{}` is returned. Neovim emits an error and shutsdown the LSP when that happens.
In the short term, just skip `{}` messages, in the long term we need to rethink and rework the entry point into the LSP for the various platforms we support.
=> Fix error message when running lsp in neovim

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Fix small formatting errors for the following cases
- missing a whitespace before/after `=` in `def` and `tuple`
- missing a whitespace before/after `:` in topic
- comments before a "fits first" `match`
- lambda subtree
- The memo cleanup vector had a **bunch** of duplicate pointers, a set is sufficient and efficient
=> fix small issues formatting the internal repo

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tests/wake-format/disallowed-input/stdout, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h
Enacts the rules for newlining defs as discussed in chat.
Specially
- Same rules as current formatter (the first bikeshed PR) plus
- Top level = always newlines
- except no newlines for single top level literals/identifiers
=> enact def + = newline rules

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Only allow flat `if - then - else -` when  `-` is a "simple" thing. Right now that is defined as a literal or identifier but that can be refined over time.
=> only allow flat if for trivial ternaries

share/wake/lib/system/incremental.wake
Incremental jobs could leave the workspace in a broken state if the user aborted Wake partway through the tarball being generated, as the resulting (truncated) file would have an incompatible hash with the database version.  This makes that archival atomic to ensure only the complete artifacts are hashed..
=> system: make incremental artifact creation atomic

tests/command-line/clean/pass.sh, tools/wake/main.cpp
Fixes the following `wake --clean` bugs
- Can't use wake clean if something creates `.`
- Wake clean doesn't work on non-linux posix systems
=> Fix wake clean dir bugs

debian/changelog.in
Testing out a new release flow to help avoid things like the changelog falling out of date.
=> debian: bump for 0.29.1

extensions/vscode/vscode.wake
Per https://docs.npmjs.com/cli/v9/commands/npm-ci, use `npm ci` instead of `npm install`.
In the long term we may want a `make vscode-ci` and `make vscode-dev` but this unblocks CI for now and enables landing other important changes.
=> Use npm ci to build in CI per the docs

README.md
Following up on [this comment](https://github.com/sifive/wake/pull/1081#discussion_r1046151095) in a separate PR, I have formatted the dependencies in the README as a table for better readability. I originally formatted as three separate tables but then made a change to a single table. There's no way to merge cells in GitHub markdown, which is why I originally went with the former. But I think the latter (i.e., single table) better aligns all the dependencies.
=> Format dependencies as a table

.gitignore, scripts/compile_commands, scripts/compile_commands.py, share/wake/lib/gcc_wake/gcc.wake
This change adds a "simple-enough" means to create a compile_commands.json file for the wake repo. The process is as follows
```
rm -rf compile_commands # Make sure we remove old compile commands
EMIT_COMPILE_COMMANDS=1 make # It shouldn't matter if the build is clean, this also works with `wake build <variant>`
python3 ./scripts/compile_commands.py
```
...wait I just realized that that always works so I think I'm going to add a bash script too
=> Add ability to emit compile commands for wake code

vendor/git.wake
Landing the non `alpha` tag on `master` broke how versions were generating for non-release CI builds. This fixes it so that node/npm doesn't fail to build in those cases by inserting `safe` where `alpha` normally goes if it is missing
=> Make the version tag safe to use in node

src/wcl/defer.h
I think I'm going to modify this so that the function inside is a wcl::optional. This will give us the desired move semantics by default AND will allow default construction....still I'm trying think of how to modify this so that you don't have to use std::function<void()> and yet you can still declare it. Ideally I want to capture this pattern
```
wcl::defer opt_resource_defer;
ResourceType optional_resource;
if (my_condition_here) {
optional_resource = make_the_resource;
opt_resource_defer = wcl::make_defer([&]() {
clean_up_resource(optional_resource);
});
}
```
=> add wcl::defer

src/parser/wakefiles.cpp, src/parser/wakefiles.h, src/runtime/sources.cpp, src/wcl/defer.h, tools/lsp-wake/astree.cpp, tools/wake/main.cpp
I'm not sure that I'm happy with this implementation, but I don't know how else to do it.
The MacOS builder is running slow enough that the warning is emitted to stdout and causing the tests to fail (however only on release build for some reason). I wanted to nip this in the bud before it became a larger issue.
Since the tests all set the -q flag, this will suppress the warning from triggering during the tests.
=> Suppress slow disk warning when --quiet is set

src/json/json5.h, src/runtime/job.cpp
Some of the json functions in the LSP code were incorrectly using the new bool json function do to implict operator overloading.
This broke the LSP; the change below makes bool `add`s explicit
=> Explicitly call into add_bool instead of relying on implict choice by compiler

src/runtime/database.cpp, src/runtime/database.h, tools/wake/describe.cpp, tools/wake/describe.h, tools/wake/main.cpp, tools/wake/timeline.cpp
Previous `wake --failed` output
```
Job 6942:
Command-line: /usr/bin/pkg-config --short-errors --modversion utf8proc
Environment:
PATH=/usr/bin:/bin
Directory: .
Built:     2023-01-31 13:18:42.072612856
Runtime:   0.00104657
CPUtime:   0.000832
Mem bytes: 0
In  bytes: 0
Out bytes: 0
Status:    1
Stdin:     /dev/null
Inputs:
Outputs:
Job 6962 (compile c++ src/runtime/job.native-cpp14-release.o):
Command-line: /usr/bin/c++ -std=c++14 -Wall -Wno-format-security -O2 -Isrc -Ivendor -pthread -Isrc -Ivendor -c src/runtime/job.cpp -frandom-seed=src/runtime/job.native-cpp14-release.o -o src/runtime/job.native-cpp14-release.o
Environment:
PATH=/usr/bin:/bin
Directory: .
Built:     2023-01-31 13:18:42.957944086
Runtime:   0.785592
CPUtime:   0.778175
Mem bytes: 191926272
In  bytes: 291708
Out bytes: …
```
=> colorless --failed

share/doc/wake/quickref.md
It seems like `.` and `|` are apples and `->` is an orange... break this out in the quickref
=> quickref: some points on parameter passing

src/runtime/term.cpp, src/util/term.h, tests/wake-unit/stdout, tools/wake-unit/term.cpp, tools/wake-unit/unit.h
This change drastically improves TermInfoBuf and its testing. I now have tests that near comprehensively generate content over a range of inputs that should be a super set of the vt100 mode escape sequences seen here: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Single-character-functions and the latest code passes all of these tests. Additionally to ensure Unicode characters are not unduly mutated (they shouldn't be because escape sequences tend to be 7-bit) we've also added explicit Unicode support so that all Unicode is entirely unfettered.
=> Massively improved filtering and testing for TermInfoBuf

src/runtime/database.cpp, src/runtime/database.h, tools/wake/main.cpp
Running `--last` or `--last-used` will include all jobs where `used_id == the highest run_id`. This creates a stable output that ignore the cache status when capturing jobs.
`--last-executed` functions as `--last` used to where only jobs that *executed* in the last run are captured.
=> implement last-used and move old functionality to last-executed

.gitignore, src/job-cache/hash.h, src/job-cache/job-cache.cpp, src/job-cache/job-cache.h, src/job-cache/schema.sql, tests/job-cache/basic-fetch/pass.sh, tests/job-cache/basic-fetch/some-input.txt, tests/job-cache/basic-fetch/test.wake, tests/job-cache/dup-output/pass.sh, tests/job-cache/dup-output/test.wake, tests/job-cache/symlink-dir/pass.sh, tests/job-cache/symlink-dir/test.wake
These were all known issues that we haven't hit testing against real code yet but which I believe will come up. At this time this represents all known bugs with shared caching. The next step is to test it more widely on more code and to fuzz test the cache type in C++.
Issues fixed:
* Output directories would be ignored so if a tool created a directory with a non-standard mode or if it that created a directory that contained no files that directory would not be created. We now store these in the cache database and recreate them faithfully. If we did have to hash them they would hash to all zeros but we don't need to do that.
* Symlinks would have been hashed to the content of the file they pointed to and the content of the file they pointed to would have been copied instead. We store the …
=> Fix several small issues with shared caching

share/doc/wake/logging.md
Thanks for @richardxia for pointing this out!
=> Fix default destination of a job's stderr in the logging docs

share/wake/lib/system/job.wake, src/runtime/database.cpp, src/runtime/database.h, src/runtime/job.cpp
Before we release is_atty we need to make it part of the primary key since jobs change their behavior when is_atty is changed. This requires a database schema update which is going to mean that everyone is going to have to delete their databases but at least wake will tell them that they need to do so.
=> Make is_atty part of primary key

share/wake/lib/core/list.wake
`sortBy` was recently updated in 0.30 to use `Order` comparison rather than `Boolean` comparison, but the examples and documentation weren't updated. I have updated the examples to use comparisons returning an `Order` in addition to making the examples executable. Personally, I think explicit examples should be executable, as that's typically the first thing a user is going to do by copying them, executing them, and then modifying them to learn a function's behavior. The more generic examples are useful, but I think those probably belong as part of the documentation string.
=> Update `sortBy` examples to use `Order` and to be executable

src/dst/bind.cpp, tests/dst/packages/stderr, tests/dst/packages/test.wake, tests/dst/packages/test4.wake
Emit an LSP warning on unused import. Right now it only works for qualified imports but should be possible to support import all imports.
One thing I'm not sure about is how we roll out to existing users without causing a bunch of warnings? Maybe we are okay with doing that? Not sure if many folks use "warn as fail" or not.
=> Warn on unused import

src/wakefs/namespace.cpp
When using wakebox's squashfs support, if a user has particular versions of libfuse then they can not mount over a non-empty directory (and this was happing in a namespace, and we moved the mount directly aftewards).
We were using `/mnt`, in this PR we create a dedicated directory to put these squashfs mounts before moving them.
(We stage/move them because within the squashfs it contains a file which must be read to say where to really mount it)
=> Use wake-specific staging mountpoint for squashfs mounts

src/runtime/sources.cpp
Fixes #1139 
For some reason we were skipping the first character of the wake version meaning `0.30.0` would be seen as `.30.0` during semver parsing. My thought was that previously it started with `v` and we needed to skip that but I went back to 0.18.0 and even that didn't have a leading `v` so this must be a fairly longstanding bug.
I still don't know why we were skipping so if anyone can give context that would be great, this does fix the issue though.
=> Fix parsing wake version

tools/wake/describe.cpp
When reaching for a stack trace via `--debug` a user likely also wants stdout/stderr to be output. This was previously achieved with `-dv` but now that you can only set one describe policy this handle was lost.
This change switches `debug` policy to align with `debug verbose` so that no fidelity is lost
=> Show stdout+stderr as part of debug

src/runtime/database.cpp, src/runtime/database.h, tools/wake/main.cpp
Running wake with `--label` allows you to provide a glob  to capture jobs based on the job label. Commandline globbing isn't supported since commandline is stored as a blob not a string. This may be added in the future.
```
> wake --label '*123*'
> wake--label '*re2c*'
$ /usr/bin/re2c --version
re2c 3.0
$ /usr/bin/re2c -8 --no-generation-date --input-encoding utf8 src/parser/lexer.re -o src/parser/lexer.cpp
$ /usr/bin/re2c -8 --no-generation-date --input-encoding utf8 src/json/jlexer.re -o src/json/jlexer.cpp
> wake --label 'lemon*'
$ /usr/bin/m4 src/parser/parser.y.m4
...
...
```
=> Support capturing jobs via label glob

tools/wake/main.cpp
Running `wake -o file1 file2 --verbose` didn't capture `--verbose` since `-o` consumed positional args leading `--verbose` to be treated as a file. Fix this by changing -i/-o use a required arg repeated for each instance. `wake -o file1 -o file2 --verbose`
=> Don't consume positional args for input/output flags

share/doc/wake/tutorial.md
The way we pass arguments to `List String` CLI targets (no `-x` when running) is mostly intuitive if you've got a "subcommand" you're already expecting to pass arguments to, but even one-off targets which don't do anything with their arguments still gobble anything following them, rather than the potentially-expected behaviour of flags being passed to `wake` itself.  I've added a paragraph in the tutorial to clarify that.
=> Add note on Wake arguments vs. List String targets

src/wcl/optional.h, src/wcl/result.h, tests/wake-unit/stdout, tools/wake-unit/diff.cpp, tools/wake-unit/result.cpp
This change adds a `result` type for better error handling in wake. This is in line with modern C++ code bases like llvm/clang, tensorflow, etc... and matches rust and funny enough wake's error handling style.
This is part of a series of changes that will end in adding an LRU eviction policy to shared caching. The next change, which I wanted this change for, will be to add a better read-dir library next.
=> Add result type to wcl

build.wake, extensions/vscode/vscode.wake, share/wake/lib/system/job.wake, tests/job-cache/basic-fetch/test.wake, tests/job-cache/dup-output/test.wake, tests/job-cache/symlink-dir/test.wake, tests/runtime/symlinks/test.wake, tests/tests.wake, tests/wake-format/basic/basic.wake, vendor/gmp.wake, vendor/lemon/lemon.wake, vendor/re2.wake, vendor/re2c.wake, vendor/sqlite3.wake
Since we've previously only had support for a single, local cache, we've not paid much attention to the difference between `Keep` and `Share` persistence; this PR goes through every job in the repo to evaluate whether it relies on some environmental factor which would prevent sharing.  A few specific notes:
* To be safe, I've gone ahead and not allowed sharing for anything internet-connected, even if it theoretically should point to a frozen file; I've not looked at any third-party licenses to see whether sharing compiled binaries might run afoul of distribution-related clauses (since *nothing* is shared currently, we're not distributing *anything* but the sources currently).
* Our tests were previously cached.  I don't expect that to have broken anything, but it's a bit of an …
=> Mark environment-sensitive jobs as unsharable

share/wake/html/main.js, share/wake/html/style.css, tools/wake/markup.cpp
This makes a number of non-functional changes to the `wake --html` output to modernize the code and make it easier to work with (IMO, at least). See the individual commits for more information about each change, but at a high level, this:
- explicitly declares the document to be HTML5, since it's no longer 2010
- relies less on DOM APIs that require parsing strings and instead uses the APIs that let you directly modify elements in a structured way. e.g. `Element.cssText` -> `Element.style`, `Element.setAttribute()` -> `Element.<specific attribute name>`.
- moves almost all styling to CSS, and JS is only used to add or remove CSS class names on elements
- uses the official [`data-`/`dataset` API](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) for setting …
=> html: Refactor and modernize HTML/CSS/JS

tools/wake/describe.cpp
Fixes #1154.
Output jobs with fewer newlines.
```
> ./bin/wake --last
$ /usr/bin/dash -c sleep 1; echo 2; echo foo > somefile2;
2
$ /usr/bin/dash -c sleep 6; echo 1; echo foo > somefile;
1
```
```
> ./bin/wake --last
....cut.....
$ /usr/bin/re2c --version
re2c 3.0
$ /usr/bin/c++ -std=c++14 -Wall -Wno-format-security -O2 -Isrc -Ivendor -pthread -c src/parser/syntax.cpp -frandom-seed=src/parser/syntax.native-cpp14-release.o -o src/parser/syntax.native-cpp14-release.o
$ /usr/bin/c++ -std=c++14 -Wall -Wno-format-security -O2 -Isrc -Ivendor -pthread -c src/parser/wakefiles.cpp -frandom-seed=src/parser/wakefiles.native-cpp14-release.o -o src/parser/wakefiles.native-cpp14-release.o
$ /usr/bin/cc -o vendor/lemon/lemon.native-c11-release vendor/lemon/lemon.native-c11-release.o -std=c11 -lpthread
$ …
```
=> describe: Minimize newline output

share/wake/html/main.js, share/wake/html/style.css
This builds off https://github.com/sifive/wake/pull/1179 by adding new dark and light color themes for the generated HTML pages. I added a theme toggle to the top right of the page, but I otherwise default to your OS's settings (and failing that, it defaults to the light theme).
I originally attempted to colors from popular open source themes like Solarized and Dracula, but none of them worked well for the several colored background highlights that are used in the wake generated HTML. I ended up making up my own theme using purple as the primary tint and basing the remainder of the colors off the original hues that wake used. I lightened the background color and darkened the text colors, since the original wake styles used pure black and pure white, which causes excessive contrast and can …
=> html: Add new dark and light themes.

src/wcl/filepath.cpp, src/wcl/filepath.h, tests/wake-unit/stdout, tools/wake-unit/filepath.cpp, tools/wake-unit/unit.h
This change adds a wrapper around posix readdir in order to make iterating directories simpler, more C++-ish, and improve error handling for it.
=> Add directory_range to wcl

tools/wake/cli_options.h, tools/wake/main.cpp
This PR extracts the command line variables that were polluting the main() function into a separate struct (and does nothing else)
I've had several false starts here and I think I've pinned down the core issues from before
1) I was trying to do too much refactoring all at once
2) I didn't fully understand what each argument expected
I took the time to learn what the args were expecting and I made this PR as small as possible so I think I'm happy with the result here.
There are still several changes I want to make like moving the cli validation code, adding tests, extracting more out of main, and reworking the actual cli interface but this change is the minimal precursor to all of that.
I tried out several different flags (including the more hairy ones) but please feel free to try any …
=> cli: Move command line parsing to dedicated class

debian/changelog.in
Prep for v32.0.0 release. 
For this release we are moving to SemVer and promoting the old "minor" version to the "major" version.
=> [v32.0.0] Set release date.

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h
An apply that "looks" like a constructor, something like 
```
Identifier (
some,
expression
)
```
is now formatted without a newline between the lhs and rhs
Bonus: the assign operator (`:->` )  is always emitted "flat" as adding newlines makes the code confusing.
Bonus #2: if-else-match has else and match on the same line
=> format simple constructor applies on the same line

tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp, tools/wake-format/types.h
PTAL a look at the formatting @ag-eitilt but I wouldn't focus on the C++ implementation for the moment. I want to tweak how we add things to ctx_t so it'll probably change a bit.
This is the implementation of the rules
-  always newline `|` and `$` when they are the "root" of a binary op chain
- when `|` and `$` are not the root, apply the normal binop formatting rules (don't newline if you fit)
=> Newline top level pipes/dollars

tests/wake-unit/stdout, tools/wake-unit/cli_options.cpp
Adds some basic  test for command line options. Should give a bit of protection for future refactors.
=> cli: Add basic cli parsing tests

tools/wake/main.cpp
When failing an invocation its useful to list out the problematic arguments. When wake is invoked from a tool it might not be immediately obvious what the invocation command like was.
```
./bin/wake -o zero one two three
Unexpected positional arguments on the command-line!
'one' 'two' 'three'
```
=> cli: list out unexpected positional args

share/wake/lib/core/list.wake
One of the examples for `find` had an off by 1 index error.
Can verify using `wake -x find (_==10) (85, 4, 10, 3, Nil)`.
=> Fix example for `find`

tools/bsp-wake/main.cpp
https://github.com/sifive/wake/pull/1161 changed how input/output arguements were specified. This broke `bsp-wake`. 
This change fixes bsp-wake to launch wake as expected.
=> bsp: Use -o flag for each ouput file

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/actions.h, tools/wake-format/formatter.h
Fixes trailing  white space that is  emitted after a  nested floating comment. Also adds more tests around floating  comments to catch other potential breakages
=> format: remove trailing whitespace from bound comments

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
- Simple 2 item applies like `Some ""` where each item is a literal or id is now considered a "simple literal"
- this also means a top level `def x = Some ""` doesn't get newlined/is considered a constant
- Simple 2 part binop like `x < 0` where the lhs/rhs is a literal or id is now considered a "simple binop", and the shape `if simple_binop then simple_literal else simple_literal` is eligible to be on a single line
- `|` or `$` nested inside of parenthesis are now eligible to be on a single line
=> Tweak the defination of simple parts to be more permissive

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/actions.h, tools/wake-format/catters.h, tools/wake-format/emitter.cpp, tools/wake-format/formatter.h, tools/wake-format/types.h
Fixes 
`def Pair _ _:                      Pair Integer String = Pair 44 "as"`
not getting the white space removed without causing 
```
def tool (dir: String)  (addHeaders: String) (addHeaders: String) (addHeaders: String) (addHeaders: String) (addHeaders: String) (addHeaders: String) (addHeaders: String)  (addHeaders: String) (addHeaders: String) (addHeaders: String) = ""
```
to explode into the invalid
```
def tool
(dir: String)
(addHeaders: String)
(addHeaders: String)
(addHeaders: String)
(addHeaders: String)
(addHeaders: String)
(addHeaders: String)
(addHeaders: String)
(addHeaders: String)
(addHeaders: String)
(addHeaders: String) = ""
```
=> format: Prevent explode in def pattern

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/actions.h, tools/wake-format/catters.h, tools/wake-format/common.h, tools/wake-format/emitter.cpp, tools/wake-format/formatter.h
Newlines are now emitted inside of a def/require body based on the following rules.
1) multi-line def/requires get a newline
2) the “return” item gets a newline
3) a commented item gets a newline
4) changing def<->require gets a newline
4) anything else doesn't
=> format: specifiy internal newlines based on structure

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
1. `export def (argument: a) | (pipeFn: a => b): b = pipeFn argument`
and 
2. `def x = Some 5`
are the same from the perspective of the formatter thus they need the same formatting rules.
It is more preferred that 1 format correctly with a newline than 2 format without one so all top level defs will always newline now.
=> format: Remove special case for constants

tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
For the MVP, I want to skip splitting types into multiple lines. It has some implications we haven't explored yet and technically isn't supported
=> format: Disable splitting types across multiple lines

share/wake/lib/core/json.wake, share/wake/lib/core/print.wake, share/wake/lib/system/job.wake, tools/lsp-wake/lsp.wake, vendor/emscripten.wake, vendor/git.wake
Certain code isn't supported and generally can't be  supported by the formatter.  There will always be cases (do to the infinite nature of recursive grammars) where the programmer know better. This change  handles those cases manually in sifive/wake
=> format: prepare wake code for formatter

tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Since `target` and  `publish` can only be top level (per the  grammar) we just always newline after the `=`
=> format: always newline top level publish/target

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/actions.h, tools/wake-format/emitter.cpp, tools/wake-format/formatter.h
`|` and `$` inside of an `if`/`else` condition shouldn't be considered a "root" binary operation otherwise it formats as
```
def x =
if cmpFn
| isGT then
0
else
0
```
This change fixes that and also adds a `ChangeContextAction` instead of a new `binop` formatter function that way `binop` is  easier to delete in the future
=> format: | and $ shouldn't force explode in if/else

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
https://github.com/sifive/wake/pull/1218 but for patterns.
Same justification. Focusing on the MVP and it has some implications that need to be explored before wide rollout.
=> format: don't split long patterns

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h
Fix comments being added/deleted when bound to a binop. Now collects the in-between binops into the parts list instead of just tracking a reference to the first one.
The output isn't formatted the best but at least the correct content is emitted now.
Ex:
```
def x =
a
| b
| c
def x =
a
| b
| c
```
was previously emitted as 
```
def x =
a
| b
| c
def x =
a
|
b
|
c
```
=> format: Correctly emit bound comments for binops

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/actions.h, tools/wake-format/emitter.cpp
Certain repos were crashing the formatter or emitting invalid code on format. This change fixes (nearly) all the breakages.
Broken rules:
1) Missing a space in an ascribe caused an assert
2) Really long require patterns would explode (as expected) but if the pattern is a binop (like `require a, b, Nil = blah`) then exploding isn't legal syntax. Explode is now disable in requires for binops. In the same vein, target patterns are prevented from exploding
3) Multiline strings without indentation caused an assert because it was always assumed that a TOKEN_WS would exists. This case now probably indents
4) An overly restrictive assertion that CST_BLOCKs only contain CST_DEF was removed as they may also contain imports
There is a subtle but with `"% ... %"` strings that I haven't figured out …
=> format: Fix various broken rules

tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Delaying major refactors/rewrites until after we roll out the MVP. It'll minimize the diff and also allow us to verify the rewrites in isolation
=> format: delay rewrites to post MVP

.github/workflows/build.yaml
The github mac builders are no longer working. It's time to remove it and drop macos support. At this time we don't plan on actively removing mac support but it isn't going to be tested for now.
=> Remove macos from our CI

share/wake/lib/core/print.wake, src/runtime/status.cpp, tools/bsp-wake/main.cpp
This change is needed in order enable some use cases we forgot. The most important one is allowing wake to act as a build server via bsp-wake.
=> Refine log level changes to maintain use cases

src/job_cache/db_helpers.h, src/job_cache/eviction_policy.cpp, src/job_cache/eviction_policy.h, src/job_cache/job_cache.cpp, src/job_cache/job_cache.h, src/job_cache/job_cache_impl_common.cpp, src/job_cache/job_cache_impl_common.h, src/job_cache/logging.h, src/job_cache/schema.sql, src/runtime/config.cpp, src/runtime/config.h, tests/config/empty/stdout, tests/config/extra_keys/stdout, tests/config/missing_user_config/stdout, tests/config/nominal/.wakeroot, tests/config/nominal/stdout, tests/job-cache/basic-lru/.wakeroot, tests/job-cache/basic-lru/pass.sh, tests/job-cache/basic-lru/test.wake, tools/wake/main.cpp
What it says on the tin, this implements an LRU eviction policy for wake's shared cache. There are still some TODOs however
1) This is complicated and needs at least a bit of testing as a smoke test if nothing else. Before being confident putting this live I think we need more extensive fuzz testing but at the very least I'd like to see a basic test that exercises the LRU policy.
2) Right now I have the high and low water marks set at 16GB and 8GB, that needs to be configurable somehow and I haven't yet decided how to make that configurable. It would be *super* nice to implement this for testing to solve 1)
Other than those two points, its ready for eyeballs on it.
=> Implement an LRU eviction policy for wake's shared cache

README.md, src/json/json5.h, src/runtime/config.cpp, src/runtime/config.h, src/runtime/status.cpp, tests/config/empty/stdout, tests/config/extra_keys/stdout, tests/config/missing_user_config/stdout, tests/config/nominal/.wakeroot, tests/config/nominal/stdout, tools/wake/cli_options.h, tools/wake/main.cpp
This change adds the option to not align your log headers which is on by default. You can turn it back on however.
=> Refine log headers

share/doc/wake/tutorial.md, share/wake/lib/system/job.wake
As part of moving away from encouraging label-less and implicit-runner jobs, the old `job` and `shellJob` wrappers are unnecessary and even undesirable.
There are a lot of places in the code which reference `job` objects, but all of those are shadowed names rather than referring to this function.  At this point, the only use of `job`-the-function is in the wake-format tests, which we want to keep frozen anyway to test the previous format.
Fixes #1254
=> Remove `job` and `shellJob` wrappers around `runJob`

src/runtime/status.cpp
We hit some issues where users want some side streams to emit a machine readable format (e.g. without escape sequences) but also want interactive features on the typical streams. Ideally we'd have some more refined way of doing this but this should be good enough for all current use cases.
=> Only set istty=true on StatusBuf on fd 1 and 2

src/job_cache/daemon_cache.cpp, src/job_cache/job_cache.cpp, src/job_cache/job_cache_impl_common.cpp, src/job_cache/message_parser.h
This change does a couple things
1) It makes communication between the daemon and client blocking. It wasn't blocking before because we based this code off of some code that I wrote ages ago that didn't use epoll at first and instead would just busy read from each client until it could get something. I switched to epoll forever ago in that code but the non-blocking accept stayed with it for some reason. This doesn't present an issue unless you fill up the kernel's buffer for the socket which never happens on small messages.
2) The code on both sides is now hardened so that in theory its compatible with non-blocking sockets. Hopefully we don't have to rely on that code as it essentially busy waits until it gets a read which is not great. I'm not sure if Linux will reschedule on blocking …
=> Fix failure to handle large messages

share/wake/lib/gcc_wake/gcc.wake
There's no real reason not to have debug information on every type of build. It increases binary size drastically (~20x in the case of wake) but Wake is only ~2.5MB so increasing to ~50MB really just isn't that big of a deal and it saves us a huge amount of headache debugging things sometimes.
Size increases:
wake: 2.53MB -> 49.3MB
wakebox: 0.275MB -> 5.35MB
wake-format: ? -> 40.4MB
fuse-waked: 0.235MB -> 3.37MB
lsp-wake: ? -> 26.6MB
shim-wake: 32.1KB -> 0.159MB
wake-hash: 0.226MB -> 0.803MB
bsp-wake: ? -> 4.59MB
So the total package size will be dominated by the binaries and will be around ~135MB which is still a very acceptable size IMO. If need be there are settings that we can play with to reduce debug information size. We can also split debug information from these binaries and ship …
=> Always ship wake with debug information

share/doc/wake/quickref.md, share/wake/lib/gcc_wake/gcc.wake, share/wake/lib/gcc_wake/pkgconfig.wake, share/wake/lib/system/incremental.wake, share/wake/lib/system/io.wake, share/wake/lib/system/job.wake, share/wake/lib/system/path.wake, share/wake/lib/system/sources.wake, tests/tests.wake, vendor/git.wake
This removes 2 fields from `Plan`
* `LocalOnly`
* `RunnerFilter`
This is a breaking change.
Some jobs relied on using `LocalOnly`, they have been transitioned to using `runJobWith localRunner` and some were removed.
Documentation received some very light updates.
The `runJob` score function becomes unable to select the localRunner, as it's no longer published to the runner topic.
A user who still needs this could in theory decide to publish a wrapper of the localRunner to that topic, that looks at some otherwise opaque Resource strings to determine if it should be used instead of the fuseRunner.
=> remove Plan's LocalOnly and RunnerFilter

Makefile, share/wake/lib/system/job.wake, share/wake/lib/system/path.wake, tools/wakebox/main.cpp
If you set `WAKEBOX_KEEP_IO_FILES=1` you'd see files in a `.build` directory that look like
``` 
$ ls .build/
2272028.29.in.json
2272028.29.out.json
2272028.301.in.json
2272028.301.out.json
2272028.302.in.json
....
```
These files correspond to the input specification (`*.in.json`) and result (`*.out.json`) for each wakebox job.
The first element is the process id of wake on the current machine, this is often not useful information to a user.
The second element is the job id from the database, that users see in `wake --last/--failed`
In this PR: 
* remove the PID from the filenames
* remove in/out.json filename suffixes, replace with spec/result
* the tracking of the files are adjusted to allow `wake --clean` to remove them
* `WAKEBOX_KEEP_IO_FILES` option is removed, the spec/result …
=> use job numbers for wakebox spec and result jsons

share/wake/lib/system/job.wake, share/wake/lib/system/path.wake, tools/wake-hash/main.cpp
This change is to fix an issue where the new batch hashing cannot handle extremely large numbers of files. This change makes it so that we generate a file if the number of files to hash is large enough but use the command line otherwise. The file is unlinked as the last step if it was created.
Additionally while I was at it, I converted to a work stealing scheme instead of dividing things up "evenly". This should make much much better use of available cores and spread the total work load much more evenly. There are still some optimizations we could do to hashing like using async io to create a more generic work queue so that we can work steal multiple hash digests at a time off a single thread. I think if we do that we should probably instead implement the hashing-in-fuse optimization
=> Make batch hashing work for arbitrarily large numbers of files

src/job_cache/message_parser.h, src/wcl/xoshiro_256.cpp, tests/tests.wake, tests/wake-unit/stdout, tests/wake-unit/unit-test.sh, tools/wake-unit/fuzz_test_job_cache.cpp
This change improves shared caching fuzzing to be a bit more flexible. We can now test parallelism and large message sizes which will catch the new issues we've seen thus far that basic_fuzz_testing didn't catch. Additionally there was one minor bug fix with regards to how ECONNRESET was handled.
=> Improve shared cache fuzz testing

src/job_cache/job_cache.cpp, src/job_cache/job_cache.h
This is a repush of https://github.com/sifive/wake/pull/1279 rebased and re-targeted to master. There was a bunch of merge conflict I didn't want to deal with so I'll just close that PR after comments from it are resolved here.
Job cache client now attempts to recover from several failure modes related to the job cache daemon. Launching and connecting to the daemon is reattempted several times with backoff. Cache read requests are also retried including relaunching and reconnecting to the daemon with backoff. After a set number of attempts the retries will give up and fail. Currently on failure wake will exit with code `1` however the scaffolding is in place so that wake can later be configured to just return a cache miss on failure
=> Increase robustness of job cache client

src/job_cache/daemon_cache.cpp, src/job_cache/db_helpers.h, src/job_cache/eviction_policy.cpp, src/job_cache/job_cache.cpp, src/job_cache/job_cache_impl_common.cpp, src/job_cache/types.cpp, src/wcl/tracing.cpp, src/wcl/tracing.h, tools/job-cache/main.cpp, tools/wake/main.cpp
The internal logging api was already starting to explode. Instead of a million subtlety different helper functions this PR converts wake logging into a more fluent api that can be used to layer in more information.
```C++
wcl::log::event("msg: %s", "var").warning().urgent().pid().time()();
```
There are still some helper functions for the most common use cases 
```C++
wcl::log::warning("msg: %s", "var")();
```
the trailing `()` is the signal to "consume and trigger the event" enabling flexible usage like the following
```C++
Event e = wcl::log::warning("msg").info();
e.items["A"] = "B";
e();
```
=> Shift wake log to be more fluent

Makefile, src/wcl/wcl.wake, tools/shim-wake/main.cpp, tools/shim-wake/shim.wake
This just causes shim-wake to clean up all its unneeded files before exec-ing to be more hygienic.
=> Clean up extra file handles

share/wake/lib/core/print.wake, src/runtime/string.cpp, src/wcl/tracing.cpp, src/wcl/tracing.h, tools/wake/main.cpp
Three smaller improvements to the newly added internal logger
- delete the `wake.log` file on `wake --clean` since its append only  and could get quite large
- "Urgent" filter that emits event to stderr for user notification
- Add a  `breadcrumb` prim so that wake lang can drop debugging hints into the wake internal log
=> breadcrumb prim, filter subscriber, log cleanup

README.md, src/job_cache/job_cache.cpp, src/job_cache/job_cache.h, src/runtime/config.cpp, src/runtime/config.h, tests/config/empty/stdout, tests/config/extra_keys/stdout, tests/config/missing_user_config/stdout, tests/config/nominal/.wakeroot, tests/config/nominal/stdout, tools/wake-unit/fuzz_test_job_cache.cpp, tools/wake/cli_options.h, tools/wake/main.cpp
`cache_miss_on_failure` may be set (`true`|`false`) in the wake config to generate a cache miss when something goes wrong with the Daemon JobCache instead of falling over.
This is useful for users with long running builds who would rather  the build take a bit longer overall  verses dying several hours in
=> Add option for cache miss on failure

tools/wake-format/main.cpp
`wake-format -n ....` now prints the file name of the failing file. This is helpful when formatting several files at once with `-n`
=> Include name of failing file in dry run

src/job_cache/daemon_cache.cpp, src/job_cache/daemon_cache.h, src/job_cache/eviction_policy.cpp, src/job_cache/eviction_policy.h, tools/wake-unit/fuzz_test_job_cache.cpp
This change adds two functions to the job cache
1) If a corrupted job is detected, instead of just returning a cache miss, we clean up that job so future checks won't fail
2) If a folder storing the hashed files of a job exists in the folder but does not exist in the database, we clean up the folder
=> Make job cache more self-healing

src/job_cache/daemon_cache.cpp, src/job_cache/eviction_policy.cpp, src/job_cache/job_cache_impl_common.cpp, src/job_cache/job_cache_impl_common.h
This change causes the shared cache .stderr file to log evictions. It would be nicer to log to .stdout but that is being used as a communication channel between the job-cache daemon and the eviction child process. We should be able to switch the eviction child process over to a thread now which would resolve this issue.
=> Log when an eviction occurs

share/wake/lib/system/job.wake
We had the quite silly behavior of caching job failures before which makes no sense. This change eliminates that.
=> Never cache a failed job

share/wake/lib/system/job.wake, src/job_cache/daemon_cache.cpp, src/job_cache/schema.sql, src/job_cache/types.cpp, src/job_cache/types.h
This change allows runner authors to add in some kind of hash or other key (I call it a "runner hash" but it is allowed to be any string) to allow runner authors to make the cache aware of differences in jobs that may not be otherwise apparent. This also allows less conservative use of shared caching with the trade off of being more conservative about what is considered to be "matching" and puts this trade off in the runner author's control.
=> Add runner hash

share/doc/wake/logging.md, share/wake/lib/core/print.wake, src/runtime/status.cpp, src/runtime/status.h, tools/wake/main.cpp
- logInteractive is now a log stream that only displays when a tty is set, usually implying a human is running the command
- logEcho doesn't get printed by default when --no-tty is set, most folks don't want echo when setting --no-tty, and CI can add it back manually if they want it
- The logging docs had drifted a bit, they are now updated
=> Add logInteractive, remove echo from no-tty, update docs

src/job_cache/eviction_policy.cpp, tests/wake-unit/unit-test.sh
This is a quick fix we need to get in to make sure people can use shared caching so we can get better tests.
=> Fix dirty startup code, and add dirty startup testing

tools/lsp-wake/lsp.wake, tools/lsp-wake/main.cpp
Adds an env var `WAKE_LSP_LOG_PATH` which when set will write lsp logs out to the provided filepath.
Useful for debugging unexpected lsp reactions.
the header `rpc` can be grepped to extract just the messages exchanged between client and server
`cat file.log | grep 'rpc='` -> all messages
`cat file.log | grep 'rpc=tx'` -> all messages from server to client
`cat file.log | grep 'rpc=rx'` -> all messages from client to server
=> Add opt in logging for lsp-wake

.github/workflows/build.yaml, .github/workflows/dockerfiles/rocky-9
Add Rocky 9 to CI
Only github actions CI is added, as that is used for generating releases, circle CI is ignored
This should be compatible with RHEL9, but it's not feasible to use RHEL9 directly.
=> CI: add rocky 9

tools/lsp-wake/main.cpp
I accidentally left in a debug print that puts us out of spec. This removes it
=> lsp: Remove debug print

src/job_cache/job_cache.cpp
While on the daemon side we did in fact do a mkdir -p style directory creation, we failed to do this on the client side which actually runs first. This change just adds that functionality to the client side as well.
=> Make both daemon and client create directory as if by mkdir -p

src/runtime/job.cpp, src/runtime/status.cpp
This fixes two issues
1) If a job is not hygenic about its color output, wake was not cleaning up after it. This change fixes that and does an extra defensive cleanup at the end
2) There was as segfault that was occurring when SIGTERM was sent in the middle of a run. I finally figured out that this was because the StreamBuf destuctor was trying to write to an invalid TermBufInfo and that was happening because the TermInfoBuf that it was referring to was not being deleted in the correct order. That order is affected by the order of the fields but its better to just manually write code that releases the data in the correct order in the JobTable::detail destructor.
=> Fix some oversights in statusbuf code

src/job_cache/job_cache.cpp
There is a race that can happen if you run a wake process directly after another wake process that looks like this:
1. A wake process runs and successfully creates and connects to a shared cache daemon
2. That wake process exits
3. That shared cache daemon sees that it has no more connections which sends it into a shutdown sequence but the shutdown sequence doesn't complete before...
4. A new wake process starts up, trys to create a daemon, that daemon sees that the cache lock is still locked so it exits
5. The shutdown sequence from step 3 finishes and releases the lock
6. The process from step 4 keeps trying to connect but there is no shared cache to connect to
Aside from that race being an issue, there are all sorts of reasons why a shared cache daemon might fail while we're trying to …
=> Fix race between previous daemon close, and next daemon create

share/wake/lib/system/job.wake
Sometimes you might want the benefit of cache hits but not trust the source to write to the cache (for instance in pre-merge CI perhaps). This PR adds that ability which can be set by setting `WAKE_EXPERIMENTAL_JOB_CACHE_READ_ONLY=1`
=> Add read only mode for shared caching

tools/lsp-wake/json_converter.cpp
There are likely several instance of these, but just throwing this up as a quick fix.
Per the spec here https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#responseMessage
> The result property of the ResponseMessage should be set to null in this case to signal a successful request.
We were previously sending `{}` instead of `null` which less forgiving languages are not happy with.
=> lsp: Result should be null instead of empty object

vendor/lemon/lemon.c, vendor/lemon/lemon.wake
The template we pass to lemon is only compatible with C++ not C. 
Right now when we build, lemon emits an invalid `.c` which we rename to `.cpp`. This leaves the invalid `.c` file on disk.
On certain targets (fedora) the `.c` file maybe be used to generate the `.o` file instead of the `.cpp` file which causes an expected error in the C compiler.
This change makes it so the `.c` file is never emitted thus can't be erroneously used.
=> lemon: Emit cpp files from lemon

tools/wake/main.cpp
Fixes #1314 
Move verbose before debug in priority list since verbose has less information.
=> db: Switch verbose and debug priority

share/wake/lib/system/job.wake, src/wakefs/daemon_client.cpp, src/wakefs/fuse.cpp, src/wakefs/fuse.h, src/wakefs/namespace.cpp, src/wakefs/namespace.h
Introduces a PID namespace for wakebox (linux-only).
Wakebox was leaking the existence of a file via `/proc/self/fd`. 
The file was used to let the `fuse-waked` daemon know when all users of it's fuse mountpoint had closed, by wakebox leaving the file open as child processes forked.
The file was not actually accessible by wakebox's payload command however, as it is hidden by the mount table changes where we bind-mount `workspace/.fuse/$UID.$GID` onto `workspace/`.
The motivation of this change, is that some payload commands actually try to read the files symlinked via `/proc/self/fd`, so those payloads would encounter the unexpected situation of a file that _is_ open, but where the path is not accessible.
Changes (linux only): 
* the live file for fuse-waked is closed on exec
* instead of …
=> PID namespace for wakebox isolation

.github/workflows/build.yaml, .github/workflows/dockerfiles/fedora-38, src/json/utf8.cpp, src/json/utf8.h
I end up using Fedora a lot with Wake and I assume others do as well. This will help make sure things don't break in Fedora.
This PR might fail at first as @V-FEXrt and @JakeSiFive have not merged in the Fedora 38 related patches to master.
=> CI: add Fedora 38

src/wakefs/fuse.cpp, src/wakefs/namespace.cpp
In this PR:
* If the `wakebox` process exits, the `wb-mount-ns` process will be sent `SIGTERM`.
* If the `wb-mount-ns` process exits, the `wb-pid-ns` process will be sent `SIGTERM`.
In an earlier PR:
* When the `wb-pid-ns` process terminates, the whole pid namespace collapses and all its children terminate.
So, if you have a process tree that looks like:
```
$ pstree -p 2815889
bash(2815889)─┬─fuse-waked(2826391)
└─wakebox(2826388)───wb-mount-ns(2826394)───wb-pid-ns(2826395)───mypayload(2826396)
```
Then if you send a signal to _any_ of `wakebox`/`wb-mount-ns`/`wb-pid-ns`/`mypayload`, then everything except the root `bash` process will exit.
=> wakebox: signal when parent exits

src/util/mkdir_parents.cpp
Previously we relied on `mkdir` claiming that a (parent) directory already exists.
There are some circumstances where the kernel will report other issues _ahead_ of saying that the directory already exists.
For example, a read-only filesystem error could be reported even when the directory exits.
This PR checks if the directory exists before trying to create it.
=> mkdir_with_parents: skip existing directories

extensions/vscode/lsp-server/src/common.ts
In https://github.com/sifive/wake/pull/1328, I fixed an out of spec response. This caused an issue in the VSCode wrapper for the lsp as we detected the out-of-spec response and rewrote it to be in-spec.
Now that we are in-spec this hack is no longer needed and should be deleted
=> lsp: Fix VSCode wrapper hack around lsp server

tools/lsp-wake/main.cpp
https://github.com/sifive/wake/pull/1307 introduces a couple subtle bugs that snuck through code review and aggressively broke the VSCode extension.
The VSCode extension has several more layers of indirection, a different build target and other subtle differences that direct clients of the native lsp don't exercise. This means its not sufficient to test the extension against native clients. It must also always be tested against VSCode
=> lsp: Fix subtle lsp bugs

src/job_cache/daemon_cache.cpp, src/job_cache/daemon_cache.h, src/job_cache/job_cache.cpp, tools/job-cache/main.cpp
Moves log outputs from `.stdout`/`.stderr` to `.cache.<YYYY-MM-DD>.log`. This was done to make cleaning up old logs easier but also has  the side effect of making our other logging code simplier as we don't have to worry about polluting stdout/stderr
This PR doesn't implement the actual cleanup, that will be a separate PR
=> Move the job cache log to a dedicated file for cleanup

src/job_cache/daemon_cache.cpp
The vast majority of the log spam generated by the daemon cache is from logging out the entirety of ever request received. This only logs that a request happened generating significantly less spam
=> Significantly decrease log spam

src/job_cache/daemon_cache.cpp
Deletes any files in `cache_dir` of shape `.cache.<YYYY-MM-DD>.log` where `YYYY-MM-DD` is more that 4 days from the current date
=> Cleanup old logs on cache start

src/job_cache/daemon_cache.cpp, src/job_cache/daemon_cache.h, src/job_cache/job_cache.cpp, src/job_cache/job_cache.h, src/job_cache/job_cache_impl_common.cpp, src/job_cache/job_cache_impl_common.h, tools/wake-unit/fuzz_test_job_cache.cpp
This change is meant to do the following
1) If a write to a client fails, the daemon keeps running and just closes its connection to that client.
2) If a write to the daemon fails, the client treats that as it would read failures and the client should restart
I don't have a good way to do auto-mated testing of this yet but I manually killed the job-cache many times and everything continued to work perfectly. I don't consider this change complete without automated testing but its hard and I wanted to get these fixes out there first so we can do another release with them in it. All existing tests pass, and manually killing the daemon repeatedly causes no issues that I can observe yet
=> Increase local shared cache robustness to daemon being killed

extensions/vscode/syntaxes/wake.tmLanguage.json, share/doc/wake/syntax/vim/syntax/wake.vim
Macros `@here`, `@line`, `@file`, and `@!` now highlight correctly  (and do so in a color different  than keyword)
I've been meaning to do this for awhile but finally got a random  stroke of inspiration 
VSCode:
Vim:
=> Add syntax highlighting for macros

share/wake/lib/system/plan_scorer.wake, tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
When a `|` was inside a string interpolation is  was being forced into multilining. Don't do that.
Before 
```
"{one | two} three"
```
->
```
"{one 
| two} three"
```
After:
```
"{one | two} three"
```
->
```
"{one | two} three"
```
=> Don't force a split inside of interpolated strings

src/runtime/string.cpp, src/runtime/value.cpp, src/runtime/value.h
Wake's `String` type internally maintains that its raw string pointer is a null terminated string so that the pointer may be used directly. However in some cases the internal pointer is filled manually outside of the class. In this case the author must remember to manually null  terminate the string or it will be inconsistent to various parts of the runtime. This may manifest itself as a segfault but may alternatively just be a string with a couple extra bytes at the end if a convenient NULL byte is nearby. 
This change fixes a case where the null terminator was forgotten but in the long term we should consider preventing this case all together by making the internal pointer read-only
=> Maintain `String` null termination invariant

src/runtime/job.cpp
Some compilation commands with a lot of library references, etc., can get untenably long and severely reduce the user experience of debugging failed jobs.  This replaces the unconditional command line printing in `getJobDescription` and thus in a number of error messages (`Non-zero exit status (Exited 1) for job 1855: '/usr/lib64/ccache/c++ -o bin/wake.native-cpp14-release src/compat/aligned_alloc.native-c11-release.o src/compat/mtime.native-c11-release.o [...] tools/wake/timeline.native-cpp14-release.o -std=c++14 -lpthread -Wl,--build-id -lncurses -ltinfo -lgmp -lsqlite3 -pthread -lre2 -lncurses -ltinfo -lsqlite3'`) with printing the label instead (`Non-zero exit status (Exited 1) for job 1855: 'link: c++ bin/wake'`); if no label has been set for a job (or if the label is `""`), it still …
=> Use a Label before the cmdline for describing Jobs

src/job_cache/daemon_cache.cpp, src/job_cache/daemon_cache.h, src/job_cache/eviction_policy.cpp, src/job_cache/job_cache.cpp, src/json/json5.cpp, src/json/json5.h, src/wcl/unique_fd.h, tools/wake/main.cpp
This change is an attempt to make log corruption due to concurrent writers less likely but it doesn't fully solve the problem. It does two things
1) It removes the biggest offender for large log lines
2) It makes sure that we write log lines in a single call to write (ignoring errors)
This should hopefully eliminate all of our log parsing errors...I should probably also make the log viewer handle corrupted lines better than by just failing on them but this PR doesn't do that yet.
=> Make JsonSubscriber more atomic

tests/wake-unit/stdout, tests/wake-unit/unit-test.sh, tools/wake-unit/diff.cpp, tools/wake-unit/fuzz_test_job_cache.cpp, tools/wake-unit/unit.cpp, tools/wake-unit/unit.h
This change adds a new kind of shared cache fuzz testing where the test harness will actively kill or briefly pause processes to test fault tolerance.
Additionally this change adds some long needed features to the unit testing framework to allow filtering of the tests that are run. You can now filter by test name prefix, or you can filter by tags. Any tests which matches any prefix will be considered for running and if no prefix is specified its as if the empty prefix was used so all tests are considered. Among considered tests only those tests who's tags are a subset of the ones the user specified will run. I've found these two controls to allow me to get almost any subset of tests I want to run to run.
@mmjconolly Your expertise is needed in reviewing the code for pid namespaces, …
=> Add chaos monkey style testing for shared caching

tools/wake-unit/fuzz_test_job_cache.cpp
https://github.com/sifive/wake/pull/1362 and https://github.com/sifive/wake/pull/1363 were incompatible together but passed CI separately. This broke the build on master, this change fixes the build.
=> build: Fix bad PR race between #1362 and #1363

src/json/json5.cpp, tools/wake-unit/filepath.cpp
I intentionally added un-checked writes to the system. These occur in single threaded instances where we can't block until they succeed, and we don't want to fail the whole system just because they fail, additionally if the log fails we can't log that fact because this *is* the logger and it would create a logger loop if we created an event that we also processed. We could add a tag to it to tell the json subscriber specifically to not process that event but it just gets complicated. So instead we just do the write (which should be a single atomic append) and we move on.
=> Fix unused warnings

tools/wake/main.cpp
This is the first PR of several being split out from  https://github.com/sifive/wake/pull/1364
This change profiles wake startup time and dumps it into `wake.log` so that optimizations can be verified.
In the long term, it would be interesting to build out some kind of macro or C++ template for a `ProfiledStep` that accepts a low cost function and wraps in it profiling but I don't think that is needed just yet
=> Profile wake startup times

build.wake, share/wake/lib/core/regexp.wake
Part two of splitting up https://github.com/sifive/wake/pull/1364
This change 
- removes more files from the  tarball that have snuck in over time
- uses globs  for exclusion instead of regexes
- prints the excluded files to `info`
=> Filter tarball files with globs; filter more files

tools/wake/describe.cpp
Fixes #1371 
When dumping a script with  `wake -o blah.txt -s`  tags are not commented out. This change fixes that
```
$ wake-o out.txt -s
#! /bin/sh -ex
cd a/path/here
env -i \
PATH=/usr/bin:/bin \
TERM=xterm-256color \
/usr/bin/dash \
-c \
'echo '\''a b c'\'' > out.txt' \
< /dev/null
```
=> db: Emit # before tags in script

src/runtime/sources.cpp
Our previous implementation of `find_all_sources` would use `git ls-files`  non-recursively requiring the exploration of every directory in the workspace which is slow on very large projects.  
This change now relies on `git ls-files --recurse-submodules` to report files in sub modules which drastically reduces the number of inodes that must be explored.
=> Determine source files from recursive `git ls-files`

.github/workflows/build.yaml, Makefile, build.wake, extensions/vscode/vscode.wake, src/job_cache/daemon_cache.cpp, src/job_cache/daemon_cache.h, src/job_cache/eviction_policy.cpp, src/job_cache/job-cache.wake, src/job_cache/job_cache.cpp, src/job_cache/job_cache.h, src/job_cache/job_cache_impl_common.cpp, src/job_cache/job_cache_impl_common.h, src/job_cache/message_parser.h, src/job_cache/message_sender.h, src/util/poll.cpp, src/util/poll.h, src/util/util.wake, tests/job-cache/basic-fetch/pass.sh, tests/job-cache/basic-lru/pass.sh, tests/job-cache/dup-output/pass.sh, tests/job-cache/overwrite-smaller/pass.sh, tests/job-cache/symlink-dir/pass.sh, tools/wake-unit/fuzz_test_job_cache.cpp, tools/wake-unit/unit.cpp
This is a rather massive change to the shared cache. It doesn't change the protocol, the directory layout, the read or write implementations etc... but it changes the nitty gritty specifics of how messages are sent/received and how blocking is handled. Specifically the following changes have been made It should be impossible for a colleciton of clients and a daemon to deadlock now because neither side ever blocks and there's no shared state between the two sides. Additionally connection closing happens much more aggressively to simplify functionality. This is all in the name of stopping deadlock from occuring.
This change also adds tests that combine large messages with parallelism which is where I think the bug was hiding previously but I've yet to run those tests on a previous commit to …
=> Switch shared cache comunication over to non-blocking io

.github/workflows/build.yaml, Makefile, src/runtime/gc.h, src/runtime/status.cpp, src/util/poll.cpp, tools/fuse-waked/fuse-waked.wake, vendor/gmp.wake, vendor/ncurses.wake, vendor/sqlite3.wake
The wake-wasm target was never actually used and now it is blocking shared caching in a non-trivial wake. Because of this, remove it.
=> Remove support for wake wasm target

src/job_cache/daemon_cache.cpp, src/job_cache/message_parser.h, src/job_cache/message_sender.h
In the previous non-blocking io change I forgot to evict clients that had timed out. This wound up not mattering much but I think its a good feature to keep in mind. All tests still pass.
=> Remove clients that have timed out

tests/wake-format/basic/basic.wake, tests/wake-format/basic/simple.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp, tools/wake-format/emitter.h
When a comment is inside a paren which is inside a def (see below) there are zero matching rules. 
```
def x _ =
def (
A # test
b
) =
c 
b
```
because the comment requires exploding but `CST_DEF` disallows it. This change make it so `CST_DEF` allows explode only for `CST_PAREN`
=> Fix case where certain defs matched zero rules

src/parser/wakefiles.cpp
https://github.com/sifive/wake/pull/1364 allowed wake files to be explicitly listed via a manifest file. These paths were directly returned to the calling function.
For `wake` this is always correct as the wake tool will `cwd` into the workspace before calling the function. This means that the relative paths returned are correct.
However `lsp-wake` doesn't `cwd` into the workspace and instead relies on absolute paths. When a relative path is returned it assumes it is absolute then fails to find the file later.
This change fixes the broken invariant that the paths returned from `find_all_wakefiles` must be directly readable given the callers cwd.
=> parser: Correctly handle paths when using manifest

src/job_cache/daemon_cache.cpp, src/job_cache/job_cache.cpp, src/job_cache/job_cache_impl_common.cpp, src/runtime/job.cpp, src/wcl/tracing.cpp, src/wcl/tracing.h
This change just tweaks logging in lots of small ways
1) We add a bunch of before/after logging of important events in order to better understand if a hang is occuring and if so to help pin down where
2) I removed a debug line printing out the full message
3) We log before and after comunication with the eviction loop in case that ever hangs
4) We log when a job statrts and when it ends so we can detect job hangs
5) hostnames are always added so that logs can be collated across multiple machines
6) We now print out if a message received was a cache hit or not.
=> Improve logging yet again, focusing on hangs, and distributed case

build.wake, rust/log_viewer/build.wake, share/wake/lib/gcc_wake/pkgconfig.wake, share/wake/lib/rust_wake/cargo.wake, share/wake/lib/system/job.wake, share/wake/lib/system/path.wake, src/job_cache/job-cache.wake, tests/tests.wake, tests/wake-format/basic/stdout, tools/lsp-wake/lsp.wake, tools/wake-format/emitter.cpp, tools/wake-format/wake-format.wake, vendor/git.wake
Trailing unary comma now tells the formatter to newline a list. 
Ex:
```
def x = a, b, c,
```
becomes 
```
def x = 
a,
b,
c,
```
instead of being flat.
This is something that @ag-eitilt and @bmitc have been asking for for awhile and I think its a good tradeoff now that I've seen a bunch of use cases in internal repos that would either use this or `# wake-format off`
=> Require explode when a binop ends with a unary comma

README.md, share/wake/lib/system/job.wake, src/job_cache/job_cache.cpp, src/runtime/config.cpp, src/runtime/config.h, src/runtime/job.cpp, tests/config/nominal/pass.sh, tests/config/nominal/stdout, tests/job-cache/basic-fetch/pass.sh, tests/job-cache/basic-lru/pass.sh, tests/job-cache/dup-output/pass.sh, tests/job-cache/overwrite-smaller/pass.sh, tests/job-cache/symlink-dir/pass.sh, tools/wake/cli_options.h, tools/wake/main.cpp
This change does the following
1) Declares the wake shared cache no longer experimental and changes the env-var used for it to be WAKE_LOCAL_JOB_CACHE
2) Adds the ability to configure some config options via environment variables. In particular the user config can now be specified via an env-var which allows for greatly increased flexibility. I did however additionally allow env-vars for cache miss on failure, and cache size manipulation in case that's helpful but we anticipate only
3) I went ahead and added a command line override for user-config so that you can locally fix what might become a shell-global override of .wakeroot
=> Shared cache env-var tweaks

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
When `# wake-format off` turns off formatting for a CST_BLOCK it would ignore any further `# wake-format off`s in the same CST_BLOCK. Update it so it works correctly.
Given
```
def a =
def b =
1+2
def c =
3+5
5
```
Old
```
def a =
def b =
1+2
def c = 3 + 5
5
```
New
```
def a =
def b =
1+2
def c =
3+5
5
```
=> wake-format: Fix format off failure in certain cases

src/job_cache/daemon_cache.cpp, src/job_cache/daemon_cache.h, src/job_cache/job_cache.cpp, src/job_cache/job_cache.h, src/runtime/config.cpp, src/runtime/config.h, tests/config/empty/stdout, tests/config/extra_keys/stdout, tests/config/missing_user_config/stdout, tests/config/nominal/stdout, tests/config/nominal/wake_user.json, tools/job-cache/main.cpp, tools/wake-unit/fuzz_test_job_cache.cpp, tools/wake/main.cpp
This change adds the WAKE_BULK_LOGGING_DIR environment variable. If turned on, wake will emit a copy all logs to that directory, with each file having its hostname, pid, the current day as part of the file name. This ensures that even over NFS, logging should stay atomic. NFS has no append atomicity but because wake is single threaded and the pid and hostname are included things should be atomic.
The day in the file name is mostly so that tools and scripts for parsing logs can pre-filter the logs they want to view based on the time frames without parsing all of the logs. In theory if a multi-day process is running on the same host with the same pid, or a pid gets recycled some days later this would also be midly helpful but those are quite rare cases.
Log cleanup can be done by deleting …
=> Add bulk logging env var for wake

share/wake/lib/system/job.wake
We agreed on the following changes for runOnce
1) The visible list should cause a re-run. This will what is today a warning into an error that says that two different jobs had the same output rather than saying that the same job was requested with different auxiliary params
2) Likewise, isatty was always supposed to be part of the primary key and is considered as such in the database already
3) If a different runner is used, the behavoir of the program will change accordingly so this is now part of the primary key of runOnce.
=> Cleanup what runOnce considers as required for re-run

src/parser/wakefiles.cpp, tools/wake-format/main.cpp
Previously `ok` is uninitialized and never set to true on success.  If the underlying memory happened to be set to `0` then it would incorrectly report a failure even though none had occurred. Set the default to true to avoid that case
=> Fix wake-format find_all_files flake 

share/wake/lib/core/syntax.wake, share/wake/lib/system/job.wake, share/wake/lib/system/path.wake, src/runtime/exception.cpp, tools/wake-hash/main.cpp
Recently we've had a lot of issues with people seeing error messages like this:
```
UNREACHABLE: wake hash expected X lines but received Nil
```
This isn't really unreachable if you hit some sort of issue with fnoutputs however but previously this code assumed that no such issues would ever occur (this is manifestly false).
To fix this I do the following
1) If the exit code of wake-hash is non-zero for any reason all hashed files from that job are considered BadHash and will thus later trigger a failure when `getJobOutputs` is called but the error will not point blame at wake-hash and will instead just say that it couldn't hash some random file (which one is chosen is up to which BadHash is checked first)
2) If any specific file cannot be hashed, wake-hash will return BadHash for it and …
=> Improve wake-hash errors

share/wake/lib/system/job.wake, tests/tests.wake
This change makes it so that getJobStdout and getJobStderr first check the job status before returning a Pass, and return a Fail if its non-zero.
To match the old behavoir getJobFailedStdout and getJobFailedStderr were added.
=> Make getJobStd{err,out} check job status before returning

src/job_cache/types.cpp, tests/job-cache/basic-lru/pass.sh, tests/job-cache/runner-hash/.wakeroot, tests/job-cache/runner-hash/pass.sh, tests/job-cache/runner-hash/some-input.txt, tests/job-cache/runner-hash/test.wake
The runtime has an accounting bug regarding the wakelang provided `runner_hash`. This lead to situations where wakelang would correctly declare two jobs as different yet the shared cache would still see them as identical.
This bug caused some jobs to resolve with stale/incorrect outputs.
The accounting error has been corrected and a test case was added that ensures a change in the runner hash results in a cache miss.
=> cache: Fix bug in runner hash accounting

src/runtime/regexp.cpp
The output array from which we construct the token list in prim tokenize was incorrectly allocated. This switches it to use a vector instead. This issue was never seen before because no one tried to do a split this big until now apparently. A user encountered this issue in the wild and I'm still not 100% sure that this will resolve their issues but I'm going to try that next.
=> Fix tokenize segfault when too many tokens are output

share/wake/lib/core/double.wake, share/wake/lib/core/order.wake, share/wake/lib/core/tree.wake, tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/actions.h, tools/wake-format/emitter.cpp, vendor/git.wake
When parsing a TOKEN_COMMENT node everything until a newline (including trailing whitespace) gets slurped into the 'contents' of the comment. We don't want to re-emit this whitespace so it has to be manually removed when emitted comments.
An alternative implementation would be to manually edit the CST after parsing to remove trailing whitespace from any TOKEN_COMMENT node but editing the CST seems ill advised if its even possible.
=> Delete spaces trailing after a comment

src/parser/wakefiles.cpp, src/parser/wakefiles.h, tools/lsp-wake/astree.cpp
When editing wake code with a running LSP an author may end up in a position where a file exists in the editor but not on disk. (rename or unsaved new file) that they then (correctly) add to the `.wakemanifest` file. This creates an issue where to the user the file exists but to wake source discovery it doesn't. When source discovery sees a file listed that doesn't exist it will exit with an error which is correct for wake, but not the LSP. 
This change adds a strict flag to source discovery that the LSP can set to false. This allows the LSP to keep going even if the manifest doesn't fully agree.
In the long term, we should do a better job of managing the source lifetime within the LSP and we should report the missing file as an LSP notification but that change will be difficult without a …
=> Don't exit LSP when manifest error occurs

src/job_cache/daemon_cache.cpp, src/job_cache/schema.sql
This change adds a create time for jobs in the job cache which will invalidate the schema. This will be needed both to implement the TTL eviction policy and to implement the needed fixes to the LRU eviction policy so it seems an easy thing to jsut go ahead and add.
=> Adding create time for jobs in job cache

share/doc/wake/tutorial.md
This fixes `makePlan` usage and description in the tutorial.
As a side note, running this on a popular system I get the following error message:
```
Fail (Error "No GitHub releases found for sifive/wake" Nil)
```
Which is a result of the fetched `releases.json` having these contents:
```
{"message":"API rate limit exceeded for 1.2.3.4. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```
=> fix makePlan examples in the tutorial and description

src/runtime/database.cpp, src/runtime/database.h, tools/wake/main.cpp
This is the second PR on the path to  tag inspection of the database. After this PR any inspection flag that accepts a parameter can use the glob operators `*` and `?` as expected.
Example:
`wake --input "*.c" --output "*.o" --job "???"`
which says match any job that takes a `c` file as input,  outputs an `o` file, and has a 3 digit job id
=> Support globbing for all param based inspection

src/wcl/iterator.h, tests/wake-unit/stdout, tools/wake-unit/iterator.cpp
Implements and tests a split-by function for exploding something iteratable (usually a string) into parts over a  delimiter
=> Add split_by to wcl

tools/wake/cli_options.h, tools/wake/main.cpp
Improves/increases the types of queries that can be spelled out with the db inspection subsystem.
The syntax is as follows
- repeating a flag is intersection
- `,` in a flag unions the parts (`,` can be repeated for multiple parts)
- `*` matches 0 or more  of any character
- `?` matches exactly 1 of any character
Example
`wake --job "5??,6??" --label "*c++*" --label "*.c" --output "*.o"` is
- AND
- label contains `c++`
- label ends with `.c`
- job output a file ending in `.o`
- OR
- job id is 3 digits starting with 5
- job id is 3 digits starting with 6
=> Add support for complex intersection/union filters

share/wake/lib/system/io.wake
In trying to debug an odd `write` job, @maniltongya and I couldn't find where it was being called despite what seemed like a very unique `420` mode being printed in the job metadata.  I eventually realized that was being printed as *decimal* instead, and was the much more typical `0644`.  This PR still doesn't help us find where the offending `write` is happening, but it will at least avoid the same confusion over what's being set.
This and `mkdirImp` seem to be the only jobs which specify the mode, and that one already uses the proper base.  There shouldn't be any issue with updating this (beyond all `write` jobs having to be rerun) as the actual `prim` call never interacts with the label/cmdline, and a very simple `wake -x 'write "tmp.txt" "Test"'` shows everything being correct.
=> Identify `write` job with mode as octal, not decimal

share/wake/lib/core/result.wake, share/wake/lib/system/io.wake, src/runtime/string.cpp
This change adds a fast way to get the following information for a file that's already been hashed
1) inode permissions (e.g.
2) inode type (e.g. regular file, symlink, directory, or something more exotic like a pipe or socket)
3) file size
This is exposed via a new function in the standard library called "stat" that returns a `Result Stat Error` which in turn (if its a Pass) contains that information.
Other information contained in the posix stat struct is volatile and inconsistent across machines so I did not add it but these should be relatively stable.
=> Add primitive for stat to avoid a job or string parsing

src/runtime/database.cpp, src/runtime/database.h, tools/wake/cli_options.h, tools/wake/describe.cpp, tools/wake/describe.h, tools/wake/main.cpp
Implements database inspection for filtering on tags. Using the same semantics as all other filters except that two values are provided with a `=` between them. `--tag a=b` filters for all tags where the URI is `a` and the content is `b`. `*` and `?` work as expected.
=> Implement tag filters for database inspection

src/runtime/database.cpp
This change removes the `filesearch` index which was previously being used by the query to find jobs that output a particular file. We have sense opted to search for those files via a glob instead which means that the index is no longer being used. For jobs that output/input huge numbers of files, this index can take up to about 1/3rd of the database size. Given that we're not actually using it this PR deletes it.
The schema remains compatible but if we do not explicitly add a "drop index if exists" the index will keep existing in people's databases. I considered bumping the schema version but I think using drop index if exists acts as an effective migration. If an older version of wake is used after a newer version, it will re-build the index. If a newer version of wake is used after an …
=> Remove filesearch index

src/job_cache/daemon_cache.cpp
If the daemon is killed by an external agent at *just* the right time, there's a about a 1/1000 chance that it will happen between the creation of a temp file and the rename. This will leave a temp file sitting around. This on its own is not really a problem. The temp file can be confusing to debug the existence however and if you have tools in place to track that cleaning your workspace actually cleans everything, this will trigger that check.
A full solution would be to have the client copy out of the cache instead of having the daemon do the copy. But even that might leave temp files sitting around that you might not want. To combat this we need to tag these files so that such a tool can identify them. Later we will move the copy to the client where the odds of this sort of thing …
=> Tag temp files created by the shared cache

src/job_cache/daemon_cache.cpp
I made a mistake in the previous TTL eviction commit and logged this info incorrectly. This PR fixes it
=> Fix LRU logging info

src/runtime/database.cpp
This reverts commit a964d7fd28dd581bc8ee3931db0fca2e3b01a77d  which introduced a significant performance regression to `db.clean()`
=> Revert "Remove filesearch index (#1457)"

rust/rsc/src/rsc/add_job.rs
Previously we were making a query per file entry in add_job. Now we always make a constant 5 queries on add_job
=> Optimize ORM insert queries

rust/rsc/src/rsc_tool/main.rs
Fixes the ArgParser for api key creation. Originally authored by @JakeSiFive
=> rsc: Fix api key creation for rsc_tool

rust/entity/src/job.rs, rust/entity/src/job_use.rs, rust/entity/src/mod.rs, rust/entity/src/prelude.rs, rust/migration/src/lib.rs, rust/migration/src/m20231127_232833_drop_use_time.rs, rust/migration/src/m20231128_000751_normalize_uses_table.rs, rust/rsc/src/rsc/read_job.rs
Last bit of tech debt cleanup before digging in to new feature work.
- Removes `time` from `JobUses` now that its covered by `CreatedAt`
- Renames `JobUses` to `JobUse` to match all other models.
=> rsc: Paydown JobUse tech debt

src/job_cache/job_cache.cpp, src/job_cache/job_cache.h, src/runtime/config.cpp, src/runtime/config.h, tests/config/empty/stdout, tests/config/extra_keys/stdout, tests/config/missing_user_config/stdout, tests/config/nominal/.wakeroot, tests/config/nominal/stdout, tools/wake-unit/fuzz_test_job_cache.cpp, tools/wake/main.cpp
This change adds the ability to adjust timeout configs because its hard to find a one size fits all solution. I think we can probably lower our number of read failures from 300 to 20 by default which would help a lot, but we can also lower these other ones sometimes. complete read failures that are recovered from are quite rare but they do happen. In practice we only seem complete read failures that recover at most about 3 times per wake run so 20 is a good upper bound compared to 300 in practice.
=> Add timeout configs

src/runtime/string.cpp
Whose bright idea was it to make the syscall you use to check the type of a path, *not* actually check the type of all paths, and instead hide the uniform behaviour behind a one-letter difference?
Regardless, the `stat` function was previously returning `PathTypeRegularFile` (and permissions/size of the target file) when called on symlinks.  It now returns `PathTypeSymlink` (and less helpful but more accurate permissions/size).
=> Make `stat` actually recognize symlinks

share/wake/lib/system/io.wake
These had always been intended to be exported, but Wake's tuple visibility marking is a bit confusing.
=> Export `Stat` tuple accessors

src/job_cache/daemon_cache.cpp
Previously we (unintentionally) would open the database BEFORE inquiring the cache lock. The vast majority of the time this is harmless because we connect to the database with randomized exponential backoff and sqlite3 does a good enough job at this with this back off strategy. Later once the cache fails to aquire the cache lock the connection is closed and no harm was done. However it can get overwhelmed and cause issues. The solution is simple, just move the lock acquire to be first like it should have always been.
=> [LSC] Aquire daemon lock before opening db

rust/rsc/Cargo.lock, rust/rsc/Cargo.toml, rust/rsc/src/common/config.rs, rust/rsc/src/rsc/blob.rs, rust/rsc/src/rsc/main.rs, rust/rsc/src/rsc/types.rs
This change introduces two new routes.
1) `GET /blob` which returns the url that blobs should be POSTed to
2) `POST /blob` which right now accepts a blob and writes it to the location specified by `config.local_store`. 
The POST route isn't complete since the blobs should be tracked in a blob database and a detailed response should be given to the client however that is a sizable chunk of work and so I wanted to split  the review into two parts. This one that handles file upload, and the next one that handle blob tracking.
Future work will be to support multiple backing stores so the routes are being implemented with that in mind.
=> Add basic implementation of blob upload

rust/rsc/src/rsc/blob.rs, rust/rsc/src/rsc/main.rs
This changes the BlobStore trait to be object safe while maintaining most of the generality of the previous implementation.
=> Use Arc dyn BlobStore insteadl of impl

rust/rsc/src/rsc/blob.rs, rust/rsc/src/rsc/main.rs, rust/rsc/src/rsc/read_job.rs, rust/rsc/src/rsc/types.rs
`POST /blob` has been updated so that it now creates a database entry for each blob when it has been uploaded and returns it back to the client.
The ids returned back to the client are mapped using the client provided names.
Example response
```
HTTP/1.1 200 OK
content-length: 125
content-type: application/json
date: Fri, 15 Dec 2023 21:39:37 GMT
{
"blobs": [
{
"id": 1,
"name": "foo"
},
{
"id": 2,
"name": "bar"
},
{
"id": 3,
"name": "bat"
},
{
"id": 4,
"name": "bazz"
}
],
"type": "Ok"
}
```
=> rsc: Track blobs in the database

src/job_cache/job_cache.cpp
I'll start out by saying, I'm not a fan of this PR but I was just noodling on what we could do to help with this problem if it occurs in the future. Ideally we'd having a polling mechanism here but at this moment I'm not at all sure how to do that. It appears to me that Tokio and mio have solved this problem somehow so I think there's a better solution out there. This change does not eliminate the core issue like the previous PR did and because it at best reduces spurious daemon launches by 2x it doesn't eliminate DoS-ing yourself by spamming wake invocations, it just reduces the impact a little bit...I'm gonna put this up and see what people think but I'm rather on the fence about landing it.
=> Poll shared cache connect

src/job_cache/job_cache.cpp
This change just makes it so that no attempt is made whatsoever after the failure cap is reached, this includes add.
As a toss in I also fixed add not using the config.
=> Do not use cache after the failure cap is reached

src/job_cache/daemon_cache.cpp, src/job_cache/daemon_cache.h, src/job_cache/eviction_policy.cpp, src/job_cache/eviction_policy.h
This change eliminates the eviction process which is now quite apparently an over optimization IMO. With this new change there will be small pauses in wake here and there while the eviction tasks are occurring but on the plus side we now have a single DB connection, guarded by a file system lock, per cache.
Additionally I spotted a couple cases where I was improperly using the database on two separate threads which is a big no no for SQLite and may have been causing some of our issues. I've removed those at additional cost (but it should be a small cost).
With these changes things should be both easier to debug, and possibly more stable.
And remember kids, friends don't let friends write multi-threaded C++ code when Rust is an option ;)
=> Eliminate eviction process; use same connection

rust/entity/src/api_key.rs, rust/entity/src/blob.rs, rust/entity/src/blob_store.rs, rust/entity/src/job.rs, rust/entity/src/job_use.rs, rust/entity/src/local_blob_store.rs, rust/entity/src/output_dir.rs, rust/entity/src/output_file.rs, rust/entity/src/output_symlink.rs, rust/entity/src/visible_file.rs, rust/migration/src/m20220101_000001_create_blob_tables.rs, rust/migration/src/m20220101_000002_create_table.rs, rust/migration/src/m20230706_104843_api_keys.rs, rust/migration/src/m20230707_144317_record_uses.rs, rust/rsc/src/rsc/blob.rs, rust/rsc/src/rsc/blob_store_service.rs, rust/rsc/src/rsc/main.rs, rust/rsc/src/rsc/read_job.rs, rust/rsc/src/rsc/types.rs
This change is updates all models/tables to use UUIDs. This is important for concurrently/db destruction/multi-client as we can't guarentee that two different clients won't ever get the same integer id representing 2 different jobs. With this change, even if bad db stuff happens we ensure running clients don't confuse jobs as every new job will always get a unique id regardless of the previous state of the db. 
It properly generates new UUIDs by default but it takes a hard dependence on Postgres. To land this PR we would have to drop sqlite3 support which has now been completed.
This change rewrites history but we just did that in the last PR so might as well get them all in at once
The standalone tests have been updated and now properly use a sandboxed postgres
=> rsc: Basic attempt at uuid as id

tools/wake-format/main.cpp
Currently setting `libdir` to `.` causes the code to operate as if no manifest is present because `find_external_stdlib_files` searches libdir and finds all wakefiles regardless of their presence in the manifest.
This behavior does not match the claim of `--auto` which is that is "matches wake discovery".
There is probably some alternative implementation that inlines this finding of the standard libdir but its a little complicated because the lsp's call has an extra level of directories for some reason.
```
$ rg -i "make_canonical.*execpath.*lib\""
tools/lsp-wake/main.cpp
325:    std::string stdLibPath = wcl::make_canonical(find_execpath() + "/../../share/wake/lib");
tools/wake-format/main.cpp
205:    std::string libdir = wcl::make_canonical(find_execpath() + "/../share/wake/lib"); …
```
=> Update wake-format's search libdir to match wake's libdir

rust/rsc/src/common/config.rs, rust/rsc/src/rsc/blob.rs, rust/rsc/src/rsc/blob_store_service.rs, rust/rsc/src/rsc/main.rs, rust/rsc/src/rsc/read_job.rs, rust/rsc/src/rsc/types.rs
Blobs returned to the client via a matching jobs now resolve and return the URL where that blob can be downloaded from.
Example:
```json
{
"cputime": 1.0,
"ibytes": 100000,
"memory": 1000,
"obytes": 1000,
"output_dirs": [],
"output_files": [
{
"blob": {
"id": "4ad74b40-4a3f-4464-a488-77f6297c8121",
"url": "file:///foo/bar/remote_cache_local_store/57KcxXl4PxMyjPcZIRJvDw=="
},
"mode": 0,
"path": "foo"
}
],
"output_symlinks": [],
"runtime": 1.0,
"status": 0,
"stderr_blob": {
"id": "5bfb8a97-c244-4241-a091-5aa3388c20eb",
"url": "file:///foo/bar/remote_cache_local_store/X1MS-Semg55oqRF3U9LAYA=="
},
"stdout_blob": {
"id": "4ad74b40-4a3f-4464-a488-77f6297c8121",
"url": "file:///foo/bar/remote_cache_local_store/57KcxXl4PxMyjPcZIRJvDw=="
},
"type": "Match"
}
```
=> rsc: Resolve Blobs on request

tools/wake/main.cpp
During the database inspection refactor job ordering for inspection responses was lost. This is confusing and actively unhelpful when debugged troublesome builds.
This PR restores the previous functionality
=> db: Order job queries by job id

tools/wake-format/main.cpp
Reverts sifive/wake#1504
While this PR is correct, it reveals a previously hidden bug. We should circle around to fixing that but other key bug fixes need to go in asap
=> Revert "Update wake-format's search libdir to match wake's libdir"

share/wake/lib/system/sources.wake
We generally don't want to promote `claimFileAsPath` on external files as it makes builds harder to reproduce (though it does still maintain cache safety), but when people *do* use it to copy files, trying to claim a read-only file would previously work in the first invocation but fail in the second due to not being able to overwrite the previous result.  This sets the permissions on the resulting file to close that hole in invocation-level reproducibility.
Of note, the file permissions are already subject to a bit of semantic change, as `cp`[^1] sets the owner of the new file to the user+group who ran the command; in the odd case of 0477 permissions, assuming the file was originally owned by a different user, by running `claimFileAsPath` with the old implementation the user would …
=> Ensure copied file from `claimFileAsPath` is writable

tools/bsp-wake/main.cpp, tools/wake/cli_options.h, tools/wake/describe.cpp, tools/wake/describe.h, tools/wake/main.cpp
`--tag` was changed to be more flexible and filterable in #1454 however bsp-wake depended on the previous functionality.
This PR adds a new flag `--tag-uri` that acts like `--tag` used to and updates bsp-wake to use it
=> bsp: restore --tag functionality for bsp-wake

.github/workflows/build.yaml, .github/workflows/dockerfiles/alpine, .github/workflows/dockerfiles/centos-7.6, .github/workflows/dockerfiles/debian-bullseye, .github/workflows/dockerfiles/fedora-38, .github/workflows/dockerfiles/rocky-8, .github/workflows/dockerfiles/rocky-9, .github/workflows/dockerfiles/ubuntu-22.04, .gitignore, .wakemanifest, build.wake, rust/log_viewer/build.wake, rust/rsc/postgres-tests.wake, rust/rsc/rsc.wake, rust/rsc/src/rsc/blob.rs, rust/rsc/src/rsc/blob_store_impls.rs, rust/rsc/src/rsc/blob_store_service.rs, rust/rsc/src/rsc/main.rs, rust/rsc/vendor-config.toml, share/wake/lib/core/syntax.wake, share/wake/lib/rust_wake/cargo.wake, tools/wake-format/emitter.cpp, wake.spec.in
This PR does a few subtle things, but all in the same vein. The old version of the RSC unit test was both annoying to run locally and also always returning a pass regardless of the result. This is a perfect combination to result in the tests breaking immediately. The goal of this PR is to generally address that 
1) A failing test now actually fails CI
2) The tests have been updated to pass again
3) I've changed how rust tests are handled/built which makes is way less annoying to run the tests locally
4) The previous item also simplifies CI quite a bit so now unnecessary things have been removed
5) As a bonus from 3, rsc and rsc tool are now built as installed as part of the wake install flow
=> rsc: Improve rust build api, fix rsc test, fix rsc test framework

rust/migration/src/m20220101_000001_create_blob_tables.rs, rust/rsc/src/common/database.rs, rust/rsc/src/rsc_tool/main.rs, rust/rsc/src/rsc_tool/table.rs
This is a somewhat chunky refactor of the `rsc_tool` to enable and support various database bootstrapping processes.
An example of a first-time configuration of a new rsc server may look like the following
```sh
$ rsc_tool add api-key --desc "API key for foo.ci.com"
Created api key: 8f0eac7e-edc7-427b-83f9-a4171b722e33
$ rsc_tool add local-blob-store --root /some/valid/path
Created local blob store: 94e2f4aa-2188-4368-8d99-c33117762c71
```
The main goal of rsc_tool is to be used directly by engineering and support teams to spin up and manage the server.
This PR also add `rsc_tool remove danger-jobs-all` which will delete all jobs from the database. It is primarily used as a development tool but in case of an aggressively poisoned cache it may be useful as a parachute. Risk of accidentenal …
=> rsc_tool: Structure tool to support model bootstrapping

share/wake/lib/system/io.wake
`unsafe_stat`: `stat` but doesn't require path. Needed by the cacheRunner to stat a file before it can be elevated into a Path
`writeTempFile`: writes a file from a string. Useful for jobs/tools that require a file as input. Filenames are generated from the hash of the content and duplicate content is de-duplicated therefore guarantees to never raise the `file output by multiple jobs` error
=> stdlib: Add unsafe_stat and writeTempFile to io.wake

.github/workflows/build.yaml
This PR disables the now failing alpine test. For now we will continue to ensure that it builds.
This is not a change in policy as alpine has not been officially supported or released for over 1.5 years. See: https://github.com/sifive/wake/releases/tag/v0.28.5
=> ci: Don't test alpine builds

rust/rsc/src/rsc/blob.rs, rust/rsc/src/rsc/blob_store_impls.rs, rust/rsc/src/rsc/main.rs, rust/rsc/src/rsc/read_job.rs
For small enough blobs, the overhead of writing out to disk/a second provider isn't worth it. This PR allows the client to opt in to storing certain blobs directly in the database. This is primarily useful for the empty blob but will also be useful for other small blobs.
Clients can opt in by setting the content type of the mutipart part to `"blob/small"`. Right now only blobs up to 100 bytes are allowed but there isn't a strong reason (other than de-duplication) to let the client arbitrarily defined what small is.
When a small blob is resolved by the server, its contents are directly returned as the blob url using standard `%BYTE%BYTE` url encoding. the schema `db://` can be used to detect this.
=> rsc: Support database backed blobs

share/wake/lib/system/job_cache_runner.wake
The jobCacheRunner was caching the filtered output when writing to the cache, it should instead be caching the raw output. This PR fixes that.
=> lsc: Fix incomplete capture of job output

rust/entity/src/job.rs, rust/entity/src/visible_file.rs, rust/migration/src/m20220101_000002_create_table.rs, rust/rsc/src/rsc/add_job.rs, rust/rsc/src/rsc/main.rs, rust/rsc/src/rsc/read_job.rs, rust/rsc/src/rsc/types.rs
- Changes job's `cmd` from a string to a vector of bytes as multipart commands are delimited with `\0` which is not valid in rust strings
- Changes visible_file's `hash` from a vector of bytes to a string as that is a much simpler representation for the client to construct.
=> rsc: Update api types to align with client expectations

share/wake/html/timeline_main.js, src/runtime/database.cpp, src/runtime/database.h, tools/wake/cli_options.h, tools/wake/describe.cpp, tools/wake/describe.h, tools/wake/main.cpp
Adds a `--simple-timeline` flag similar to `--timeline` with  most of the data removed to generate a much smaller timeline file.
Keeps cmdline, label, job id, start time, and end time. All other info should be pulled from more targeted/filtered timeline files
=> db: Add simple timeline rendering

rust/rsc/src/rsc/main.rs, share/wake/lib/system/http.wake, share/wake/lib/system/remote_cache_api.wake
Fixes a few small rsc bugs:
- Large JSON body requests would fail to launch from the client due to linux's max character len for a command
- Large requests would fail to be accepted by the server due to max request size limits
- Filenames were not shell escaped and so things like `$` would be incorrectly resolved to shell values
=> rsc: Fix large uploads and unescaped paths

share/wake/lib/system/remote_cache_api.wake, share/wake/lib/system/remote_cache_runner.wake
Setting `DEBUG_WAKE_REMOTE_CACHE` env var now emits debug information to `wake.log` and `<wakeroot>/.build/tmp/writes` to more easily debug and inspect the client side of the cache interactions.
=> rsc: Emit debug information when env set

rust/entity/src/output_symlink.rs, rust/migration/src/m20220101_000002_create_table.rs, rust/rsc/src/rsc/add_job.rs, rust/rsc/src/rsc/read_job.rs, rust/rsc/src/rsc/types.rs, share/wake/lib/system/remote_cache_api.wake, share/wake/lib/system/remote_cache_runner.wake
This PR adds support for jobs that output directories or symlinks which is necessary to support much more complex builds than what the wake repo itself tests.
Now when a job creates a symlink, the output pulled back out of the cache will be put back on disk as a symlink. 
This change forces more ordering (and thus less parallelism) as a directory needs to be created before any output files are put into it and a symlink needs be created after all files have been saved to disk in case the symlink references a file output by the job
=> rsc: Add support for output directories and symlinks

rust/rsc/src/rsc/main.rs, share/wake/lib/system/remote_cache_runner.wake
The following bugs are fixed in this PR
- Logging is temporarily disabled due to spammy logs creating a 2x slowdown
- Output files were previously being written to the wrong location when the Plan directory was changed
- Symlink content is now entirely defined by the content of the link, not a vague notion of the source path
- Symlinks would fail if a symlink was left on disk from a previous build
- The source path of the symlink was being returned as the output instead of the symlink itself
- Symlinks no longer wait for all files to download as it's not necessary
With these changes larger internal builds will complete successfully
=> rsc: Implement several bug fixes

rust/rsc/Cargo.lock, rust/rsc/Cargo.toml, rust/rsc/src/rsc/add_job.rs
The version of `sqlx` we depend on has a max of 65536 parameters. When calling `insert_many` each model contributes several parameters (5-6). In cases of very large jobs we need to split the `insert_many` into several queries to stay under the max.
=> rsc: Chunk insert_many to avoid max param count

rust/rsc/src/common/database.rs, rust/rsc/src/rsc/main.rs, rust/rsc/src/rsc_tool/main.rs
`rsc_tool --bootstrap` now completes all tasks needed to bootstrap an empty but migrated postgres database. This includes supporting DbOnly Blob Store which was previously under supported. There is now only one place where the DbOnly Blob Store id is hard coded.
=> rsc: Update the tool to fully bootstrap a fresh db from one command

share/wake/lib/system/remote_cache_api.wake
There is a window of time where interrupting the fixup script will leave it on disk but with the wrong permissions which may interfere with later invocations of wake. Use `mv` + a temp file to atomically put the file on disk.
=> rsc: Use mv to atomically fixup files

rust/rsc/src/rsc/main.rs, share/wake/lib/system/remote_cache_api.wake
Add the route `POST /auth/check` which returns `200` on valid auth key and `401` on invalid auth key. It will be used as an early warning to actors they they may have incorrectly specified their auth key when connecting to the rsc
=> rsc: Add route to check for valid api key

rust/rsc/src/rsc/main.rs, share/wake/lib/system/remote_cache_api.wake
Creates `GET /version/check` which a client can use to see if the server declares compatibility with the it. The server doesn't enforce anything based on the result but a client should expect issues if it continues to interact with the server when incompatible.
=> rsc: Add client-server compatibility check

share/wake/lib/system/remote_cache_api.wake, share/wake/lib/system/remote_cache_runner.wake
Since the `localRunner` job don't report their inputs/outputs to the wake runtime they must rerun once any time the are encountered in a given invocation. Otherwise errors can occur where their outputs are missing and wake doesn't know how to recreate them.
Its not possible to teach wake about the inputs/outputs as that would cause the cached jobs to encounter "file output by multiple jobs" error.
However its totally acceptable for these to rerun since they are only requested from the runner when they aren't already in the local `wake.db`. If a job is in the db then wake won't try to reach out to the cache for it so the jobs don't unnecessarily rerun.
=> rsc: Don't cache the cache infra jobs

rust/rsc/src/rsc/add_job.rs, rust/rsc/src/rsc/blob.rs, rust/rsc/src/rsc/main.rs, rust/rsc/src/rsc/read_job.rs
Reenables tracing logs for the RSC. It does this by moving (and thus omitting) the spammy `sqx` logs and completely removing the very spammy parameter logs. 
This isn't as useful as the super spammy logs for debugging but its significantly better than the nothing we have right now.
In the long term, I'd like to see about writing the logs to a file, or more interestingly, writing the logs back into the postgres database so we can do structured analysis on them.
=> rsc: Reenable minified version of trace logging

share/wake/lib/system/http.wake, share/wake/lib/system/remote_cache_api.wake
This change updates it so that `stdout` and `stderr` are optimized when small. It'll decrease the number of blobs stored externally, and the number of jobs needed to fetch those blobs.
Right now only `stdout`/`stderr` are supported but with careful consideration there is no reason generic blobs can't be supported.
The server still needs a change to dedup duplicate "small blobs" but that is a transparent change to the client that can be done later
=> rsc: Support dbonly small blobs on the client

share/wake/lib/system/runner.wake
Previously I just `panic`ed with the RSC config was invalid. At the time this was more reasonable because 1) it was only invalid when the config had a typo and 2) I (incorrectly) assumed it would only apply to the wake bootstrap build. 
With both of those no longer true, the `panic` needs to be replaced with a fallback to the non-cache runner
=> rsc: Don't panic on invalid RSC

share/wake/lib/system/remote_cache_api.wake
Certain versions of `mv` will fail when both the `src` and `dst` are hardlinked to the same inode.
Ex:
```
$ echo "foo" > foo.txt
$ ln foo.txt one.txt
$ ln foo.txt two.txt
$ mv two.txt one.txt 
mv: 'two.txt' and 'one.txt' are the same file
```
which can occur if the a build is hydrated from the RSC, then the local db is removed but none of the output files, then the build is again hydrated from the RSC.
`mv` doesn't have a magic `--pls-dont-have-that-behavior` flag and we can't simply skip the `mv` due to atomic permission  requirements so this changes the client to rm the old output file if it is a hardlink to the same inode
=> rsc: Don't fail in presence of old hardlink

share/wake/lib/system/remote_cache_api.wake
The `auth` and `version` checks were getting triggered far more than expected. This change makes them `target`s so they are only triggered once per wake invocation.
=> rsc: Only check auth/version once per wake invocation

rust/entity/src/job.rs, rust/migration/src/lib.rs, rust/migration/src/m20240509_163905_add_label_to_job.rs, rust/rsc/src/rsc/add_job.rs, rust/rsc/src/rsc/main.rs, rust/rsc/src/rsc/types.rs, share/wake/lib/system/remote_cache_api.wake
A job's label isn't relevant to a job's cachability so it was not previously tracked. However, since things like cmd/env are obscured in the db (due to storage format) it is very difficult to examine a specific job. Adding the label makes it easier to inspect the db so this change adds it as an option field when uploading a job.
=> rsc: Track job label in rsc db

rust/rsc/src/common/database.rs, rust/rsc/src/rsc_tool/main.rs
Running `rsc_tool danger-delete-all-jobs` on large databases takes a very long time and can peg the postgres processes at 100% for several hours. This seems to be a common postgres issue when issuing very large deletes.
Being a very rare thing we would do, its fine that the process is slow but we need to be able to interrupt the project if the machine is under heavy load however interrupting the process doesn't actually stop postgres from maxing out the cores.
To avoid this issue, the delete is issued in batches so when it is interrupted only the last (much smaller) batch needs to complete before postgres chills out.
As a bonus, this also gives some level of progress through the delete instead of hanging for a long time
=> rsc: Page delete-all-jobs query for interruptable progress

rust/migration/src/m20220101_000001_create_blob_tables.rs, rust/rsc/.config.json, rust/rsc/src/common/database.rs, rust/rsc/src/rsc/blob.rs
The dbonly blob store was creating hundreds of rows for the empty string blob. In solving this a more general implementation arose.
A blob store is now allowed to de-duplicate a blob by returning a previously return key. The database will automatically flatten that into one entry in the db (and update the TTL for blob eviction)
The uniqueness requirement is set for store id+key pair so two different stores are allowed to return the same key without issues
=> rsc: Allow blob stores to dedup blobs

rust/entity/src/blob.rs, rust/migration/src/m20220101_000001_create_blob_tables.rs, rust/rsc/.config.json, rust/rsc/src/common/database.rs, rust/rsc/src/rsc/blob.rs, rust/rsc/src/rsc/blob_store_impls.rs, rust/rsc/src/rsc/main.rs
Blob size will be needed eventually for more complex eviction algorithms and is useful now for analyzing usage stats of given jobs.
This change adds sizes to blobs and requires the BlobStore to report the size used for an uploaded blob.
=> rsc: Track blob size in database

rust/entity/src/blob.rs, rust/migration/src/lib.rs, rust/migration/src/m20240517_195757_add_updated_at_to_blob.rs, rust/rsc/.config.json, rust/rsc/src/common/database.rs, rust/rsc/src/rsc/blob.rs, rust/rsc/src/rsc/main.rs
Adds an `update_at` column to Blob to track when updated. Blob eviction TTL now uses updated_at instead of created_at
=> rsc: Add updated_at to blob

src/runtime/database.cpp, src/runtime/database.h, tools/wake/main.cpp
Previously database inspection was created by unioning & intersecting several smaller sqlite queries together. This was mostly a bandaid over the previous system.
It was good enough for awhile but couldn't support nice features like negation, precise exclusion (for internal jobs) or custom user filers.
With a (fair) bit of massaging all the queries can be sent as a single generated query with significantly more flexibility. 
This PR makes that change and also adds support for negation with `!` in front of any filter variable. 
Followup PRs will handing a better system for tagging and filtering out internal jobs
=> db: Generate sql for db inspection

share/wake/lib/core/list.wake
There's been a few times I and @maniltongya have lamented not having some less-obvious List helpers we'd reach for in Haskell; this adds the two we had talked about previously, and I quickly scanned through Data.List but didn't see anything else immediately relevant -- feel free to suggest others, though, if I did miss something.
Additionally, this implements the note that [we'd eventually add `single`](https://github.com/sifive/wake-extras/blob/bb9e17d6b1b492da968b89ff6efd73b876675164/query.wake#L3-L6) for similar limited benefit as `prepend` (i.e. not having to write a parenthetical underscore-lambda when we want to pass it to some other function).  I deliberately *haven't* brought over [the similarly-notated `lookup`](https://github.com/sifive/wake-extras/blob/bb9e17d6b1b492da968b89ff6e …
=> Add a few list helper functions

Makefile, share/wake/lib/system/http.wake, share/wake/lib/system/io.wake, share/wake/lib/system/job.wake, share/wake/lib/system/path.wake, share/wake/lib/system/remote_cache_api.wake, share/wake/lib/system/remote_cache_runner.wake, share/wake/lib/system/sources.wake, tools/wake/main.cpp
Manually and directly tag jobs as hidden then filter those jobs out from inspection instead of relying on magic character in the jobs commandline/label
=> db: Use tags instead of magic to hide internal jobs

share/wake/lib/system/remote_cache_api.wake, share/wake/lib/system/remote_cache_runner.wake
Cleans up TODOS, updates the strToBytes function to use `byteToInteger` which shouldn't break serialization on non-ASCII strings
=> rsc: Cleanup TODOs

share/wake/lib/system/remote_cache_api.wake, share/wake/lib/system/remote_cache_runner.wake
I unnecessarily introduced a new env var for debugging the remote cache. This complicated things without actually having an real value. This change makes the old env var the standard and warns when the new one is being used.
=> rsc: Use a singular env var to debug shared caches

share/doc/wake/syntax/emacs/wake-mode.el
Fix a bug in syntax highlighting for regular expressions.  These are put in backticks.  However, this was not specified in the syntax table. Therefore, any quote in a regex would kick syntax highlighting into "string mode" and likely mess up highlighting in the rest of the file.
=> highlight: Add missing regex syntax in emacs

src/runtime/database.cpp, src/runtime/database.h, tools/wake/main.cpp
It was discovered that really long input/output file lists will overflow sqlite3's max column memory after releasing the previous version of wake.
The input/output file part of the query have been moved into a seperate join in order to maintain the nicety of a single generated sql query per inspection. This is _nearly_ identical to the previous inspection query and all previous commands still work as expected however input/output files are now special cased an non-orthogonal. This means any future inspection command has to consider them specifically and also when`--sql` is implemented queries involving input/output files may not be specified in the sql
<details>
<summary>Examples of the Generated SQL</summary>
```
wake --last
SELECT j.job_id, j.label, j.directory, j.commandline, …
```
=> db: Fix mem overflow during inspection

rust/rsc/.config.json, share/wake/lib/system/remote_cache_api.wake, share/wake/lib/system/remote_cache_runner.wake, share/wake/lib/system/runner.wake
Moves all of the RSC client code into the `remote_cache` package for better isolation and deals with the associated fallout
=> rsc: Move client code to dedicated package

src/runtime/job.cpp
A status system bug was exercised by the RSC. Basically the wrong `<<` function was being using to emit stdout/stderr which meant that certain strings were emitted as escaped strings instead of the expected, formatted string
=> status: Don't format/escape stdout/err

share/wake/lib/system/remote_cache_api.wake
Updates the RSC client code to use the new functions for serializing unicode strings. After this change unicode in the cmd or env will no longer incorrectly generate a cache hit
=> rsc: Support unicode in cmd/env

rust/rsc/src/bin/rsc/main.rs
Out of an abundance of caution, this PR dials the job TTL down to 24 hours. As a fairly quick followup this will be changed into a config variable but for now I'd like to lean on the conservative side for the reason we are making later today
=> rsc: Decrease job TTL

rust/rsc/src/bin/rsc/dashboard.rs, rust/rsc/src/bin/rsc/main.rs, rust/rsc/src/bin/rsc/types.rs, rust/rsc/src/database.rs
This PR adds another route to the rsc `GET /dashboard` which returns a json object summarizing basic stats about the cache. 
A follow up PR will be added that renders it (somewhat) nicely as an HTML page
Example response:
```json
{
"job_count": 1234,
"blob_count": 9999,
"size": 1000000000,
"savings": 5432,
"oldest_jobs": [
{
"label": "echo foo",
"created_at": "2024-07-16T18:02:01.083651",
"savings": 5
}
],
"most_reused_jobs": [
{
"label": "echo foo",
"reuses": 2,
"savings": 5
}
],
"most_space_efficient_jobs": [
{
"label": "foo bar",
"runtime": 1,
"disk_usage": 50,
"ms_saved_per_byte": 50
}
],
"most_space_use_jobs": [
{
"label": "foo bar",
"runtime": 1,
"disk_usage": 50,
"ms_saved_per_byte": 50
}
],
"lost_opportunity_jobs": [
{
"label": "foo bar",
"reuses": 1,
"misses": 50,
"real_savings": …
```
=> rsc: Add json route that returns stats

share/wake/lib/system/http.wake
Filenames with uncommon characters just as `,` would previously fail to be cached. This change escapes the filename so that they can be cached.
=> rsc: Fix filename escaping bug

rust/rsc/src/bin/rsc/config.rs, rust/rsc/src/bin/rsc/main.rs, rust/rsc/src/bin/rsc_tool/config.rs, rust/rsc/src/bin/rsc_tool/main.rs, rust/rsc/src/lib.rs
This is a simplification and split of the RSC config files in preparation for a larger push for config changes.
Unneeded configs and arg flags were removed and the `rsc` and `rsc_tool` were given dedicated config types
=> rsc: Split configs for rsc/rsc_tool

rust/rsc/src/bin/rsc/main.rs, rust/rsc/src/database.rs
- The number of blobs deleted per tick is now supplied via config var.
- The eviction loop now only sleeps between ticks when it has fully caught up on evictions or when something goes wrong
=> rsc: Allow config for chunking blob eviction + no sleep until caught up

rust/rsc/src/bin/rsc/config.rs, rust/rsc/src/bin/rsc/main.rs
Pool connection timeout can now be set/managed from RSC config
=> rsc: Determine pool connection timeout from config

rust/entity/src/job.rs, rust/migration/src/lib.rs, rust/migration/src/m20220101_000002_create_table.rs, rust/migration/src/m20240731_152842_create_job_size_proc.rs, rust/rsc/.config.json, rust/rsc/src/bin/rsc/add_job.rs, rust/rsc/src/bin/rsc/config.rs, rust/rsc/src/bin/rsc/main.rs, rust/rsc/src/database.rs
Recalculating the job size every time it is needed is very expensive. This was less of an issue when only being used for dashboarding but the size is also needed for eventual LRU eviction. This PR sets up a cron task to calculate and store the size of the job after the job has been inserted so that the calculated value can be used directly
=> rsc: Precalcuate job size as part of cron job

rust/migration/src/lib.rs, rust/migration/src/m20240731_201632_create_job_blob_timestamp_index.rs, rust/rsc/src/bin/rsc/main.rs, rust/rsc/src/database.rs
- Adds index to blob(updated_at) which speeds up the TTL check for old blobs
- Completes the blob eviction lookup and delete in one query to not waste time repeating work.
- Makes delete query much more static instead of passing in 16k variables
=> rsc: Optimize blob eviction deletion

rust/entity/src/job.rs, rust/migration/src/m20220101_000002_create_table.rs, rust/rsc/.config.json, rust/rsc/src/bin/rsc/types.rs
Hidden info was suppose to be a `string` not an `ezblob`. It wasn't really hurting anything besides using more space but since db breaking changes are going in anyways it should be fixed
=> rsc: Fix type for hidden_info

share/wake/lib/system/http.wake
The previous escape changes regressed small blob handling. This PR refines the escape so that it works for both small/blob and files with `,` in them
=> rsc: Refine curl escape

rust/rsc/.config.json, rust/rsc/src/bin/rsc/blob_store_impls.rs
Instead of dumping all blobs into the root of the local blob store, nest them into sub folders to avoid hitting files limits
=> rsc: Tier blobs into nested dirs to avoid file limits

rust/rsc/.config.json, rust/rsc/src/bin/rsc/dashboard.rs, rust/rsc/src/bin/rsc/types.rs, rust/rsc/src/database.rs
Adds data for "Most Time Saved Jobs" and "Blobs/Blob Reference per store" 
Improves previous lost opportunity and bytes per ms data
=> rsc: Add more dashboards and improve others

.github/workflows/build.yaml, .github/workflows/dockerfiles/alpine, .github/workflows/dockerfiles/debian-bullseye, .github/workflows/dockerfiles/fedora-38, .github/workflows/dockerfiles/rocky-8, .github/workflows/dockerfiles/rocky-9, .github/workflows/dockerfiles/ubuntu-22.04, .github/workflows/dockerfiles/wasm, rust/entity/Cargo.lock, rust/log_viewer/Cargo.lock, rust/migration/Cargo.lock, rust/rsc/.config.json, rust/rsc/Cargo.lock
One of the RSC's dependencies doesn't build against rust 1.8 which GHActions is now using by default. This PR updates the deps so that CI can pass again
=> rsc: Enable RSC to build with rust 1.8

rust/rsc/src/bin/rsc/blob.rs
We've observed blob uploads that silently failed which caused a delay is response time. This updates the `POST /blob` route to log an error when blob upload fails for some reason
=> rsc: Log failures to upload blob

.github/workflows/build.yaml
When disabling alpine I missed turning off the download which broke the release pipeline. This should fix the pipeline while we work on fixing the build
=> ci: Fix broken release

.github/workflows/build.yaml
_extremely temporary_
Disables VSCode Extension build to unblock critical RSC fixes. Immediately after the release  work will start to fix the extension build
=> ci: Disable VSCode Extension

rust/rsc/.config.json, rust/rsc/src/bin/rsc/config.rs, rust/rsc/src/bin/rsc/main.rs, rust/rsc/src/bin/rsc/read_job.rs
Allows the config to specify what the minimum runtime should be for a cache job. Any job that completes faster than that runtime isn't worth caching due to various overheads
=> rsc: Add config var for min runtime to cache

share/wake/lib/system/http.wake
Sets Usage to observation based values. Lets more requests run in parallel on a limited set of cores
=> http: Set job cpu time

share/wake/lib/system/remote_cache_api.wake
Allows generic blobs to also be created as DbOnly blobs, including the deduping feature.
This change does require that the blob be `stat`d but that should essentially be free because `stat` is a `target` and we have to stat every file before upload anyways
=> rsc: Allow file blobs in DbOnly Store

rust/rsc/src/database.rs
`UNION` requires that duplicate ids be removed which requires a sort + unique linear scan. We were previously doing this on the largest table in the database. Instead its more performant if we move the id deduplication to the last step where the id list is as small as possible. This results in a query plan where the sort + unique linear scan happens on a much smaller set of rows
=> rsc: Optimize blob eviction query

.github/workflows/build.yaml
upload-artificant@v3 silently changed the default to not included hidden files. This broke the release process.
Restores the functionality to just that artifact upload.
See https://github.com/actions/upload-artifact/issues/602 for more details.
=> ci: Include hidden files in the test artifact

share/wake/lib/system/remote_cache_runner.wake
Not sure how I forget this, but we can't cache jobs that fail. It wastes space but more importantly can "lock in" a flow failure for other users/flow runs
=> rsc: Failing jobs shouldn't be cached

share/wake/lib/system/remote_cache_runner.wake
When a job creates both a file and a symlink to that file but only outputs the symlink it creates a hidden dependency on that untracked file. 
This is generally not a huge problem but now is since the RSC is moving to only track true dependencies. The symlink would be restored but not the "hidden" file.
This PR panics when that situation occurs for a cached job. Broken jobs can avoid this by opting out of caching or by also outputting the hidden file
=> rsc: Disallow hidden file dependencies

rust/entity/src/output_dir.rs, rust/migration/src/lib.rs, rust/migration/src/m20240919_214610_add_hidden_to_output_dir.rs, rust/rsc/src/bin/rsc/add_job.rs, rust/rsc/src/bin/rsc/read_job.rs, rust/rsc/src/bin/rsc/types.rs, share/wake/lib/system/remote_cache_api.wake, share/wake/lib/system/remote_cache_runner.wake
Updates the RSC and clients to track "hidden" directories which are directories created by a job but not output by the job.
This is necessary as some jobs will output a file and depends on the directory being created without also outputting said directory
=> rsc: Track hidden output dirs

rust/rsc/.config.json, rust/rsc/src/bin/rsc/config.rs, rust/rsc/src/bin/rsc/main.rs, rust/rsc/src/bin/rsc/types.rs
Blob file deletion previously launched a task per file. This has significant overhead when deleting 100s of thousands of files. 
This change allows the config to specify how many files should be deleted per task
=> rsc: Delete multiple blob files per task by config

rust/rsc/.config.json, rust/rsc/src/bin/rsc/config.rs, rust/rsc/src/bin/rsc/main.rs
Adds a new config var `connection_pool_max_connect` which is used to determine the max number of connections the server will make to the database server
=> rsc: Add config var for max number of pool connections

share/wake/lib/system/runner.wake
Runners need to wait for jobs to complete before calling `FnOutputs` so that all files are written to disk before any kind of magic file detection occurs
=> stdlib: Fix call timing for FnOutputs

share/wake/lib/system/remote_cache_runner.wake
When rehydrating from the cache, any "hidden" directories should be listed as cleanable outputs since they aren't listed as actual outputs by the runner. If they aren't listed then they won't get cleaned up as expected by `wake --clean`
=> rsc: Hidden directories should be returned as cleanable outputs

.github/workflows/build.yaml, tools/wake-format/emitter.cpp
clang-format-12  is no longer available in CI now that `ubuntu-latest` points to 24.04. Switch to a newer one
=> ci: Switch to available formatter

share/wake/lib/system/remote_cache_api.wake
When writing a db backed blob file to disk, include the blob id in the file name for better inspection.
=> rsc: Tag dbblob files with their blob id

src/runtime/database.cpp, src/runtime/database.h, tools/wake/cli_options.h, tools/wake/describe.cpp, tools/wake/describe.h, tools/wake/main.cpp
Added new `wake --history` command
=> cli: Add new history command

share/wake/lib/system/job.wake, share/wake/lib/system/job_cache_runner.wake, share/wake/lib/system/remote_cache_runner.wake, share/wake/lib/system/runner.wake
We've seen a couple problems where the proper reporting of an issue got masked by an "Infinite recursion detected" panic, and we verified that it was due to `primJobFinish`/`primJobFailFinish` being called before the respective `primJobLaunch`/`primJobFailLaunch` -- which for all their other benefits is a new risk with v44's flattened runners.  Ultimately it would be best to implement an architecture solution for solving this, but in the mean time it's sufficient to patch the existing runners and to keep a careful eye on future code which touches them.
=> Fix potential "infinite recursion" panics in runners

share/wake/lib/core/result.wake
The examples in the documentation showed passing the same arguments and getting different results. The examples are incorrect because they forgot to change the arguments to demonstrate the other case. This fixes the examples and also replaces the type of the other case to more clearly indicate that it is totally unused.
=> [result] Fix documentation for getWhenFail and getWhenPass methods.

src/runtime/gc.cpp, src/runtime/gc.h, src/runtime/tuple.cpp, src/runtime/value.cpp, tools/wake/main.cpp
`--profile-heap` currently lacks proper metrics to debug OOM issues and varies from the information provided from valgrind. This PR adds more relevant information about the garbage collector for each GC cycle, while also adding extra information in profiling csv file.
Example generated CSV file: 
[heap_log.csv](https://github.com/user-attachments/files/18872526/heap_log.csv)
=> Add better profiling of heap for --profile-heap

share/wake/lib/system/remote_cache_api.wake
This PR fixes the bug where when enabling rsc and running a wake command exposes the `generateUUID` function call when it should be hidden.
Before:
```
[aquazi@pe01 federation]$ wake --init .
[aquazi@pe01 federation]$ wake -x 'Unit'
Unit
[aquazi@pe01 federation]$ wake --last
$ date +%s%N
1745341573150093718
```
After:
```
[aquazi@pe01 wake]$ ./bin/wake -x 'Unit'
Unit
[aquazi@pe01 wake]$ ./bin/wake --last
No jobs matched query
[aquazi@pe01 wake]$ 
```
The generateUUID function is required to run to check against the sentinel disable cache file to verify if the RSC should be disabled or not, in `guardRemoteCacheDisabled`. This PR also restructures `guardRemoteCacheDisabled` so that `generateUUID` is only called when necessary (only if the disabled file exists) instead of being called by …
=> bugfix: fixing bug where generateUUID function appears when doing --last

src/runtime/database.cpp
With the addition of `runner_status` to the `jobs` table on https://github.com/sifiveinc/wake/pull/1695, I noticed that there was significant delay in querying for failed jobs using `wake --failed` for larger wake.db's. This PR fixes this issue by also indexing on `runner_status` and adding it to the core subtable so that the database can query without checking every single row on the jobs table.
=> Fix performance issue of wake --failed related to runner failures

.wakemanifest, Makefile, build.wake, src/runtime/database.cpp, src/runtime/schema.h, tools/wake-migrate/main.cpp, tools/wake-migrate/wake-migrate.wake, wake.spec.in
Added the `wake-migration` tool so that users can now easily update and migrate their wake.db whenever wake releases have database version upgrades/schema changes without having to delete their current wake db instance.
=> Add wake.db migration tool

rust/entity/src/blob.rs, rust/migration/src/lib.rs, rust/migration/src/m20250900_000000_add_content_hash_to_blob.rs, rust/rsc/src/bin/rsc/blob.rs, rust/rsc/src/bin/rsc/main.rs, rust/rsc/src/bin/rsc/read_job.rs, rust/rsc/src/bin/rsc/types.rs, share/wake/lib/system/http.wake, share/wake/lib/system/remote_cache_api.wake
In order to protect against cache poisoning of the blob store, this PR introduces the `content_hash` field that sends a blake2b hash of the contents of the output file blobs of a cached job to the RSC server for it to store in the DB, as a way for clients to check against the hash when downloading the blob from the store during a cache hit.
=> Add content_hash field to verify cached blobs when downloaded
