sifiveinc/wake

doc/tutorial.md, share/wake/lib/core/double.wake, share/wake/lib/core/integer.wake, share/wake/lib/core/json.wake, share/wake/lib/core/list.wake, share/wake/lib/core/order.wake, share/wake/lib/core/string.wake, share/wake/lib/core/tree.wake, share/wake/lib/core/vector.wake, share/wake/lib/system/gcc.wake
We've decided to use longer xToY style for all function names in wake.
Long functions are a thing!
=> Cleanup APIs

README.md
We need like a clean laptop we can wipe and check install instructions
=> Update MacOS with Homebrew instructions

share/wake/lib/system/job.wake
=> job: add resources to the RunnerInput

doc/wake-mode.el
I don't think emacs syntax file has been updated since v0.9.
=> Update emacs syntax file to v0.13 syntax

share/wake/lib/core/tree.wake, share/wake/lib/core/vector.wake, src/parser.cpp
Reading over the syntax highlighting for emacs made me realize I had to fix a few things!
=> Better if parsing

doc/wake-4.1.jsf, doc/wake-4.6.jsf
detect Doubles
: and ` are legal
? is illegal
val is not a keyword
tuple is a keyword
=> joe: update syntax highlighting for v0.13

fuse/fuse.cpp, src/value.cpp, src/value.h
Older versions are problematic.
=> value: avoid RE2::Options limitation

re2c/re2c.wake, share/wake/lib/core/double.wake, share/wake/lib/core/json.wake, share/wake/lib/core/print.wake, share/wake/lib/system/job.wake, share/wake/lib/system/path.wake, share/wake/lib/system/pkgconfig.wake, share/wake/lib/system/sources.wake, src/job.cpp, src/main.cpp, src/prim.h, src/status.cpp, src/string.cpp, src/wake.wake
Plans can now control what gets dump to the terminal in a build.
=> Fancy Printing

share/wake/lib/system/job.wake
These APIs are ancient and bad. Let's remove them in the future.
=> job: deprecate old APIs

share/wake/lib/system/job.wake, src/job.cpp, src/main.cpp
This PR should make fully functional remote runners possible.
@samh-sifive This will be in v0.15.0. You will almost certainly need to update your slurm runner, but it should be possible now to really leverage for parallel dispatch.
=> Remote scheduler

doc/quickref.md
opened a new pr.
This is basically done for now.
=> A first quickref for wake.

.gitignore, share/wake/lib/core/json.wake, share/wake/lib/system/job.wake, share/wake/lib/system/path.wake
This is an API change but it is usually code negative or neutral in fixing it
=> Change read and parseJSONFile to fail with Error instead of String

fuse/daemon.cpp
erase files_read from files_wrote
=> erase files_wrote from files_read

README.md, fuse/fuse.cpp, preload/wrap.cpp, share/wake/lib/system/environment.wake, src/database.cpp, src/main.cpp
Don't randomly return a non-zero exit status for non-Result types.
=> Return code

share/wake/lib/core/option.wake, src/bind.cpp
```
global def jack =
def file = file
42
```
... also add 'orElse'
=> Fix cycle segfault

README.md
=> README: brew can use system sqlite3 and ncurses

share/doc/wake/tutorial.md
I think more is necessary, and I think a section on JSON to provide a more complete example is still needed but I wanted to PR this to get feedback rather than just continuing to add to it.
=> Add tutorial section for dealing with failure

fuse/fuse.cpp, src/job.cpp
Please confirm this resolves your ```pipe: Too many open files``` issue.
=> Increase limit on file descriptors

debian/changelog.in
First patch release for v0.15.
=> v0.15.0: Set the release date

src/main.cpp
This was introduced in 3c4f9f4009893c92fc548d7fe417f657bf55ba09
=> panic: don't confuse with a target loop

fuse/daemon.cpp, fuse/fuse.cpp
The .fuse folder has a file called .f.wake ... which predictably gets parsed as a wakefile.
=> Fix fuse wake race

share/wake/lib/core/json.wake, share/wake/lib/system/job.wake, share/wake/lib/system/path.wake
It originally returned Result String Error which is problematic for
propagating Paths
Weirdly,  @john-sifive doesn't show up for assigning reviewers
=> Change getPathResult to return Result Path Error

share/wake/lib/system/job.wake, share/wake/lib/system/sources.wake
also fixes case where input was not simplified
Fixes #95
=> source: check if the input is a sources file

src/database.cpp, src/database.h, src/job.cpp, src/status.cpp, src/status.h
Schedule jobs in critical path order.
=> Critical path

share/doc/wake/tutorial.md, share/wake/lib/core/json.wake
Example: ```json /../ (_ // `name` ==/ JString "pig")```
Returns: all nodes in the JSON tree with a child named pig.
=>  json: add the /../ operator for deep search of a JSON file

README.md
=> README: document how to install into a home directory

wake.spec.in
=> wake.spec: create a relocatable RPM

src/database.cpp, src/string.cpp, src/value.h
Reading an 8GiB file used to take 30s. Now it takes 3.3s.
=> read: improve performance 10x

fuse/daemon.cpp
=> fuse: don't attempt to unmount forever

share/wake/lib/core/boolean.wake, share/wake/lib/core/double.wake, share/wake/lib/core/integer.wake, share/wake/lib/core/list.wake, share/wake/lib/core/option.wake, share/wake/lib/core/order.wake, share/wake/lib/core/string.wake, share/wake/lib/core/syntax.wake, share/wake/lib/core/tree.wake, share/wake/lib/core/tuple.wake, share/wake/lib/core/vector.wake, wake2rst.py
Added additional documentation for features, to be included in the HTML documentation.
Note that some documentation is incomplete because I don't understand all the features that Wake offers yet.
=> Added Documentation

share/wake/lib/core/json.wake, share/wake/lib/core/print.wake
=> Misc stdlib improvements

common/json5.cpp, src/expr.cpp, src/job.cpp, src/value.cpp
valgrind found a number of uses of uninitialized memory. Oops!
=> Fix undefined memory accesses

.circleci/config.yml
=> circleci: use git instead of gh-pages

README.md, common/location.h, share/wake/html/main.js, src/bind.cpp, src/expr.cpp, src/expr.h, src/main.cpp, src/parser.cpp, src/value.cpp
This is a follow-up PR which smooths out the few remaining issues in the documentation generation.
=> Improve HTML generation

Makefile, README.md, fuse/daemon.cpp, fuse/fuse.cpp, share/wake/lib/system/gcc.wake, share/wake/lib/system/os.wake, src/sources.cpp, src/status.h
Replaces #213 
@sistillson I've tested this on 12.0 and it seems to work now.
=> FreeBSD port with working FUSE

src/sources.cpp
These directories are volatile.  Their contents can disappear during the
build.  That can lead to spurious error messages, like detecting duplicated
wake symbols from a failed build that leaves .wake files in build step.
=> wake: don't scan .build or .fuse directories

src/job.cpp, src/job.h, src/main.cpp, src/parser.cpp, src/prim.h, src/target.cpp
The cure was worse than the disease.
Reopen #106.
=> Undo loop detect

src/string.cpp
Reusing the general-purpose deep wait in hashing is too expensive
for such a common and important primitive.
=> lcat: directly walk the input list

common/shell.cpp, common/shell.h, src/job.cpp, src/main.cpp
This affects command echos, progress status, and job descriptions.
=> wake: consistently escape shell command output

src/datatype.cpp, src/datatype.h, src/describe.cpp, src/describe.h, src/main.cpp, src/markup.cpp, src/markup.h, src/parser.cpp, src/parser.h, src/prim.cpp, src/prim.h, src/sources.cpp, src/target.cpp, src/value.cpp, src/vector.cpp
=> Clean-up main.cpp by moving code to their respective subsystems

.circleci/config.yml, README.md, build.wake, re2c/fake-re2c, re2c/re2c.wake, share/wake/lib/system/job.wake, src/sed-version
Use the new multiline string support to implement shell scripts inside wake.
=> Shell jobs

share/wake/lib/core/double.wake, share/wake/lib/core/integer.wake, share/wake/lib/core/list.wake, share/wake/lib/core/option.wake, src/gc.cpp, src/gc.h, src/main.cpp, src/runtime.cpp, src/runtime.h, src/tuple.cpp, src/tuple.h
Add --profile-heap and --heap-factor options. These can help debug memory usage.
=> Heap stats

src/gc.cpp, src/gc.h, src/main.cpp
Somehow this commit got lost from the last PR.
=> GC: don't touch destroyed type names

fuse/daemon.cpp
Previously this just broke on hashing
=> fuse: support rename of directories with contents

.circleci/config.yml, debian/control, wake.spec.in
=> dash: required by package files too

share/doc/wake/quickref.md, share/wake/lib/system/job.wake
Credit to @albertchen-sifive for providing the base content of this.
=> Add documentation for runners and environment packages

share/wake/lib/core/string.wake, src/bind.cpp, src/expr.h, src/gc.cpp, src/gc.h, src/job.cpp, src/prim.cpp, src/runtime.cpp, src/runtime.h, src/string.cpp, src/tuple.cpp, src/tuple.h, src/value.h
Grab good changes from #244, which we're not going to merge now.
=> Cherry pick lazy

src/main.cpp, src/prim.h, src/target.cpp
Global variables are not so nice, but get the job done.
=> target: don't report missing values if wake is terminated

share/doc/wake/from-scala.adoc
=> from-scala: make the examples legal wake

src/status.cpp
=> status: if stdout is piped, we don't have a tty

src/job.cpp, src/regexp.cpp
This got broken somewhere along the way.
=> wake: backport to osx 10.10

debian/changelog.in
Backport some bugfixes to 0.15
=> Merge v0.15.2 release

src/scope.cpp
Didn't review the last PR carefully enough!
=> hash: fix typo

src/job.cpp, src/runtime.cpp, src/status.cpp, src/status.h
=> wake: show a spinner when wake is running code

fuse/daemon.cpp, src/dsu.h, src/main.cpp, src/type.cpp, src/type.h
The type formatting accessed invalid memory.
=> Fix invalid dob

.circleci/config.yml, fuse/daemon.cpp, src/gc.cpp
Cannot use member variables even in decltype on clang.
=> fuse: fix utimensat on clang

share/doc/wake/how-to/create-a-release.adoc
I tried adding some documentation on how to create a release. Let me know if these instructions make sense, or if there are any mistakes in them.
=> Add notes on creating a release.

common/execpath.cpp, src/sources.cpp
=> wake: handle the case where cwd is unreadable

src/expr.cpp, src/expr.h
These have not been used since SSA was introduced.
=> Expr: remove useless hash and flags

share/wake/lib/core/regexp.wake, src/sources.cpp
- Also add support for \
- Escape properly classes in []
=> sources: split an improved glob2regexp into a reusable function

share/doc/wake/tutorial.md, src/main.cpp, src/sources.cpp, src/sources.h, tests/test_all.sh, tests/test_util.sh, tests/wake-ignore.t
Backport of https://github.com/sifive/wake/pull/359 onto 0.17
Looking to create a 0.17.2 release from this
=> Backport of .wakeignore to 0.17.x

src/database.cpp
Backport https://github.com/sifive/wake/pull/363 to v0.17 for 0.17.2 release, as requested by @jackkoenig
=> Rebuild when inputs disappear

src/database.cpp, src/database.h, src/main.cpp
No one was using this feature. Stored expressions would have needed to capture their package context. Don't bother fixing it, get rid of it!
=> Remove DB targets

src/main.cpp
=> wake: encourage people to update their scripts

share/doc/wake/quickref.md, share/doc/wake/tour/packages.adoc, share/doc/wake/tour/targets.adoc, share/doc/wake/tour/tuples.adoc, share/doc/wake/tutorial.md
The tuple and tutorial docs were out-of-date.
=> Update docs for 0.18

share/wake/lib/core/double.wake, share/wake/lib/core/integer.wake
They were previously the identity function.
=> core: + and +. should force their types

src/main.cpp, src/type.cpp, src/type.h
Turns out spewing error messages onto a user's screen is not helpful.
=> Fix available target enumeration

src/bind.cpp
This is now illegal:
```
require (a; b) = ...
```
=> bind: detect when require is used unnecessarily

share/wake/lib/core/list.wake
Explicit list append and prepend functions
I've seen (and written) lines that look like,
`def newList = someList ++ (someItem, Nil)`
I think it's easier to read as
`def newList = append someList someItem`
=> List append item function

debian/changelog.in
=> wake: mark release of v0.18.1

share/wake/lib/core/syntax.wake, share/wake/lib/system/job.wake, src/bind.cpp, src/cse.cpp, src/exception.cpp, src/inline.cpp
Detect more functions as equal.
Also detect when all cases reduce to the same execution path.
=> CSE improvements

.circleci/config.yml, src/sources.cpp
=> sources: describe why --init fails

share/wake/lib/system/environment.wake, src/main.cpp
=> Add "--strict" option to wake cli to set PATH=""

share/wake/lib/core/string.wake
Simple operations need helper functions, such as sorting list of string.
I had to ask around today for this implementation, so posting here so others can have a grep-able name
=> Add sort func for list of string

fuse/fuse.cpp
Previously, fuse-wake provided a redacted view of the workspace on
.fuse/pid/ and ran Jobs there. This has two downsides:
- we trust the Job not to access the workspace directly
- the Jobs can notice that .fuse is in the build paths
- this can result in non-deterministic output
- this can confuse follow-on Jobs that expect .fuse filenames
This change only affects linux
=> fuse: use unshare to fully redact the workspace

share/wake/lib/core/tree.wake
export `Tree` so we can do
```
tuple ASDF =
LKJ: Tree String
```
=> export Tree type

share/wake/lib/nothing/nothing.wake, src/main.cpp
Defaulting to wake allowed the user access to unexported symbols!
=> main: default to no package if none is found

re2c/re2c.wake, share/wake/lib/system/gcc.wake, share/wake/lib/system/job.wake, src/database.cpp, src/database.h, src/describe.cpp, src/job.cpp
Add labels to Plans.
These are recorded in the database and shown when inspecting Jobs.
Progress bars use the label name for better readability.
=> Plan labels

src/database.cpp
This way we can detect incompatible databases gracefully.
Fixes #405.
=> database: add a schema version number

src/database.cpp
When an input file is specified which was not a visible file, it currently generates an sqlite3 exception.
Ever since https://github.com/sifive/wake/pull/139 (v0.15), we record the visible files. This makes it possible to test whether or not this condition occurs. Previously, when #358 was reported, that was not the case.
Therefore, this PR:
- detects when an input is not a visible file
- prints a warning to that effect
- omits the erroneous input from the database
- proceeds with the build
Fixes #358 .
=> database: detect if a user supplied bad inputs

debian/changelog.in
=> Set v0.19.1 release date

.circleci/config.yml, debian/changelog.in, src/database.cpp
=> Release 0.18.2

src/bind.cpp, src/inline.cpp, src/ssa.cpp
This PR applies a number of fixes to ensure pattern guards are optimized correctly.
=> Optimize literal match

share/doc/wake/tutorial.md
=> tutorial: update URL for Unicode data

common/jparser.cpp, common/json5.cpp, common/json5.h
Rather than trying to format JSON output directly, use an escape-safe C++ API.
=> JSON5 generation

share/wake/lib/core/result.wake
Fixes #210
Fixes #351
I think this PR combined with the new IO streams mostly addresses both of these issues.
=> result: addErrorContext for composition of "Result a Error"

share/wake/lib/system/job.wake
=> job: add isPathDir function

share/wake/lib/core/result.wake
=> result: fix two warnings

fuse/daemon.cpp, fuse/fuse.cpp
This PR adds some diagnostics around an area where fuse has been known to fail quasi-randomly.
=> FUSE debug

src/job.cpp
For memory, we follow a more conservative policy. We don't start a job that would
oversubscribe RAM, unless there are no other jobs running yet. The rational:
- exceeding memory would slow down the build due to thrashing
- RAM is never "wasted" (disk cache / etc), so just wait for the next critical job
- even if a job uses more memory than the system has, eventually attempt it anyway (progress)
Previously, we used the same policy for memory as for CPU (add jobs until full).
Fixes #529.
=> scheduler: do not overcommit memory

src/sources.cpp
Fixes #497.
`git ls-files` lists submodule directories.
This is a problem, because wake uses that to find source FILES.
We now subtract from the results of ls-files the contents of .gitmodules, if
any, thus pruning any unwanted directories from the source files list.
=> sources: omit submodules from sources list

fuse/fuse.cpp
The input json has fields added for the mounts.
They must be correctly ordered if there is any overlap and the mount types must be supported by the platform.
The mounts are non-recursive and are optionally read-only when supported by the underlying filesystem.
If at some point we add more mount types, we can add a 'mount-type' field to the json entries
This does not add anything to Plan or Job to use this from within wake.
Jobs that do not use bind mounts are unaffected
This was tested by running `fuse-wake in.json out.json`
This performs a copy of `/bin/bash` into `/home/matthewc/bind-mounts/test/ws-mount2`, except that the copy command uses neither of those two paths directly
`in.json`:
```
{
"command": [
"bash", "-c", "ls -l ws-mount*; cp -v ws-mount1/bash ws-mount3/; ls ws-mount2; …
```
=> Add bind mounts to fuse-wake

src/sources.cpp
When wake cannot walk the workspace, say why.
=> Report enumeration failure

fuse/fuse.cpp
Add a pivot-root operation to fuse-wake so that we can change the base OS for each individual wake job.
This does not modify the wake rules to use the new functionality, just provides mechanism.
This PR makes the assumption that we want to build up our mount point, and then switch onto it as the last operation.
This isn't the only possible model, at a later date we could choose to expose the pivot_root's 'oldroot' as a json option if we wanted to make a model available where parts of oldroot can be mounted in post-pivot. It doesn't feel required just now
~The pivot expects that the new root has a `tmp` directory available as a subdir which we can pivot the old root onto. It's immediately unmounted.~ From reading docs it's looks like its possible to do a pivot without having that extra …
=> Add pivot-root mount option for fuse-wake

fuse/fuse.cpp
Adds a `squashfs` mount operation to fuse-wake
The input json to fuse-wake can have a entry that looks like
```
"mounts": [
{ "type": "squashfs", "source": "your-os-image.squashfs", "destination": "/mnt" }
]
```
Notes:
* This `fork()`s out to `squashfuse`
* `prctl` is used to kill `squashfuse` when `fuse-wake` terminates
* We poll to find out when the mount is ready before continuing\
* Requires `isolate/user` resource
=> Add 'squashfs' mount type to fuse-wake

.circleci/config.yml, .circleci/dockerfiles/centos-8.3, wake.spec.in
Ensure that the build works on redhat 8
Closes #577
=> Add Centos 8.3 to CI build

fuse/namespace.cpp
We have had to manually specify the destination mount prefix, for example the `/mnt`s in:
```
{
"command": ["bash", "-c", "echo hello"],
"environment": [
"PATH=/usr/bin:/bin",
"HOME=/root",
"USER=root"
],
"user-id": 0,
"group-id": 0,
"visible": [""],
"directory": ".",
"mount-ops": [
{ "type": "squashfs", "source": "centos8.wbi", "destination": "/mnt" },
{ "type": "bind", "source":"/proc", "destination": "/mnt/proc"},
{ "type": "bind", "source":"/sys", "destination": "/mnt/sys"},
{ "type": "bind", "source":"/dev", "destination": "/mnt/dev"},
{ "type": "tmpfs", "destination": "/mnt/tmp"},
{ "type": "tmpfs", "destination": "/mnt/run"},
{ "type": "tmpfs", "destination": "/mnt/var"},
{ "type": "tmpfs", "destination": "/mnt/home"},
{ "type": "workspace", "destination": "/mnt/workspace" },
{ …
```
=> wakebox: Use pivot-relative destination mountpoints

src/database.cpp
Instead of printing the same message every second, it now prints the
message once and just adds an additional period per second.
=> Change busy database print to only use one line

.gitignore, Makefile, fuse/client.cpp, fuse/daemon_client.cpp, fuse/fuse.cpp, fuse/fuse.h, fuse/fuse.wake, wake.spec.in, wakebox/main.cpp
This changes the `daemon_locations` from being a POD to more of a client library 
* daemon_locations is renamed to daemon_client
* daemon_client is created outside of `run_in_fuse`
* daemon_client has connect/disconnect methods
=> daemon client library

fuse/daemon.cpp
If the renamed directory happened to be "close enough" to the original name
that no files existed alphabetically between the new and old name, the
rename function would overrun its bounds.
=> fuse: fix a bug in 'rename'

src/parser.cpp
A coding style for wake calls for indenting even simple expressions:
```
def foo =
def bar =
777 + 123
def baz =
999 + 111
```
This results in a lot of block statements with no defs/imports.
Optimize for this case.
Also, fixes #610.
=> parser: optimize for empty blocks

share/wake/lib/core/list.wake
It's very useful to take a list and break it into user-defined categories.
This function makes that possible.
=> list: add a groupBy method

src/sources.cpp
To find the workspace root, wake looks for either a wake.db or a .wakeroot.
It searches from the current directory to the root, parent by parent.
This PR makes wake stop searching when it finds either wake.db or .wakeroot.
Previously, if wake found a wake.db, it would prefer it over a child .wakeroot.
This was a hold-over from when it was actually looking for a wit manifest.
Now that wit is gone, we should trust the .wakeroot to be correct.
There is never a reason to add more scope to the workspace than requested.
=> workspace: stop looking for wake.db if you find .wakeroot

src/parser.cpp
```
def (x; y) = ... # is an extractor
def (x: Integer) + (y: Integer): Integer = ... # defines +
```
The difference here is that the parens cover the entire pattern.
In other words, only use an extract for a topParen expression.
The bug is that:
```
def (x) + (y)
```
is being conflated with
```
def (x + y)
```
=> parser: an opening paren should not make an operator an extractor

README.md, scripts/wake2rst.py
=> Fix sphinx documentation generation

share/wake/lib/system/cp.wake, share/wake/lib/system/environment.wake, share/wake/lib/system/incremental.wake, share/wake/lib/system/os.wake, share/wake/lib/system/path.wake, share/wake/lib/system/sources.wake
=> system: reformat and add type signatures

.gitignore, bsp/bsp.wake, build.wake, common/common.wake, fuse/fuse.wake, gopt/gopt.wake, lsp/emscripten.wake, lsp/lsp.wake, preload/preload.wake, re2c/re2c.wake, share/wake/lib/gcc_wake/gcc.wake, share/wake/lib/gcc_wake/pkgconfig.wake, shim/shim.wake, src/wake.wake, utf8proc/utf8proc.wake, wakebox/build.wake
Also reformat the code to use modern styling.
=> build: update to use Results instead of BadPaths

fuse/daemon.cpp
It turned out the issue I was trying to debug was NOT a fuse issue, but this
improved output helped me to confirm that.
=> wake-fused: improve logging quality

share/wake/lib/gcc_wake/gcc.wake, src/compat/aligned_alloc.c, src/dst/primfn.h, src/parser/wakefiles.h, src/runtime/regexp.cpp, src/runtime/value.cpp, src/runtime/value.h, vendor/emscripten.wake, vendor/re2.patch, vendor/re2.wake
Blinding disabling a few fancier features seems to have improved LSP reliability.
=> WASM memory tweaks

src/dst/bind.cpp
Should fix this long open bug with duplicate symbols.
=> bind: fix assertion failure on duplicate package symbols

src/dst/bind.cpp
def x = y + 1
def y = z + 1
def z = x + 1
build.wake:160:[9-13]: definition of 'z@build_wake' references 'x@build_wake' forming an illegal cyclic value
build.wake:159:[9-13]: definition of 'y@build_wake' references 'z@build_wake' forming an illegal cyclic value
build.wake:158:[9-13]: definition of 'x@build_wake' references 'y@build_wake' forming an illegal cyclic value
=> bind: improve error message for cyclic definitions

extensions/vscode/package.json, src/dst/bind.cpp, src/dst/expr.cpp, src/dst/expr.h, src/dst/todst.cpp, src/optimizer/inline.cpp, src/optimizer/ssa.cpp, src/optimizer/ssa.h, src/optimizer/tossa.cpp, src/runtime/tuple.cpp, src/runtime/tuple.h, src/runtime/value.cpp, src/util/location.h, tools/lsp-wake/lsp.cpp
This tries to strike a lazier balance about updating the source files.
=> Self contained locations

src/dst/todst.cpp, tests/dst/colon/fail.sh, tests/dst/colon/stderr, tests/dst/colon/test.wake, tests/dst/packages/fail.sh, tests/dst/packages/stderr, tests/dst/packages/test.wake, tests/dst/packages/test2.wake, tests/dst/packages/test3.wake, tests/dst/typedef/fail.sh, tests/dst/typedef/stderr, tests/dst/typedef/test.wake, tools/wake/main.cpp
These don't test everything, but more is better than less.
=> Parser unit tests

tools/lsp-wake/astree.cpp, tools/lsp-wake/astree.h, tools/lsp-wake/json_converter.cpp, tools/lsp-wake/json_converter.h, tools/lsp-wake/lsp.cpp, tools/lsp-wake/symbol_definition.h
Split lsp.cpp into server part, ast part, and json converter part.
=> lsp restructure

src/dst/bind.cpp
Even if you manage to run with no wakefiles in the workspace and a missing
standard library, wake should not segault.
Now you get this:
```
terpstra@pumpkin:~/wake/x$ ../bin/wake  -x Unit
<command-line>:1:[9-12]: reference to undefined variable 'Unit'
src/types/sums.cpp:54:1: required data type Boolean@wake not defined
src/types/sums.cpp:65:1: required data type Order@wake not defined
src/types/sums.cpp:76:1: required data type List@wake not defined
src/types/sums.cpp:85:1: required data type Unit@wake not defined
src/types/sums.cpp:94:1: required data type Pair@wake not defined
src/types/sums.cpp:104:1: required data type Result@wake not defined
src/types/sums.cpp:119:1: required data type JValue@wake not defined
>>> Aborting without execution <<<
```
=> bind: do not segfault if there are no wakefiles

tools/lsp-wake/lsp.cpp
When a file is deleted, its diagnostics are cleaned.
When a file is created/deleted, needsUpdate is set to true to account for created/deleted/renamed files.
This allows to create/delete/rename not only files, but folders too.
=> lsp: support creating/deleting/renaming files

extensions/vscode/package.json
=> vscode: bump version

src/runtime/database.cpp
Fixes #556.
db.open should obtain exclusive access so db.prepare is guaranteed to succeed.
With locking_mode=exclusive, once a database obtains shared permission, it
never returns it until the database is closed.  Similarly, it never releases
exclusive, once obtained.
Previously, if the schema already existed, db.open would only put the
database into shared state, since nothing was written.  The new 'update
where 0' ensures that exclusive permission is obtained by db.open.
However, this new policy makes it necessary for db.open to close the
database between attempts.  Otherwise, two racing instances can end up with
both connections in shared state, never able to upgrade to exclusive.
=> database: fix race condition when opening database

tools/fuse-waked/fuse-waked.cpp
This bug has haunted us for half a year!
Finally, I think the true root cause has been identified and fixed!
We may want to make a 0.20.1 release. Let's see how it goes.
=> Fix FUSE disconnect

Makefile
Searches one directory deeper for .o files and adds the updated paths
for the generated lexer and parser files.
=> make clean: Fix paths changed by the reorganization of the repo.

src/runtime/database.cpp, src/runtime/database.h, tools/wake/describe.cpp, tools/wake/main.cpp
Record and report the command-line used to invoke wake.
This information is made available with `-v` in combination with `-i` `-o` `--failed` `--last`.
Fixes #586 
Fixes #673
=> Save command line

src/dst/bind.cpp
A `publish` with the wrong type should put the error message at the location
of the publish, not the topic.
Fixes #805.
=> bind: fix publish type error locations

src/runtime/string.cpp
Since wake tries to make the entire path from / for absolute paths,
we must accept that some of the steps in that chain may already exist
and be owned by another user... like root.
=> mkdir: must succeed on extant absolute dirs

.gitignore, .vscode/c_cpp_properties.json, .vscode/settings.json
Turns out that vscode is pretty handy also for C++.
=> vscode: add configuration so C++ code works in vscode

src/dst/bind.cpp, src/dst/todst.cpp, src/types/datatype.cpp, src/types/datatype.h, tools/lsp-wake/astree.cpp, tools/lsp-wake/astree.h, tools/lsp-wake/symbol_definition.h
Add types to use/definition table in the LSP.
Fixes #819
=> Goto type definitions

src/dst/todst.cpp
=> dst: don't insert false location for if-then-else constructors

share/wake/lib/core/list.wake
This change performs three updates:
1) Updates all functions to use markdown
2) Updates a few functions with nicer markdown
3) Updates many (but not all) functions with extra info
Please check the following:
* Spelling
* All added examples
* All added properties
* Grammar and general clarity of added content
* For needlessly verbose or unwanted examples/conditions
=> Update doc comments for list.wake

src/runtime/status.cpp
A terminal might support colour manipulation without intensity control.
Now wake continues with colour on those systems without segfaulting.
At issue was tigetstr for intensity returning nullptr, fed to strlen.
This didn't normally happen, because the request was guarded by sgr0.
=> status: support terminals without intensity

LICENSE, extensions/vscode/vscode.wake, src/runtime/database.cpp, src/runtime/database.h, src/util/diagnostic.h, tools/lsp-wake/astree.cpp, tools/lsp-wake/astree.h, tools/lsp-wake/json_converter.cpp, tools/lsp-wake/json_converter.h, tools/lsp-wake/lsp.cpp, tools/lsp-wake/lsp.wake, tools/lsp-wake/symbol_definition.h, tools/wake/describe.cpp, tools/wake/timeline.cpp
Timeline code is cleaned and sped up.
Years and misprints in licenses are corrected.
=> Minor changes to timeline and licenses

tools/wakebox/wakebox.cpp
In https://github.com/sifive/wake/pull/872 the CLI for fuse-wake and wakebox were placed in a single file.
This PR attempts to reduce the divergence between the two implementations by making parts of the wakebox cli conditionally compiled.
Command line options that don't rely on linux's user namespaces functionality are made available to non-linux platforms.
The previous fuse-wake implementation of the CLI is removed entirely.
The CLI on MacOS now looks like:
```
Usage: wakebox [OPTIONS]
NOTE: Reduced command line options due to operating system support.
Mount options, uid/gid control and network isolation in the input parameters file
will be ignored.
Batch options                                                                                 
-p --params FILE         Json file …
```
=> Integrate wakebox linux and non-linux cli options

debian/changelog.in
After this lands I'll tag this as v0.27.0-alpha and the release will be complete.
=> Bumping to 0.27-alpha

debian/changelog.in
Ok I messed this up the first time but I've got it down now. I was going off the meeting notes I had with Wes and those did not contain the details that Richard's doc contained on getting the artifacts all squared away. I think this should work to produce the release AND generate artifacts as well.
=> Relase v0.26

.circleci/config.yml, docs, scripts/fetch, share/doc/wake/how-to/create-a-release.adoc
also:
* removed some commented out parts from a yaml file that shouldn't be there
* added a top-level symlink to where the documentation lives, cause I always forget
=> Update release artifact fetch script for new/removed OS

debian/changelog.in, share/wake/lib/system/job.wake
Minor release with just one patch for isolating the return code
=> Release 0.26.1

share/wake/lib/core/option.wake
now this function does what is says on the tin
=> Fix isNone

tools/fuse-waked/fuse-waked.cpp
If a directory existed on the underlying filesystem and was non-empty, but appeared to be empty within wakebox/fuse-waked, then fuse-waked would disallow the rmdir() even though it appeared to be empty. This could confuse a process that would think it's entitled to remove a writeable empty dir it had created (note: this means the directory is not in the 'visible' list).
This PR attempts to allow the _fiction_ of a successful rmdir() by letting the fuse client believe that the directory is gone, even though the underlying storage is left as-is.
Example of the issue:
```
$ cat bug.json
{
"command": [
"bash",
"-c",
"set -x; mkdir testdir/foo; ls -l -a testdir/foo; rm -rf testdir/foo"
],
"environment": [ "PATH=/usr/bin:/bin" ],
"directory": ".",
"mount-ops": [
{
"type": "workspace", …
```
=> fuse-waked: allow directories that appear to be empty to rmdir()

share/wake/lib/core/list.wake
This change adds the unary comma operator as the singleton list operation which can be used to improve list syntax.
=> [wake stdlib][list] Add unary comma operator

share/doc/wake/tutorial.md
The `tutorial.md` wasn't actually as out-of-date as I feared it might be, though it definitely still needed quite a few changes to reflect the current API.  I haven't looked into the rest of the docs yet, but am planning on doing so soon.
@ErikParawell-SiFive, @marshalla-sifive, @michelyalu, you've all been mentioned as wanting to learn Wake.  I've been meaning to talk with all of you a bit more closely, but if you have the time, mind reading through [the new `tutorial.md`](https://github.com/sifive/wake/blob/5c42ecc5c193bcad6c2e248d8a31b0b7cee20401/share/doc/wake/tutorial.md) as newcomers to the language and letting me know about any parts of it that are confusing or any questions it leaves you with?  I know part of the difficulty in learning is the jump from focused documentation to …
=> tutorial: update after the BadPath and subsequent Result changes

build.wake, share/wake/lib/system/job.wake, src/runtime/database.cpp, src/runtime/database.h, src/runtime/job.cpp
This change adds support for tracking unhashed files in wake so that they can be removed via --clean and listed via --list-outputs.
=> Unhashed files

share/doc/wake/tutorial.md
When reading through it, I thought it would be nice to have a table of contents to better sort through it so I added one.
=> Add a table of contents to the tutorial

Makefile, share/wake/lib/gcc_wake/gcc.wake
I got annoyed with this warning that I introduced. It isn't easily fixable however and it's just being overly strict in this case so I'm setting it to not warn. Hopefully this should fix the issue.
=> Fix the warning

src/runtime/prim.cpp
This restores two lines erroneously removed by 93c43ac88769fb9fc57983a6e76eac3ff5336d47
=> prim: "hash" should not return -1!

src/wcl/filepath.h, src/wcl/trie.h, src/wcl/xoshiro_256.h, tools/job-cache/bloom.h, tools/job-cache/hash.h, tools/job-cache/job-cache.cpp, tools/job-cache/job-cache.wake
This change is intended to add reading of jobs from the cache, with handling for directories and sandbox to real world redirection.
=> Job cache read

src/wcl/diff.h, tests/wake-unit/stdout, tools/wake-format/wake-format.cpp, tools/wake-unit/diff.cpp, tools/wake-unit/unit.h
This needs some work (tests, pretty printing, etc...) but I think using this a base for something a lot better than just calling `diff`
=> Sketch of diff algorithm

src/wcl/doc_state.h, tools/wake-unit/doc.cpp
This PR extracts the max width code from the binop full choice PR
=> Implement max width monoid

extensions/vscode/package.json.in
Add path to icon in package.json.in
=> vscode: fix extension icon

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Formats the following subtrees
- multiline strings
- publish
- target
- require else
=> Format several subtrees

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/actions.h, tools/wake-format/catters.h, tools/wake-format/emitter.cpp, tools/wake-format/formatter.h
Ex:
```
export def vfoldl (combiningFn: accum => element => accum): accum => Vector element => accum =
def loop accumulator v s e =
if s == e then
accumulator
else
def element = vget v s
loop (combiningFn accumulator element) v (s+1) e
def top a (Vector v s e) =
loop a v s e
top
```
and
```
def loop a s e =
if s == e then
e
else if stopFn (vget a s) then
s
else
loop a (s+1) e
```
=> Format if subtrees with blocks or nested ifs

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Support formatting `target` subtrees with patterns on the LHS
=> Support patterns in targets

src/runtime/status.cpp, tools/wake/main.cpp
Fix the descriptor issues we noticed in the last meeting.
=> Don't trust user descriptors

share/doc/wake/tutorial.md
linkO's signature changed in df1b122
Also fixed a missing "
Also fixed the code snip that covers curl
=> Fix linkO args in tutorial.md

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Formats UNARY subtrees. Any wsnl between a unary and the parameter is removed
=> format unary subtree

debian/changelog.in
I apparently need some new commit to open a PR to generate the release artifacts, so here's an inconsequential timestamp bump to differentiate the branch.
=> Release 0.29.0

src/dst/bind.cpp
On newer versions of fedora (and possible Arch, not confirmed) the bootstrapped build of wake `./bin/wake build default` fails with a SEGFAULT. This is due to UB allowing the re-order of parameter execution. This error wasn't seen previously as there wasn't a compiler reordering the calls. 
Update the code to force the `release()` to happen after the pointer has been captured
=> Fix UB causing objects to be freed early

README.md
=> Add m4 to external dependencies

src/parser/wakefiles.cpp, tools/wake/main.cpp
Prints out a progress message if startup takes longer than a second.
=> profile steps before executing wake source

debian/changelog.in
Release using the new non-release branch flow. Docs to follow (writing them as I go through the process).
Now release changes get merged directly into master.
We don't need to merge `v0.29` into `master` since @ag-eitilt updated that with the previous release
=> Update changelog for v0.29.2

Makefile, share/doc/wake/how-to/create-a-release.adoc
Updates the release docs to use automatic release generation and no release branching
=> Update release docs

src/runtime/status.cpp, src/runtime/term.cpp, src/runtime/value.cpp, src/types/type.cpp, src/util/term.h, tools/wake-unit/unit.cpp, tools/wake-unit/unit.h, tools/wake/main.cpp
Step 3 of splitting https://github.com/sifive/wake/pull/868
=> move term functions to dedicated file

share/wake/lib/system/environment.wake, src/runtime/term.cpp, src/util/term.h, tests/tests.wake, tests/wake-unit/stdout, tests/wake-unit/unit-test.sh, tools/wake-unit/term.cpp, tools/wake-unit/unit.cpp
This should be the final prep PR and the next PR will include actually emitting color in `--failed` and the like.
This PR introduces TermInfoBuf, FdBuf, and the associated tests but does not directly use any of them.
=> Create TermInfoBuf and FdBuf

share/wake/lib/core/string.wake, share/wake/lib/system/io.wake, share/wake/lib/system/job.wake, src/job-cache/job-cache.cpp, src/runtime/string.cpp
This change adds some significant improvements to the shared cache and identifies a few more areas to work on.
1) It adds hash_str for all the value hashing stuff we do. This is in place of the original `hash` which is non-deterministic because it hashes addresses which was a big surprise to me
2) Files containing the same content (and thus that have the same hash) are now handled correctly where as before it would cause errors or cache misses
3) These changes have been successfully tested on a large repository.
We do know of a few issues however:
1) output directories and symlinks are not handled correctly by AddJobRequest or Cache::add
2) I realized that I left the threaded file copies in the code even now that its in the wake binary. This is a problem because one of those threads could …
=> Bugsquashing

src/parser/wakefiles.cpp, src/parser/wakefiles.h, src/runtime/sources.cpp, src/wcl/filepath.h, tests/wake-unit/stdout, tools/lsp-wake/lsp.cpp, tools/wake-unit/filepath.cpp, tools/wake/main.cpp
Moves `make_canonical` to `wcl`, adds tests, and per DM removes windows support
=> move make_canonical to wcl

extensions/vscode/vscode.wake, share/wake/lib/gcc_wake/gcc.wake, share/wake/lib/gcc_wake/pkgconfig.wake, share/wake/lib/system/io.wake, share/wake/lib/system/path.wake, share/wake/lib/system/sources.wake, tests/runtime/symlinks/test.wake, vendor/git.wake, vendor/lemon/lemon.wake, vendor/re2c.wake
There were several Plans within wake that didn't have labels. This change adds labels everywhere they were missing.
=> Set labels for all plans

tools/wakebox/wakebox.cpp
It is sometimes useful to take a params file created by a wake run and run it interactively with additional bind mounts. Previously, --bind was ignored when --params is specified, but now additional binds are appended to the ones specified by the params file.
=> wakebox: Allow --bind with --params file.

tools/lsp-wake/lsp.cpp
Per the spec, certain notifications (a message send without and `id` field) may be ignored. This change ignores those messages when they are unrecognized instead of generating an error.
=> Don't send response to unsupported $/ notifications

src/job_cache/job_cache.cpp, src/wcl/unique_fd.h
This change just move's job_cache's unique_fd into wcl so that it can be used more widely.
=> Promote unique_fd to wcl

tools/wake/cli_options.h, tools/wake/main.cpp
Moves validation logic to CommandLineOptions, also moves the env fallback for some options into CommandLineOptions
=> cli: Move validation and env parsing to CLO

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
After recent changes a couple formatting cases were asserting/emitting invalid code. This change fixes those cases and adds tests for them.
It also removes some unused code
=> format: Fixup failing cases

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Explicitly call out and document "human flat" which is an emitted doc where the only newlines are created by comments
=> format: Small refactor for "human flat"

tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
=> format: fix indentation for suffix binops

src/runtime/status.cpp, src/runtime/status.h
I hope so much that this fixes the issue.
=> Fix segfault in destructor

src/job_cache/eviction_policy.cpp, src/job_cache/job_cache.cpp, src/job_cache/schema.sql, tests/tests.wake, tests/wake-unit/stdout, tests/wake-unit/unit-test.sh, tools/wake-unit/fuzz_test_job_cache.cpp
This change adds fuzz testing for the shared cache and fixes a couple bugs that it found!
=> Add basic fuzz testing for the shared cache

.gitignore, Makefile, build.wake, src/job_cache/daemon_cache.cpp, src/job_cache/job_cache.cpp, tools/job-cache/job-cache.wake, tools/job-cache/main.cpp, wake.spec.in
job-cache daemon is now launched as a separate binary instead of just forking
=> Convert job-cache to binary

tools/wake-format/main.cpp
adds a quiet flag to print out failing files without a diff
=> Add --quiet flag for wake-format dry-run

share/doc/wake/logging.md, share/wake/lib/core/print.wake, src/runtime/status.cpp, src/runtime/status.h, tools/wake/main.cpp
Reverts sifive/wake#1302
This is a short term revert to enable a fast patch release for a shared cache bug.
=> Revert "Add logInteractive, remove echo from no-tty, update docs"

.circleci/config.yml, .circleci/dockerfiles/ubuntu-18.04, .github/workflows/build.yaml, scripts/fetch
Ubuntu 18.04 is end-of-life
This PR removes it from CI
=> CI: remove ubuntu 18.04

share/doc/wake/logging.md, share/wake/lib/core/print.wake, src/runtime/status.cpp, src/runtime/status.h, tools/wake/main.cpp
Reverts sifive/wake#1310
Restore log interactive now that v37.0.0 has been released
=> Revert "Revert "Add logInteractive, remove echo from no-tty, update docs""

src/job_cache/daemon_cache.cpp, src/job_cache/eviction_policy.cpp, src/job_cache/job_cache_impl_common.h, tools/wake-format/emitter.cpp
I goofed this up multiple times because its hard to test, this fixes it yet again.
=> Fix group id dir being the hex of a 4-byte integer instead of a 1-byte integer

rust/gsc/src/gsc/api_key_check.rs, rust/gsc/src/gsc/main.rs
This change adds a check to to make sure that the user has supplied a valid api key when performing a write.
=> Add api key check for writes

debian/changelog.in
Sync changelog.in changes from one-off release branch into master
=> Sync changelog.in to latest release

tools/wake/main.cpp
This PR is a small refactor to make the "support tag inspection" change easier. This refactor shouldn't result in any functional changes to wake. 
The plan is for 3 or  4 PR as follows
- Mild refactor to exact db inspection out of main (this change)
- Normalize all the db command that take parameters to accept globs
- make repeating a command be AND; make adding a `,` be OR
- implement tag inspection
=> Mild refactor of database inpection

share/wake/lib/core/string.wake, src/runtime/string.cpp
This PR just adds primitives for converting to all upper case and all lower case, we I recently needed but didn't have access to.
=> Add toUpper and toLower

rust/rsc/src/rsc/add_job.rs, rust/rsc/src/rsc/api_key_check.rs, rust/rsc/src/rsc/read_job.rs, rust/rsc/src/rsc_tool/main.rs
Various cleanups and code formatting
=> Code cleanup & format

rust/rsc/src/rsc/main.rs
Adds a TTL eviction loop that runs every 10 minutes to delete expired jobs.
=> rsc: Implement basic TTL eviction for jobs

rust/rsc/src/common/config.rs, rust/rsc/src/rsc/main.rs, rust/rsc/src/rsc_tool/main.rs
Renames the last remaining parts from old GSC name
=> rsc: Finalize tool rename

rust/rsc/src/rsc/blob.rs, rust/rsc/src/rsc/blob_store_service.rs, rust/rsc/src/rsc/main.rs
Implements blob eviction loop for RSC. Depends on blob resolution PR landing first.
=> rsc: Implement blob eviction

rust/log_viewer/build.wake, rust/rsc/rsc.wake, share/wake/lib/core/result.wake, share/wake/lib/rust_wake/cargo.wake, tests/wake-format/basic/basic.wake, tests/wake-format/basic/stdout, tools/wake-format/emitter.cpp
Result pipelines allow for much nicer user APIs (when designed for). This PR adds operators to allow for such pipelines
=> stdlib: Add |> and |< operators for result pipelines

tools/wake/cli_options.h, tools/wake/describe.cpp, tools/wake/describe.h, tools/wake/main.cpp
Just like the default db inspection rendering but without stdout/stderr
=> Add --simple db inspection flag

rust/rsc/src/common/database.rs, rust/rsc/src/rsc_tool/main.rs
Adds command to rsc_tool for searching jobs by label and deleting jobs by id
=> rsc: Add job search and remove

rust/rsc/.config.json, rust/rsc/src/bin/rsc/config.rs, rust/rsc/src/bin/rsc/main.rs, rust/rsc/src/bin/rsc_tool/main.rs
Many "I'll make that a config later" promises were made. This PR makes good on those promises and sets some reasonable defaults. LRU configs were added but are not yet used
=> rsc: Convert various constants to config vars

share/doc/wake/how-to/create-a-release.adoc
Removes the doc steps that are skipped every time when making a release
=> docs: Update release process documentation

debian/changelog.in
Following the release process to release Wake v44.3.0
=> Set release date.

README.md
There are probably more of these i did not make any attempt to be thorough.
=> Update broken README.md URLs after migration to sifiveinc

share/doc/wake/basic_wake_tutorial.md
=> Additional missed github link update for sifiveinc

tools/bsp-wake/main.cpp
The build server spams requests for compile of no projects. Don't build in that case.
Also: pass the desired project to wake vscode.
That requires a matching change.
=> bsp-wake: only build the requested project
